

# for use in api calls


ADDRESS = "address"
ADDRESSPREFIX = "addressPrefix"
ADDRESSTYPE = "addressType"
AGENTADDRESS = "agentAddress"
AGENTHASH = "agentHash"
ALGORITHM = "algorithm"
ALIAS = "alias"
ALLHITS = "allHits"
AMOUNT = "amount"
ARGS = "args"
ASSETCHAINID = "assetChainId"
ASSETID = "assetId"
ASSETIDS = "assetIds"
ASSETINFOLIST = "assetInfoList"
ASSETNAME = "assetName"
ASSETS = "assets"
BEGIN = "begin"
BLOCK = "block"
BLOCKHASH = "blockHash"
BLOCKHEADER = "blockHeader"
BLOCKHEIGHT = "blockHeight"
BLOCKTIME = "blockTime"
BLOCKTYPE = "blockType"
BYTECOUNT = "byteCount"
CHAINID = "chainId"
CHAINNAME = "chainName"
CIRCULATECHAINID = "circulateChainId"
CMD = "cmd"
CMDREGISTERLIST = "cmdRegisterList"
COMMAND = "command"
COMMISSIONRATE = "commissionRate"
CONTRACTADDRESS = "contractAddress"
CONTRACTBALANCE = "contractBalance"
CONTRACTCODE = "contractCode"
CONTRACTLIST = "contractList"
CONTRACTNONCE = "contractNonce"
CONTRACTSENDER = "contractSender"
COUNT = "count"
DATA = "data"
DECIMALPLACES = "decimalPlaces"
DELLIST = "delList"
DEPOSIT = "deposit"
DOWNLOAD = "download"
END = "end"
ENDHEIGHT = "endHeight"
ENDTIMESTAMP = "endTimestamp"
EVIDENCEHEADER = "evidenceHeader"
EXCLUDENODES = "excludeNodes"
EXTEND = "extend"
EXTENDSDATA = "extendsData"
FRESTARTIFRUNNING = "fRestartIfRunning"
FILEPATH = "filePath"
GASLIMIT = "gasLimit"
HASH = "hash"
HASHLIST = "hashList"
HEADERLIST = "headerList"
HEIGHT = "height"
INITNUMBER = "initNumber"
INPUTS = "inputs"
INTCOUNT = "intCount"
INTERVAL = "interval"
ISCONFIRMED = "isConfirmed"
ISCROSS = "isCross"
ISCROSSGROUP = "isCrossGroup"
JARFILEDATA = "jarFileData"
JOINAGENTHASH = "joinAgentHash"
KEYSTORE = "keyStore"
KEYWORD = "keyWord"
LMAXCPUS = "lMaxCPUs"
LMODULENAME = "lModuleName"
LMODULEVERSION = "lModuleVersion"
LIST = "list"
LISTFROM = "listFrom"
LISTTO = "listTo"
LONGCOUNT = "longCount"
MAGICNUMBER = "magicNumber"
MAXIN = "maxIn"
MAXOUT = "maxOut"
MAXSIGNATURECOUNT = "maxSignatureCount"
MAXTXDATASIZE = "maxTxDataSize"
MESSAGEBODY = "messageBody"
METHODDESC = "methodDesc"
METHODNAME = "methodName"
MINAVAILABLECOUNT = "minAvailableCount"
MINAVAILABLENODENUM = "minAvailableNodeNum"
MINSIGNS = "minSigns"
MODULECODE = "moduleCode"
NEWPASSWORD = "newPassword"
NODEID = "nodeId"
NODES = "nodes"
OUTPUTS = "outputs"
OVERWRITE = "overwrite"
PACKAGING = "packaging"
PACKINGADDRESS = "packingAddress"
PAGENUMBER = "pageNumber"
PAGESIZE = "pageSize"
PASSWORD = "password"
PERCENT = "percent"
PRESTATEROOT = "preStateRoot"
PREFIXLIST = "prefixList"
PRIKEY = "priKey"
PRICE = "price"
PROTOCOLCMDS = "protocolCmds"
PROTOCOLVERSION = "protocolVersion"
PUBKEY = "pubKey"
PUBKEYS = "pubKeys"
REGISTERTIME = "registerTime"
REMARK = "remark"
REWARDADDRESS = "rewardAddress"
ROLE = "role"
ROUND = "round"
SEEDIPS = "seedIps"
SENDER = "sender"
SHORTCOUNT = "shortCount"
SIG = "sig"
SIGNADDRESS = "signAddress"
SIGNPASSWORD = "signPassword"
SIGNATUREBFTRATIO = "signatureBFTRatio"
SIZE = "size"
STARTHEIGHT = "startHeight"
STARTPAGE = "startPage"
STATE = "state"
STATEROOT = "stateRoot"
STATUS = "status"
SYMBOL = "symbol"
TOADDRESS = "toAddress"
TX = "tx"
TXHASH = "txHash"
TXHASHLIST = "txHashList"
TXLIST = "txList"
TYPE = "type"
USABLE = "usable"
VALUE = "value"
VERIFIERLIST = "verifierList"


# list of callable api's and their necessary parameters
REGISTERAPI: []
AC_ADDADDRESSPREFIX: [PREFIXLIST]
AC_CREATEACCOUNT: [CHAINID, COUNT, PASSWORD]
AC_CREATECONTRACTACCOUNT: [CHAINID]
AC_CREATEMULTISIGNACCOUNT: [CHAINID, PUBKEYS, MINSIGNS]
AC_CREATEMULTISIGNTRANSFER: [CHAINID, INPUTS, OUTPUTS, REMARK, SIGNADDRESS, SIGNPASSWORD]
AC_CREATEOFFLINEACCOUNT: [CHAINID, COUNT, PASSWORD]
AC_EXPORTACCOUNTKEYSTORE: [CHAINID, ADDRESS, PASSWORD, FILEPATH]
AC_EXPORTKEYSTOREJSON: [CHAINID, ADDRESS, PASSWORD]
AC_GETACCOUNTBYADDRESS: [CHAINID, ADDRESS]
AC_GETACCOUNTLIST: [CHAINID]
AC_GETADDRESSLIST: [CHAINID, PAGENUMBER, PAGESIZE]
AC_GETADDRESSPREFIXBYCHAINID: [CHAINID]
AC_GETALIASBYADDRESS: [CHAINID, ADDRESS]
AC_GETALLADDRESSPREFIX: []
AC_GETALLPRIKEY: [CHAINID, PASSWORD]
AC_GETENCRYPTEDADDRESSLIST: [CHAINID]
AC_GETMULTISIGNACCOUNT: [CHAINID, ADDRESS]
AC_GETPRIKEYBYADDRESS: [CHAINID, ADDRESS, PASSWORD]
AC_GETPUBKEY: [CHAINID, ADDRESS, PASSWORD]
AC_IMPORTACCOUNTBYKEYSTORE: [CHAINID, PASSWORD, KEYSTORE, OVERWRITE]
AC_IMPORTACCOUNTBYPRIKEY: [CHAINID, PASSWORD, PRIKEY, OVERWRITE]
AC_ISALIASUSABLE: [CHAINID, ALIAS]
AC_ISMULTISIGNACCOUNTBUILDER: [CHAINID, ADDRESS, PUBKEY]
AC_REMOVEACCOUNT: [CHAINID, ADDRESS, PASSWORD]
AC_REMOVEMULTISIGNACCOUNT: [CHAINID, ADDRESS]
AC_SETALIAS: [CHAINID, ADDRESS, PASSWORD, ALIAS]
AC_SETMULTISIGNALIAS: [CHAINID, ADDRESS, ALIAS, SIGNADDRESS, SIGNPASSWORD]
AC_SETREMARK: [CHAINID, ADDRESS, REMARK]
AC_SIGNBLOCKDIGEST: [CHAINID, ADDRESS, PASSWORD, DATA]
AC_SIGNDIGEST: [CHAINID, ADDRESS, PASSWORD, DATA]
AC_SIGNMULTISIGNTRANSACTION: [CHAINID, TX, SIGNADDRESS, SIGNPASSWORD]
AC_TRANSFER: [CHAINID, INPUTS, OUTPUTS, REMARK]
AC_UPDATEOFFLINEACCOUNTPASSWORD: [CHAINID, ADDRESS, PASSWORD, NEWPASSWORD, PRIKEY]
AC_UPDATEPASSWORD: [CHAINID, ADDRESS, PASSWORD, NEWPASSWORD]
AC_VALIDATIONPASSWORD: [CHAINID, ADDRESS, PASSWORD]
AC_VERIFYSIGNDATA: [PUBKEY, SIG, DATA]
BATCHVALIDATEBEGIN: [CHAINID]
BLOCKVALIDATE: [CHAINID, TXLIST, BLOCKHEIGHT]
CANCELCROSSCHAIN: [CHAINID, ASSETID]
CHECKBLOCKVERSION: [CHAINID, EXTENDSDATA]
CLEARUNCONFIRMTXS: [CHAINID]
CM_ASSET: [CHAINID, ASSETID]
CM_ASSETCIRCULATECOMMIT: [CHAINID, TXLIST, BLOCKHEADER]
CM_ASSETCIRCULATEROLLBACK: [CHAINID, TXLIST, BLOCKHEADER]
CM_ASSETCIRCULATEVALIDATOR: [CHAINID, TX]
CM_ASSETDISABLE: [CHAINID, ASSETID, ADDRESS, PASSWORD]
CM_ASSETREG: [CHAINID, ASSETID, SYMBOL, ASSETNAME, INITNUMBER, DECIMALPLACES, ADDRESS, PASSWORD]
CM_CHAIN: [CHAINID]
CM_CHAINACTIVE: [CHAINID, CHAINNAME, ADDRESSTYPE, ADDRESSPREFIX, MAGICNUMBER, MINAVAILABLENODENUM, ASSETID, SYMBOL, ASSETNAME, INITNUMBER, DECIMALPLACES, ADDRESS, PASSWORD, VERIFIERLIST, SIGNATUREBFTRATIO, MAXSIGNATURECOUNT]
CM_CHAINREG: [CHAINID, CHAINNAME, ADDRESSTYPE, ADDRESSPREFIX, MAGICNUMBER, MINAVAILABLENODENUM, ASSETID, SYMBOL, ASSETNAME, INITNUMBER, DECIMALPLACES, ADDRESS, PASSWORD, VERIFIERLIST, SIGNATUREBFTRATIO, MAXSIGNATURECOUNT]
CM_GETCHAINASSET: [CHAINID, ASSETCHAINID, ASSETID]
CM_GETCHAINSSIMPLEINFO: []
CM_GETCIRCULATECHAINASSET: [CIRCULATECHAINID, ASSETCHAINID, ASSETID]
COMMITBATCHUNCONFIRMEDTXS: [CHAINID, TXLIST]
COMMITBLOCKTXS: [CHAINID, TXLIST, BLOCKHEIGHT]
COMMITUNCONFIRMEDTX: [CHAINID, TX]
CONNECTREADY: []
CREATEAGENTVALID: [CHAINID, TX]
CREATECROSSTX: [CHAINID, LISTFROM, LISTTO, REMARK]
CROSSCHAINREGISTERCHANGE: [CHAINID]
CS_ADDBLOCK: [CHAINID, BLOCKHEADER]
CS_ADDEVIDENCERECORD: [CHAINID, BLOCKHEADER, EVIDENCEHEADER]
CS_CHAINROLLBACK: [CHAINID, HEIGHT]
CS_CONTRACTDEPOSIT: [CHAINID, AGENTHASH, DEPOSIT, CONTRACTADDRESS, CONTRACTSENDER, CONTRACTBALANCE, CONTRACTNONCE, BLOCKTIME]
CS_CONTRACTWITHDRAW: [CHAINID, JOINAGENTHASH, CONTRACTADDRESS, CONTRACTSENDER, CONTRACTBALANCE, CONTRACTNONCE, BLOCKTIME]
CS_CREATEAGENT: [CHAINID, AGENTADDRESS, PACKINGADDRESS, REWARDADDRESS, COMMISSIONRATE, DEPOSIT, PASSWORD]
CS_CREATECONTRACTAGENT: [CHAINID, PACKINGADDRESS, DEPOSIT, COMMISSIONRATE, CONTRACTADDRESS, CONTRACTSENDER, CONTRACTBALANCE, CONTRACTNONCE, BLOCKTIME]
CS_CREATEMULTIAGENT: [CHAINID, AGENTADDRESS, PACKINGADDRESS, REWARDADDRESS, COMMISSIONRATE, DEPOSIT, PASSWORD, SIGNADDRESS]
CS_DEPOSITTOAGENT: [CHAINID, ADDRESS, AGENTHASH, DEPOSIT, PASSWORD]
CS_DOUBLESPENDRECORD: [CHAINID, BLOCK, TX]
CS_GETAGENTADDRESSLIST: [CHAINID]
CS_GETAGENTCHANGEINFO: [CHAINID]
CS_GETAGENTINFO: [CHAINID, AGENTHASH]
CS_GETAGENTLIST: [CHAINID, PAGENUMBER, PAGESIZE, KEYWORD]
CS_GETAGENTSTATUS: [CHAINID, AGENTHASH]
CS_GETCONSENSUSCONFIG: [CHAINID]
CS_GETCONTRACTAGENTINFO: [CHAINID, AGENTHASH, CONTRACTADDRESS, CONTRACTSENDER]
CS_GETCONTRACTDEPOSITINFO: [CHAINID, JOINAGENTHASH, CONTRACTADDRESS, CONTRACTSENDER]
CS_GETDEPOSITLIST: [CHAINID, PAGENUMBER, PAGESIZE, ADDRESS, AGENTHASH]
CS_GETINFO: [CHAINID, ADDRESS]
CS_GETNODEPACKINGADDRESS: [CHAINID]
CS_GETPACKERINFO: [CHAINID]
CS_GETPUBLISHLIST: [CHAINID, ADDRESS, TYPE]
CS_GETROUNDINFO: [CHAINID]
CS_GETROUNDMEMBERLIST: [CHAINID, EXTEND]
CS_GETSEEDNODEINFO: [CHAINID]
CS_GETWHOLEINFO: [CHAINID]
CS_MULTIDEPOSIT: [CHAINID, ADDRESS, AGENTHASH, DEPOSIT, PASSWORD, SIGNADDRESS]
CS_MULTIWITHDRAW: [CHAINID, ADDRESS, TXHASH, PASSWORD, SIGNADDRESS]
CS_RANDOM_RAW_SEEDS_COUNT: [CHAINID, HEIGHT, COUNT]
CS_RANDOM_RAW_SEEDS_HEIGHT: [CHAINID, STARTHEIGHT, ENDHEIGHT]
CS_RANDOM_SEED_COUNT: [CHAINID, HEIGHT, COUNT, ALGORITHM]
CS_RANDOM_SEED_HEIGHT: [CHAINID, STARTHEIGHT, ENDHEIGHT, ALGORITHM]
CS_RECEIVEHEADERLIST: [CHAINID, HEADERLIST]
CS_RUNCHAIN: [CHAINID]
CS_RUNMAINCHAIN: [CHAINID]
CS_STOPAGENT: [CHAINID, ADDRESS, PASSWORD]
CS_STOPCHAIN: [CHAINID]
CS_STOPCONTRACTAGENT: [CHAINID, CONTRACTADDRESS, CONTRACTSENDER, CONTRACTBALANCE, CONTRACTNONCE, BLOCKTIME]
CS_STOPMULTIAGENT: [CHAINID, ADDRESS, PASSWORD, SIGNADDRESS]
CS_TRIGGERCOINBASECONTRACT: [CHAINID, TX, BLOCKHEADER, STATEROOT]
CS_UPDATEAGENTCONSENSUSSTATUS: [CHAINID]
CS_UPDATEAGENTSTATUS: [CHAINID, STATUS]
CS_VALIDBLOCK: [CHAINID, DOWNLOAD, BLOCK]
CS_WITHDRAW: [CHAINID, ADDRESS, TXHASH, PASSWORD]
DEPOSITVALID: [CHAINID, TX]
GETASSETSBYID: [CHAINID, ASSETIDS]
GETBALANCE: [CHAINID, ASSETCHAINID, ASSETID, ADDRESS]
GETBALANCENONCE: [CHAINID, ASSETCHAINID, ASSETID, ADDRESS, ISCONFIRMED]
GETBLOCKBYHASH: [CHAINID, HASH]
GETBLOCKBYHEIGHT: [CHAINID, HEIGHT]
GETBLOCKHEADERBYHASH: [CHAINID, HASH]
GETBLOCKHEADERBYHEIGHT: [CHAINID, HEIGHT]
GETBLOCKHEADERPOBYHASH: [CHAINID, HASH]
GETBLOCKHEADERPOBYHEIGHT: [CHAINID, HEIGHT]
GETBLOCKHEADERSBYHEIGHTRANGE: [CHAINID, BEGIN, END]
GETBLOCKHEADERSFORPROTOCOL: [CHAINID, INTERVAL]
GETBYZANTINECOUNT: [CHAINID]
GETCHAINS: [CHAINID, NODEID, MESSAGEBODY]
GETCIRCULAT: [CHAINID, NODEID, MESSAGEBODY]
GETCROSSCHAININFOS: []
GETCROSSTXSTATE: [CHAINID, TXHASH]
GETCTX: [CHAINID, NODEID, MESSAGEBODY]
GETCTXSTATE: [CHAINID, NODEID, MESSAGEBODY]
GETFREEZELIST: [CHAINID, ASSETCHAINID, ASSETID, ADDRESS, PAGENUMBER, PAGESIZE]
GETFRIENDCHAINCIRCULATE: [CHAINID, ASSETIDS]
GETLATESTBLOCKHEADERS: [CHAINID, SIZE]
GETLATESTROUNDBLOCKHEADERS: [CHAINID, ROUND]
GETNONCE: [CHAINID, ASSETCHAINID, ASSETID, ADDRESS, ISCONFIRMED]
GETOTHERCTX: [CHAINID, NODEID, MESSAGEBODY]
GETREGISTEREDCHAININFOLIST: []
GETROUNDBLOCKHEADERS: [CHAINID, HEIGHT, ROUND]
GETSTATUS: [CHAINID]
GETVERSION: [CHAINID]
INFO: [CHAINID]
LATESTBLOCK: [CHAINID]
LATESTBLOCKHEADER: [CHAINID]
LATESTBLOCKHEADERPO: [CHAINID]
LATESTHEIGHT: [CHAINID]
LISTENERDEPENDENCIESREADY: []
MSGPROCESS: [CHAINID, NODEID, CMD, MESSAGEBODY]
NEWAPIMODULECROSSTX: [CHAINID, TX]
NEWBLOCKHEIGHT: [CHAINID, HEIGHT]
NW_ACTIVECROSS: [CHAINID, MAXOUT, MAXIN, SEEDIPS]
NW_ADDNODES: [CHAINID, ISCROSS, NODES]
NW_BROADCAST: [CHAINID, EXCLUDENODES, MESSAGEBODY, COMMAND, ISCROSS, PERCENT]
NW_CREATENODEGROUP: [CHAINID, MAGICNUMBER, MAXOUT, MAXIN, MINAVAILABLECOUNT, ISCROSSGROUP]
NW_CURRENTTIMEMILLIS: []
NW_DELNODEGROUP: [CHAINID]
NW_DELNODES: [CHAINID, NODES]
NW_GETCHAINCONNECTAMOUNT: [CHAINID, ISCROSS]
NW_GETGROUPBYCHAINID: [CHAINID]
NW_GETGROUPS: [STARTPAGE, PAGESIZE]
NW_GETMAINMAGICNUMBER: []
NW_GETNODES: [CHAINID, STATE, ISCROSS, STARTPAGE, PAGESIZE]
NW_GETSEEDS: []
NW_INFO: [CHAINID]
NW_NODES: [CHAINID]
NW_PROTOCOLREGISTER: [ROLE, PROTOCOLCMDS]
NW_RECONNECT: [CHAINID]
NW_SENDPEERSMSG: [CHAINID, NODES, MESSAGEBODY, COMMAND]
NW_UPDATENODEINFO: [CHAINID, NODEID, BLOCKHEIGHT, BLOCKHASH]
PARAMTESTCMD: [INTCOUNT, BYTECOUNT, SHORTCOUNT, LONGCOUNT]
PROTOCOLREGISTERWITHPRIORITY: [ROLE, PROTOCOLCMDS]
PROTOCOLVERSIONCHANGE: [CHAINID, PROTOCOLVERSION]
RECEIVEPACKINGBLOCK: [CHAINID, BLOCK]
RECVCIRCULAT: [CHAINID, NODEID, MESSAGEBODY]
RECVCTX: [CHAINID, NODEID, MESSAGEBODY]
RECVCTXHASH: [CHAINID, NODEID, MESSAGEBODY]
RECVCTXSIGN: [CHAINID, NODEID, MESSAGEBODY]
RECVCTXSTATE: [CHAINID, NODEID, MESSAGEBODY]
RECVOTHERCTX: [CHAINID, NODEID, MESSAGEBODY]
RECVREGCHAIN: [CHAINID, NODEID, MESSAGEBODY]
REGISTERASSET: [CHAINID, ASSETID, SYMBOL, ASSETNAME, USABLE, DECIMALPLACES]
REGISTERCROSSCHAIN: [CHAINID, CHAINNAME, MINAVAILABLENODENUM, ASSETINFOLIST, REGISTERTIME]
REGISTERMODULEDEPENDENCIES: []
REGISTERPROTOCOL: [CHAINID, MODULECODE, LIST]
ROLLBACKBLOCKTXS: [CHAINID, TXLIST, BLOCKHEIGHT]
ROLLBACKUNCONFIRMTX: [CHAINID, TX]
ROLLBACKBLOCK: [CHAINID, BLOCKHEADER]
ROLLBACKTXVALIDATESTATUS: [CHAINID, TX]
SAVEBLOCK: [CHAINID, BLOCKHEADER]
SC_ACCOUNT_CONTRACTS: [CHAINID, ADDRESS, PAGENUMBER, PAGESIZE]
SC_BATCH_BEFORE_END: [CHAINID, BLOCKTYPE, BLOCKHEIGHT]
SC_BATCH_BEGIN: [CHAINID, BLOCKTYPE, BLOCKHEIGHT, BLOCKTIME, PACKINGADDRESS, PRESTATEROOT]
SC_BATCH_END: [CHAINID, BLOCKHEIGHT]
SC_CALL: [CHAINID, SENDER, PASSWORD, VALUE, GASLIMIT, PRICE, CONTRACTADDRESS, METHODNAME, METHODDESC, ARGS, REMARK]
SC_CALL_VALIDATOR: [CHAINID, TX]
SC_CONSTRUCTOR: [CHAINID, CONTRACTCODE]
SC_CONTRACT_INFO: [CHAINID, CONTRACTADDRESS]
SC_CONTRACT_OFFLINE_TX_HASH_LIST: [CHAINID, BLOCKHASH]
SC_CONTRACT_RESULT: [CHAINID, HASH]
SC_CONTRACT_RESULT_LIST: [CHAINID, HASHLIST]
SC_CONTRACT_TX: [CHAINID, HASH]
SC_CREATE: [CHAINID, SENDER, PASSWORD, ALIAS, GASLIMIT, PRICE, CONTRACTCODE, ARGS, REMARK]
SC_CREATE_VALIDATOR: [CHAINID, TX]
SC_DELETE: [CHAINID, SENDER, PASSWORD, CONTRACTADDRESS, REMARK]
SC_DELETE_VALIDATOR: [CHAINID, TX]
SC_IMPUTED_CALL_GAS: [CHAINID, SENDER, VALUE, CONTRACTADDRESS, METHODNAME, METHODDESC, ARGS]
SC_IMPUTED_CREATE_GAS: [CHAINID, SENDER, CONTRACTCODE, ARGS]
SC_INITIAL_ACCOUNT_TOKEN: [CHAINID, ADDRESS]
SC_INVOKE_CONTRACT: [CHAINID, BLOCKTYPE, TX]
SC_INVOKE_VIEW: [CHAINID, CONTRACTADDRESS, METHODNAME, METHODDESC, ARGS]
SC_PACKAGE_BATCH_END: [CHAINID, BLOCKHEIGHT]
SC_REGISTER_CMD_FOR_CONTRACT: [CHAINID, MODULECODE, CMDREGISTERLIST]
SC_TOKEN_ASSETS_LIST: [CHAINID, ADDRESS, PAGENUMBER, PAGESIZE]
SC_TOKEN_BALANCE: [CHAINID, CONTRACTADDRESS, ADDRESS]
SC_TOKEN_TRANSFER: [CHAINID, ADDRESS, TOADDRESS, CONTRACTADDRESS, PASSWORD, AMOUNT, REMARK]
SC_TOKEN_TRANSFER_LIST: [CHAINID, ADDRESS, PAGENUMBER, PAGESIZE]
SC_TRANSFER: [CHAINID, ADDRESS, TOADDRESS, PASSWORD, AMOUNT, REMARK]
SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT: [CHAINID, STATEROOT, BLOCKHEIGHT, CONTRACTADDRESS, TX]
SC_UPLOAD: [CHAINID, JARFILEDATA]
SC_VALIDATE_CALL: [CHAINID, SENDER, VALUE, GASLIMIT, PRICE, CONTRACTADDRESS, METHODNAME, METHODDESC, ARGS]
SC_VALIDATE_CREATE: [CHAINID, SENDER, GASLIMIT, PRICE, CONTRACTCODE, ARGS]
SC_VALIDATE_DELETE: [CHAINID, SENDER, CONTRACTADDRESS]
STOPAGENTVALID: [CHAINID, TX]
TXCOMMIT: [CHAINID, TXLIST, BLOCKHEADER]
TXROLLBACK: [CHAINID, TXLIST, BLOCKHEADER]
TXVALIDATOR: [CHAINID, TXLIST, BLOCKHEADER]
TX_BACKPACKABLETXS: [CHAINID, TXLIST]
TX_BATCHVERIFY: [CHAINID, TXLIST, BLOCKHEADER, PRESTATEROOT]
TX_BL_STATE: [CHAINID, STATUS]
TX_BLOCKHEIGHT: [CHAINID, HEIGHT]
TX_CS_STATE: [CHAINID, PACKAGING]
TX_GENGSISSAVE: [CHAINID, TXLIST, BLOCKHEADER]
TX_GETBLOCKTXS: [CHAINID, TXHASHLIST]
TX_GETBLOCKTXSEXTEND: [CHAINID, TXHASHLIST, ALLHITS]
TX_GETCONFIRMEDTX: [CHAINID, TXHASH]
TX_GETCONFIRMEDTXCLIENT: [CHAINID, TXHASH]
TX_GETNONEXISTENTUNCONFIRMEDHASHS: [CHAINID, TXHASHLIST]
TX_GETSYSTEMTYPES: [CHAINID]
TX_GETTX: [CHAINID, TXHASH]
TX_GETTXCLIENT: [CHAINID, TXHASH]
TX_NEWTX: [CHAINID, TX]
TX_PACKABLETXS: [CHAINID, ENDTIMESTAMP, MAXTXDATASIZE, BLOCKTIME, PACKINGADDRESS, PRESTATEROOT]
TX_REGISTER: [CHAINID, MODULECODE, LIST, DELLIST]
TX_ROLLBACK: [CHAINID, TXHASHLIST, BLOCKHEADER]
TX_SAVE: [CHAINID, TXLIST, CONTRACTLIST, BLOCKHEADER]
TX_VERIFYTX: [CHAINID, TX]
UPDATECHAINASSET: [CHAINID, ASSETS]
VERIFYCOINDATA: [CHAINID, TX]
VERIFYCOINDATABATCHPACKAGED: [CHAINID, TXLIST]
WITHDRAWVALID: [CHAINID, TX]
FORWARDMESSAGE: []
GETCPUINFO: [LMAXCPUS]
GETCONSOLIDATEDAPI: []
GETRAMINFO: []
LISTAPI: []
REGISTERAPI: []
CHECKUPDATES: []
SCANMANAGEDMODULES: []
SHUTDOWNSYSTEM: []
STARTALLMODULES: [FRESTARTIFRUNNING]
STARTMODULE: [LMODULENAME, LMODULEVERSION, FRESTARTIFRUNNING]
STOPALLMODULES: []
STOPMODULE: [LMODULENAME, LMODULEVERSION]

