
# "method name constants representing possible api calls to Nulstar.",
# "Nancy Schorr, December, 2019


AC_ADDRESS_PREFIX = "ac_addAddressPrefix"
AC_CREATE_ACCOUNT = "ac_createAccount"
AC_CREATE_CONTRACT_ACCT = "ac_createContractAccount"
AC_CREATE_MULTISIGN_ACCT = "ac_createMultiSignAccount"
AC_CREATE_MULTISIGN_TRANSFER = "ac_createMultiSignTransfer"
AC_CREATE_OFFLINE_ACCT = "ac_createOfflineAccount"
AC_EXPORTACCOUNTKEYSTORE = "ac_exportAccountKeyStore"
AC_EXPORT_KEYSTORE_JSON = "ac_exportKeyStoreJson"
AC_EXPORT_ACCT_KEYSTORE = "ac_createMultiSignAccount"
AC_GET_ACCOUNT_LIST = "ac_getAccountList"
AC_GET_ADDRESS_LIST = "ac_getAddressList"
AC_GET_ADDRESS_PREFIXBY_CHAINID = "ac_getAddressPrefixByChainId"
AC_GET_ALIASBY_ADDRESS = "ac_getAliasByAddress"
AC_GET_ALL_ADDRESS_PREFIX = "ac_getAllAddressPrefix"
AC_GET_ALL_PRIKEY = "ac_getAllPriKey"
AC_GET_ENCRYPTED_ADDRESS_LIST = "ac_getEncryptedAddressList"
AC_GET_MULTISIGN_ACCT = "ac_getMultiSignAccount"
AC_GET_PRI_KEY = "ac_getPriKeyByAddress"
AC_GET_PUBKEY = "ac_getPubKey"
AC_GET_ACCT_BYADDRESS = "ac_getAccountByAddress"
AC_IMPORTACCOUNTBYPRIKEY = "ac_importAccountByPriKey"
AC_IMPORT_ACCT_BY_KEYSTORE = "ac_importAccountByKeystore"
AC_IS_ALIAS_USABLE = "ac_isAliasUsable"
AC_IS_MULTISIGN_ACCT_BUILDER = "ac_isMultiSignAccountBuilder"
AC_REMOVEACCOUNT = "ac_removeAccount"
AC_REMOVEMULTISIGNACCOUNT = "ac_removeMultiSignAccount"
AC_SETALIAS = "ac_setAlias"
AC_SETMULTISIGNALIAS = "ac_setMultiSignAlias"
AC_SETREMARK = "ac_setRemark"
AC_SIGNBLOCKDIGEST = "ac_signBlockDigest"
AC_SIGNDIGEST = "ac_signDigest"
AC_SIGNMULTISIGNTRANSACTION = "ac_signMultiSignTransaction"
AC_SIGN_DIGEST = "ac_signDigest"
AC_TRANSFER = "ac_transfer"
AC_UPDATEOFFLINEACCOUNTPASSWORD = "ac_updateOfflineAccountPassword"
AC_UPDATEPASSWORD = "ac_updatePassword"
AC_VALIDATIONPASSWORD = "ac_validationPassword"
AC_VERIFY_SIGNDATA = "ac_verifySignData"
ASC_CCOUNT_CONTRACTS = "sc_account_contracts"
BATCH_VALIDATE_BEGIN = "batchValidateBegin"
BLOCKVALIDATE = "blockValidate"
CANCEL_CROSS_CHAIN = "cancelCrossChain"
CHECKBLOCKVERSION = "checkBlockVersion"
CHECKUPDATES = "checkupdates"
CLEAR_UNCONFIRMED_TX  = "clearUnconfirmTxs"
CM_ASSET = "cm_asset"
CM_ASSET_CIRCULATE_COMMIT = "cm_assetCirculateCommit"
CM_ASSET_CIRCULATE_ROLLBACK  = "cm_assetCirculateRollBack"
CM_ASSET_CIRCULATE_VALIDATOR = "cm_assetCirculateValidator"
CM_ASSET_DISABLE = "cm_assetDisable"
CM_ASSET_REG = "cm_assetReg"
CM_CHAIN = "cm_chain"
CM_CHAIN_ACTIVE = "cm_chainActive"
CM_CHAIN_REG = "cm_chainReg"
CM_GET_CHAIN_ASSET = "cm_getChainAsset"
CM_GET_CIRCULATE_CHAIN_ASSET = "cm_getCirculateChainAsset"
CM_GET_CROSS_CHAIN_SIMPLE_INFOS = "cm_getChainsSimpleInfo"
COMMIT_BATCH_UNCONFIRMED_TXS = "commitBatchUnconfirmedTxs"
COMMITBLOCKTXS = "commitBlockTxs"
COMMIT_UNCONFIRMEDTX  = "commitUnconfirmedTx"
CONNECTREADY = "connectReady"
CREATEAGENTVALID = "createAgentValid"
CREATECROSSTX  = "createCrossTx"
CROSS_CHAIN_REGISTER_CHANGE = "crossChainRegisterChange"
CS_ADDBLOCK = "cs_addBlock"
CS_ADD_EVIDENCE_RECORD = "cs_addEvidenceRecord"
CS_CHAIN_ROLLBACK  = "cs_chainRollBack"
CS_CONTRACT_DEPOSIT = "cs_contractDeposit"
CS_CONTRACT_WITHDRAW = "cs_contractWithdraw"
CS_CREATE_AGENT = "cs_createAgent"
CS_CREATE_CONTRACT_AGENT = "cs_createContractAgent"
CS_CREATE_MULTIAGENT = "cs_createMultiAgent"
CS_DEPOSIT_TOAGENT = "cs_depositToAgent"
CS_DOUBLE_SPEND_RECORD = "cs_doubleSpendRecord"
CS_GET_AGENTADDRESSLIST = "cs_getAgentAddressList"
CS_GET_WHOLEINFO = "cs_getWholeInfo"
CS_GET_AGENT_ADDRESS_LIST = "cs_get_AgentAddressList"
CS_GET_AGENT_CHANGE_INFO = "cs_getAgentChangeInfo"
CS_GET_AGENT_INFO = "cs_getAgentInfo"
CS_GET_AGENT_LIST = "cs_getAgentList"
CS_GET_AGENT_STATUS = "cs_getAgentStatus"
CS_GET_CONSENSUS_CONFIG = "cs_getConsensusConfig"
CS_GET_CONTRACT_AGENT_INFO = "cs_getContractAgentInfo"
CS_GET_CONTRACT_DEPOSIT_INFO = "cs_getContractDepositInfo"
CS_GET_DEPOSIT_LIST = "cs_getDepositList"
CS_GET_INFO = "cs_getInfo"
CS_GET_NODE_PACKING_ADDR = "cs_getNodePackingAddress"
CS_GET_PACKER_INFO = "cs_getPackerInfo"
CS_GET_PUBLISH_LIST = "cs_getPublishList"
CS_GET_ROUNDMEMBER_LIST = "cs_getRoundMemberList"
CS_GET_ROUND_INFO = "cs_getRoundInfo"
CS_GET_SEED_NODE_INFO = "cs_getSeedNodeInfo"
CS_GET_WHOLEINFO = "cs_getwholeinfo"
CS_MULTIDEPOSIT = "cs_multiDeposit"
CS_MULTIWITHDRAW = "cs_multiWithdraw"
CS_RANDOM_RAW_SEEDS_COUNT = "cs_random_raw_seeds_count"
CS_RANDOM_RAW_SEEDS_HEIGHT = "cs_random_raw_seeds_height"
CS_RANDOM_SEED_COUNT = "cs_random_seed_count"
CS_RANDOM_SEED_HEIGHT = "cs_random_seed_height"
CS_RECEIVEHEADERLIST = "cs_receiveHeaderList"
CS_RECEIVE_HEADER_LIST = "cs_receiveheaderlist"
CS_RUNCHAIN = "cs_runChain"
CS_RUNMAINCHAIN = "cs_runMainChain"
CS_STOPAGENT = "cs_stopAgent"
CS_STOPCHAIN = "cs_stopChain"
CS_STOPCONTRACTAGENT = "cs_stopContractAgent"
CS_STOPMULTIAGENT = "cs_stopMultiAgent"
CS_STOP_AGENT = "cs_stopagent"
CS_STOP_CHAIN = "cs_stopchain"
CS_STOP_CONTRACTAGENT = "cs_stopcontractagent"
CS_TRIGGER_COINBASE_CONTRACT = "cs_triggerCoinBaseContract"
CS_UPDATE_AGENT_CONSENSUS_STATUS = "cs_updateAgentConsensusStatus"
CS_UPDATE_AGENT_STATUS = "cs_updateAgentStatus"
CS_VALIDBLOCK = "cs_validBlock"
CS_WITHDRAW = "cs_withdraw"
DEPOSIT_VALID = "depositValid"
GET_BALANCE = "getBalance"
GET_BLOCKHEADER_BYHASH = "getBlockHeaderByHash"
GET_BLOCKHEADER_BYHEIGHT = "getBlockHeaderByHeight"
GET_BLOCKHEADER_POBYHASH = "getBlockHeaderPoByHash"
GET_BLOCKHEADER_POBYHEIGHT = "getBlockHeaderPoByHeight"
GET_BLOCKHEADERS_BYHEIGHTRANGE = "getBlockHeadersByHeightRange"
GET_BLOCKHEADERS_FORPROTOCOL  = "getBlockHeadersForProtocol"
GET_CIRCULAT = "getCirculat"
GET_CROSSTX_STATE = "getCrossTxState"
GET_CTX  = "getCtx"
GET_CTX_STATE = "getCtxState"
GET_FREEZELIST = "getFreezeList"
GET_LATESTBLOCKHEADERS  = "getLatestBlockHeaders"
GET_LATEST_ROUND_BLOCKHEADERS  = "getLatestRoundBlockHeaders"
GET_NONCE = "getNonce"
GET_OTHERCTX  = "getOtherCtx"
GET_ROUNDBLOCKHEADERS  = "getRoundBlockHeaders"
GET_STATUS = "getStatus"
GET_VERSION = "getVersion"
GET_BALANCE = "getBalanceNonce"
GET_BLOCK_BY_HASH = "getBlockByHash"
GET_BLOCK_BY_HEIGHT = "getBlockByHeight"
GET_BYZANTINE_COUNT = "getByzantineCount"
GET_CROSS_CHAIN_INFOS = "getCrossChainInfos"
GET_FRIEND_CHAIN_CIRCULATE = "getFriendChainCirculate"
GET_NETWORK_GROUP = "getGroupByChainId"
GET_REGISTERED_CHAIN = "getRegisteredChainInfoList"
GET_REGISTERED_CHAIN_MESSAGE = "getChains"
GET_REGISTERED_CHAIN_INFO_LIST = "getRegisteredChainInfoList"
INFO = "info"
LATESTBLOCK = "latestBlock"
LATESTBLOCKHEADERPO = "latestBlockHeaderPo"
LATESTHEIGHT = "latestHeight"
LATEST_BLOCK_HEADER = "latestBlockHeader"
LG_GET_ASSETS_BY_ID = "getAssetsById"
LG_GET_COINDATA = "getBalanceNonce"
LISTENER_DEPENDENCIES_READY = "listenerDependenciesReady"
MSGPROCESS = "msgProcess"
NEWBLOCKHEIGHT = "newBlockHeight"
NEW_API_MOD_CROSS_TX  = "newApiModuleCrossTx"
NW_ACTIVE_CROSS = "nw_activeCross"
NW_ADD_NODES = "nw_addNodes"
NW_BROADCAST = "nw_broadcast"
NW_CREATE_NODEGROUP = "nw_createNodeGroup"
NW_CROSS_RANDOM_BROADCAST = "nw_crossRandomBroadcast"
NW_CROSS_SEEDS = "nw_getSeeds"
NW_DELETE_NODEGROUP = "nw_delNodeGroup"
NW_DEL_NODES = "nw_delNodes"
NW_GET_CHAIN_CONNECT_AMOUNT = "nw_getChainConnectAmount"
NW_GET_DELETE_NODEGROUP = "nw_delNodeGroup"
NW_GET_GROUPS = "nw_getGroups"
NW_GET_GROUP_BY_CHAINID = "nw_getGroupByChainId"
NW_GET_MAIN_NET_MAGIC_NUMBER = "nw_getMainMagicNumber"
NW_GET_NODES = "nw_getNodes"
NW_GET_SEEDS = "nw_getSeeds"
NW_CUR_TIME_MILLIS = "nw_currentTimeMillis"
NW_INFO = "nw_info"
NW_NODES = "nw_nodes"
NW_PROTOCOL_REGISTER  = "nw_protocolRegister"
NW_RECONNECT = "nw_reconnect"
NW_SEND_PEERS_MSG = "nw_sendPeersMsg"
NW_UPDATE_NODE_INFO = "nw_updateNodeInfo"
PARAMTESTCMD = "paramTestCmd"
PROTOCOL_VERSIONCHANGE = "protocolVersionChange"
PROTOCOL_PRIORITY_REGISTER  = "protocolRegisterWithPriority"
RECEIVE_PACKING_BLOCK = "receivePackingBlock"
RECV_CIRCULAT = "recvCirculat"
RECV_CTX  = "recvCtx"
RECV_CTX_HASH = "recvCtxHash"
RECV_CTX_SIGN = "recvCtxSign"
RECV_CTX_STATE = "recvCtxState"
RECV_OTHERCTX  = "recvOtherCtx"
RECV_REGCHAIN = "recvRegChain"
REGISTER_API = "RegisterAPI"
REGISTER_MODULEDEPENDENCIES = "registerModuleDependencies"
REGISTER_PROTOCOL  = "registerProtocol"
REG_CROSS_ASSET = "registerAsset"
REG_CROSS_CHAIN = "registerCrossChain"
ROLLBACK_BLOCK = "rollbackBlock"
ROLLBACK_BLOCKTXS = "rollBackBlockTxs"
ROLLBACK_TX_VALIDATESTATUS = "rollbackTxValidateStatus"
ROLLBACK_UNCONFIRMTX  = "rollBackUnconfirmTx"
SAVEBLOCK = "saveBlock"
SC_BATCH_BEFORE_END = "sc_batch_before_end"
SC_BATCH_BEGIN = "sc_batch_begin"
SC_BATCH_END = "sc_batch_end"
SC_CALL = "sc_call"
SC_CALL_VALIDATOR = "sc_call_validator"
SC_CONSTRUCTOR = "sc_constructor"
SC_CONTRACT_INFO = "sc_contract_info"
SC_CONTRACT_OFFLINE_TX_HASH_LIST = "sc_contract_offline_tx_hash_list"
SC_CONTRACT_RESULT = "sc_contract_result"
SC_CONTRACT_RESULT_LIST = "sc_contract_result_list"
SC_CONTRACT_TX  = "sc_contract_tx"
SC_CREATE = "sc_create"
SC_CREATE_VALIDATOR = "sc_create_validator"
SC_DELETE = "sc_delete"
SC_DELETE_VALIDATOR = "sc_delete_validator"
SC_IMPUTED_CALL_GAS = "sc_imputed_call_gas"
SC_IMPUTED_CREATE_GAS = "sc_imputed_create_gas"
SC_INITIAL_ACCOUNT_TOKEN = "sc_initial_account_token"
SC_INVOKE_CONTRACT = "sc_invoke_contract"
SC_INVOKE_VIEW = "sc_invoke_view"
SC_PACKAGE_BATCH_END = "sc_package_batch_end"
SC_REGISTER_CM_FOR_CONTRACT = "sc_register_cmd_for_contract"
SC_TOKEN_ASSETS_LIST = "sc_token_assets_list"
SC_TOKEN_BALANCE = "sc_token_balance"
SC_TOKEN_TRANSFER = "sc_token_transfer"
SC_TOKEN_TRANSFER_LIST = "sc_token_transfer_list"
SC_TRANSFER = "sc_transfer"
SC_TRANSFER_FEE = "sc_transfer_fee"
SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT = "sc_trigger_payable_for_consensus_contract"
SC_UPLOAD = "sc_upload"
SC_VALIDATE_CALL = "sc_validate_call"
SC_VALIDATE_CREATE = "sc_validate_create"
SC_VALIDATE_DELETE = "sc_validate_delete"
STOPAGENTVALID = "stopAgentValid"
TX_COMMIT = "txCommit"
TX_ROLLBACK  = "txRollback"
TX_VALIDATOR = "txValidator"
TX_BACKPACKABLETXS = "tx_backPackableTxs"
TX_BASE_VALIDATE = "tx_baseValidateTx"
TX_BATCHVERIFY  = "tx_batchVerify"
TX_BLOCKHEIGHT = "tx_blockHeight"
TX_BL_STATE = "tx_bl_state"
TX_CHAIN_ID = "chainId"
TX_CLEAN_THREAD = "cleanTxThread"
TX_COUNT = "txCount"
TX_CS_STATE = "tx_cs_state"
TX_GENGSISSAVE = "tx_gengsisSave"
TX_GET_BLOCKTXS = "tx_getBlockTxs"
TX_GET_BLOCKTX_SEXTEND = "tx_getBlockTxsExtend"
TX_GET_CONFIRMEDTX  = "tx_getConfirmedTx"
TX_GET_CONFIRMEDTX_CLIENT = "tx_getConfirmedTxClient"
TX_GET_NONEXISTENT_UNCONFIRMED_HASHS = "tx_getNonexistentUnconfirmedHashs"
TX_GET_SYSTEMTYPES = "tx_getSystemTypes"
TX_GET_TX  = "tx_getTx"
TX_GET_TX  = "tx_getTxClient"
TX_HASH = "txHash"
TX_HASH_LIST = "txHashList"
TX_LIST = "txList"
TX_NEW = "tx_newTx"
TX_NEWTX  = "tx_newTx"
TX_NEW_CM = "tx_newTx"
TX_PACKABLETXS = "tx_packableTxs"
TX_REGISTER  = "tx_register"
TX_ROLLBACK  = "tx_rollback"
TX_SAVE = "tx_save"
TX_THREAD = "newNetTxThread"
TX_VERIFY_TX  = "tx_verifyTx"
UPDATE_CHAIN_ASSET = "updateChainAsset"
VERIFY_COINDATA = "verifyCoinData"
VERIFY_COINDATA_BATCH_PACKAGED = "verifyCoinDataBatchPackaged"
WITHDRAWVALID = "withdrawValid"
GET_CONSOLIDATEDAPI  = "GetConsolidatedAPI"
FORWARDMESSAGE ="ForwardMessage"
GET_CROSSCHAIN_INFOS = "getCrossChainInfos"
SCANMANAGEDMODULES  = "scanmanagedmodules"
SHUTDOWNSYSTEM  ="shutdownsystem"
STOPALLMODULES  = "stopallmodules"


# to generate _ALL_ list:     dir(nulsws_CONSTANTS_API_names)
__ALL__ = [AC_ADDRESS_PREFIX, AC_CREATE_ACCOUNT, AC_CREATE_CONTRACT_ACCT, AC_CREATE_MULTISIGN_ACCT,
      AC_CREATE_MULTISIGN_TRANSFER, AC_CREATE_OFFLINE_ACCT, AC_EXPORTACCOUNTKEYSTORE,
      AC_EXPORT_KEYSTORE_JSON, AC_EXPORT_ACCT_KEYSTORE, AC_GET_ACCOUNT_LIST, AC_GET_ADDRESS_LIST,
      AC_GET_ADDRESS_PREFIXBY_CHAINID, AC_GET_ALIASBY_ADDRESS, AC_GET_ALL_ADDRESS_PREFIX,
      AC_GET_ALL_PRIKEY, AC_GET_ENCRYPTED_ADDRESS_LIST, AC_GET_MULTISIGN_ACCT, AC_GET_PRI_KEY,
      AC_GET_PUBKEY, AC_GET_ACCT_BYADDRESS, AC_IMPORTACCOUNTBYPRIKEY, AC_IMPORT_ACCT_BY_KEYSTORE,
      AC_IS_ALIAS_USABLE, AC_IS_MULTISIGN_ACCT_BUILDER, AC_REMOVEACCOUNT,
      AC_REMOVEMULTISIGNACCOUNT, AC_SETALIAS, AC_SETMULTISIGNALIAS, AC_SETREMARK,
      AC_SIGNBLOCKDIGEST, AC_SIGNDIGEST, AC_SIGNMULTISIGNTRANSACTION, AC_SIGN_DIGEST,
      AC_TRANSFER, AC_UPDATEOFFLINEACCOUNTPASSWORD, AC_UPDATEPASSWORD, AC_VALIDATIONPASSWORD,
      AC_VERIFY_SIGNDATA, ASC_CCOUNT_CONTRACTS, BATCH_VALIDATE_BEGIN, BLOCKVALIDATE,
      CANCEL_CROSS_CHAIN, CHECKBLOCKVERSION, CHECKUPDATES, CLEAR_UNCONFIRMED_TX, CM_ASSET,
      CM_ASSET_CIRCULATE_COMMIT, CM_ASSET_CIRCULATE_ROLLBACK, CM_ASSET_CIRCULATE_VALIDATOR,
      CM_ASSET_DISABLE, CM_ASSET_REG, CM_CHAIN, CM_CHAIN_ACTIVE, CM_CHAIN_REG,
      CM_GET_CHAIN_ASSET, CM_GET_CIRCULATE_CHAIN_ASSET, CM_GET_CROSS_CHAIN_SIMPLE_INFOS,
      COMMIT_BATCH_UNCONFIRMED_TXS, COMMITBLOCKTXS, COMMIT_UNCONFIRMEDTX, CONNECTREADY,
      CREATEAGENTVALID, CREATECROSSTX, CROSS_CHAIN_REGISTER_CHANGE, CS_ADDBLOCK,
      CS_ADD_EVIDENCE_RECORD, CS_CHAIN_ROLLBACK, CS_CONTRACT_DEPOSIT, CS_CONTRACT_WITHDRAW,
      CS_CREATE_AGENT, CS_CREATE_CONTRACT_AGENT, CS_CREATE_MULTIAGENT, CS_DEPOSIT_TOAGENT,
      CS_DOUBLE_SPEND_RECORD, CS_GET_AGENTADDRESSLIST, CS_GET_WHOLEINFO, CS_GET_AGENT_ADDRESS_LIST,
      CS_GET_AGENT_CHANGE_INFO, CS_GET_AGENT_INFO, CS_GET_AGENT_LIST, CS_GET_AGENT_STATUS,
      CS_GET_CONSENSUS_CONFIG, CS_GET_CONTRACT_AGENT_INFO, CS_GET_CONTRACT_DEPOSIT_INFO,
      CS_GET_DEPOSIT_LIST, CS_GET_INFO, CS_GET_NODE_PACKING_ADDR, CS_GET_PACKER_INFO,
      CS_GET_PUBLISH_LIST, CS_GET_ROUNDMEMBER_LIST, CS_GET_ROUND_INFO, CS_GET_SEED_NODE_INFO,
      CS_GET_WHOLEINFO, CS_MULTIDEPOSIT, CS_MULTIWITHDRAW, CS_RANDOM_RAW_SEEDS_COUNT,
      CS_RANDOM_RAW_SEEDS_HEIGHT, CS_RANDOM_SEED_COUNT, CS_RANDOM_SEED_HEIGHT,
      CS_RECEIVEHEADERLIST, CS_RECEIVE_HEADER_LIST, CS_RUNCHAIN, CS_RUNMAINCHAIN, CS_STOPAGENT,
      CS_STOPCHAIN, CS_STOPCONTRACTAGENT, CS_STOPMULTIAGENT, CS_STOP_AGENT, CS_STOP_CHAIN,
      CS_STOP_CONTRACTAGENT, CS_TRIGGER_COINBASE_CONTRACT, CS_UPDATE_AGENT_CONSENSUS_STATUS,
      CS_UPDATE_AGENT_STATUS, CS_VALIDBLOCK, CS_WITHDRAW, DEPOSIT_VALID, FORWARDMESSAGE,
      GET_BALANCE, GET_BLOCKHEADER_BYHASH, GET_BLOCKHEADER_BYHEIGHT, GET_BLOCKHEADER_POBYHASH,
      GET_BLOCKHEADER_POBYHEIGHT, GET_BLOCKHEADERS_BYHEIGHTRANGE, GET_BLOCKHEADERS_FORPROTOCOL,
      GET_CIRCULAT, GET_CONSOLIDATEDAPI, GET_CROSSCHAIN_INFOS, GET_CROSSTX_STATE, GET_CTX,
      GET_CTX_STATE, GET_FREEZELIST, GET_LATESTBLOCKHEADERS, GET_LATEST_ROUND_BLOCKHEADERS, GET_NONCE,
      GET_OTHERCTX, GET_ROUNDBLOCKHEADERS, GET_STATUS, GET_VERSION, GET_BALANCE,
      GET_BLOCK_BY_HASH, GET_BLOCK_BY_HEIGHT, GET_BYZANTINE_COUNT, GET_CROSS_CHAIN_INFOS,
      GET_FRIEND_CHAIN_CIRCULATE, GET_NETWORK_GROUP, GET_REGISTERED_CHAIN,
      GET_REGISTERED_CHAIN_INFO_LIST, GET_REGISTERED_CHAIN_MESSAGE, INFO, LATESTBLOCK,
      LATESTBLOCKHEADERPO, LATESTHEIGHT, LATEST_BLOCK_HEADER, LG_GET_ASSETS_BY_ID,
      LG_GET_COINDATA, LISTENER_DEPENDENCIES_READY, MSGPROCESS, NEWBLOCKHEIGHT,
      NEW_API_MOD_CROSS_TX, NW_ACTIVE_CROSS, NW_ADD_NODES, NW_BROADCAST, NW_CREATE_NODEGROUP,
      NW_CROSS_RANDOM_BROADCAST, NW_CROSS_SEEDS, NW_CUR_TIME_MILLIS, NW_DELETE_NODEGROUP,
      NW_DEL_NODES, NW_GET_CHAIN_CONNECT_AMOUNT, NW_GET_DELETE_NODEGROUP, NW_GET_GROUPS,
      NW_GET_GROUP_BY_CHAINID, NW_GET_MAIN_NET_MAGIC_NUMBER, NW_GET_NODES, NW_GET_SEEDS,
      NW_INFO, NW_NODES, NW_PROTOCOL_REGISTER, NW_RECONNECT, NW_SEND_PEERS_MSG,
      NW_UPDATE_NODE_INFO, PARAMTESTCMD, PROTOCOL_VERSIONCHANGE, PROTOCOL_PRIORITY_REGISTER,
      RECEIVE_PACKING_BLOCK, RECV_CIRCULAT, RECV_CTX, RECV_CTX_HASH, RECV_CTX_SIGN, RECV_CTX_STATE,
      RECV_OTHERCTX, RECV_REGCHAIN, REGISTER_API, REGISTER_MODULEDEPENDENCIES, REGISTER_PROTOCOL,
      REG_CROSS_ASSET, REG_CROSS_CHAIN, ROLLBACK_BLOCK, ROLLBACK_BLOCKTXS,
      ROLLBACK_TX_VALIDATESTATUS, ROLLBACK_UNCONFIRMTX, SAVEBLOCK, SCANMANAGEDMODULES,
      SC_BATCH_BEFORE_END, SC_BATCH_BEGIN, SC_BATCH_END, SC_CALL, SC_CALL_VALIDATOR,
      SC_CONSTRUCTOR, SC_CONTRACT_INFO, SC_CONTRACT_OFFLINE_TX_HASH_LIST, SC_CONTRACT_RESULT,
      SC_CONTRACT_RESULT_LIST, SC_CONTRACT_TX, SC_CREATE, SC_CREATE_VALIDATOR, SC_DELETE,
      SC_DELETE_VALIDATOR, SC_IMPUTED_CALL_GAS, SC_IMPUTED_CREATE_GAS, SC_INITIAL_ACCOUNT_TOKEN,
      SC_INVOKE_CONTRACT, SC_INVOKE_VIEW, SC_PACKAGE_BATCH_END, SC_REGISTER_CM_FOR_CONTRACT,
      SC_TOKEN_ASSETS_LIST, SC_TOKEN_BALANCE, SC_TOKEN_TRANSFER, SC_TOKEN_TRANSFER_LIST,
      SC_TRANSFER, SC_TRANSFER_FEE, SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT, SC_UPLOAD,
      SC_VALIDATE_CALL, SC_VALIDATE_CREATE, SC_VALIDATE_DELETE, SHUTDOWNSYSTEM, STOPAGENTVALID,
      STOPALLMODULES, TX_COMMIT, TX_ROLLBACK, TX_VALIDATOR, TX_BACKPACKABLETXS, TX_BASE_VALIDATE,
      TX_BATCHVERIFY, TX_BLOCKHEIGHT, TX_BL_STATE, TX_CHAIN_ID, TX_CLEAN_THREAD, TX_COUNT,
      TX_CS_STATE, TX_GENGSISSAVE, TX_GET_BLOCKTXS, TX_GET_BLOCKTX_SEXTEND, TX_GET_CONFIRMEDTX,
      TX_GET_CONFIRMEDTX_CLIENT, TX_GET_NONEXISTENT_UNCONFIRMED_HASHS, TX_GET_SYSTEMTYPES, TX_GET_TX,
      TX_GET_TX, TX_HASH, TX_HASH_LIST, TX_LIST, TX_NEW, TX_NEWTX, TX_NEW_CM,
      TX_PACKABLETXS, TX_REGISTER, TX_ROLLBACK, TX_SAVE, TX_THREAD, TX_VERIFY_TX,
      UPDATE_CHAIN_ASSET, VERIFY_COINDATA, VERIFY_COINDATA_BATCH_PACKAGED, WITHDRAWVALID]


# to generate the list of constants from the dict:
# q  = '"'
# for k,v in constants_d.items():
#     print(k + ' = ' + q + v + q)
