#!/usr/bin/python3.7

# by Nancy Schorr
# for Nuls, Nulstar,
# December, 2019

# Do not edit this file to run queries - only
# for adding or changing methods

from nulsws_python.src.nulsws_python.labels import Labels
import nulsws_python.src.nulsws_python.user_settings.usersettings as usersettings


class CallsD(object):
    u_obj = usersettings.UserSettings()
    u = u_obj.get_user_set_dict()
    par_d = Labels.labs_params_d

    calls_dict = {
        'AC_ADD_ADDRESS_PREFIX': {"ac_addAddressPrefix": {
            par_d.get("PREFIXLIST"): u.get("z0_ADD_ADDRESS_PREFIX_prefix")}},

        'AC_CREATE_ACCOUNT': {"ac_createAccount": {
            par_d.get("CHAINID"): u.get("z1_AC_CREATE_ACCOUNT_chainId"),
            par_d.get("COUNT"): u.get("z1_AC_CREATE_ACCOUNT_count"),
            par_d.get("PASSWORD"): u.get("z1_AC_CREATE_ACCOUNT_password")}},

        'AC_CREATE_CONTRACT_ACCOUNT': {"ac_createContractAccount": {
            par_d.get("CHAINID"): u.get("z2_AC_CREATE_CONTRACT_ACCOUNT_chainId")}},

        'AC_CREATE_MULTI_SIGN_ACCOUNT': {"ac_createMultiSignAccount": {
            par_d.get("CHAINID"): u.get("z3_AC_CREATE_MULTI_SIGN_ACCOUNT_chainId"),
            par_d.get("PUBKEY"): u.get("z3_AC_CREATE_MULTI_SIGN_ACCOUNT_pubKeys"),
            par_d.get("MINSIGNS"): u.get("z3_AC_CREATE_MULTI_SIGN_ACCOUNT_minSigns")}},

        'AC_CREATE_MULTI_SIGN_TRANSFER': {"ac_createMultiSignTransfer": {
            par_d.get("CHAINID"): u.get("z4_AC_CREATE_MULTI_SIGN_TRANSFER_chainId"),
            par_d.get("INPUTS"): u.get("z4_AC_CREATE_MULTI_SIGN_TRANSFER_inputs"),
            par_d.get("OUTPUTS"): u.get("z4_AC_CREATE_MULTI_SIGN_TRANSFER_outputs"),
            par_d.get("REMARK"): u.get("z4_AC_CREATE_MULTI_SIGN_TRANSFER_remark"),
            par_d.get("INPUTS"): u.get("z4_AC_CREATE_MULTI_SIGN_TRANSFER_signAddress"),
            par_d.get("SIGNPASSWORD"):
                u.get("z4_AC_CREATE_MULTI_SIGN_TRANSFER_signPassword"),
            par_d.get("SIGNPASSWORD"): u.get("z25_AC_SET_MULTISIGN_ALIAS_signPassword")}},

        'AC_GET_PRIKEY_BY_ADDRESS': {"ac_getPriKeyByAddress": {
            par_d.get("CHAINID"): u.get("z1017_AC_GET_PRIKEY_BY_ADDRESS__chainId"),
            par_d.get("ADDRESS"): u.get("z1017_AC_GET_PRIKEY_BY_ADDRESS_address"),
            par_d.get("PASSWORD"): u.get("z1017_AC_GET_PRIKEY_BY_ADDRESS_password")}},

        'AC_CREATE_OFFLINE_ACCOUNT': {"ac_createOfflineAccount": {
            par_d.get("CHAINID"): u.get("z5_AC_CREATE_OFFLINE_ACCOUNT_chainId"),
            par_d.get("COUNT"): u.get("z5_AC_CREATE_OFFLINE_ACCOUNT_count"),
            par_d.get("PASSWORD"): u.get("z5_AC_CREATE_OFFLINE_ACCOUNT_password")}},

        'AC_EXPORT_ACCOUNT_KEYSTORE': {'ac_exportAccountKeyStore': {
            par_d.get("CHAINID"): u.get("z6_AC_EXPORT_ACCOUNT_KEYSTORE_chainId"),
            par_d.get("ADDRESS"): u.get("z6_AC_EXPORT_ACCOUNT_KEYSTORE_address"),
            par_d.get("PASSWORD"): u.get("z6_AC_EXPORT_ACCOUNT_KEYSTORE_password"),
            par_d.get("FILEPATH"): u.get("z6_AC_EXPORT_ACCOUNT_KEYSTORE_filePath")}},

        'AC_EXPORT_KEYSTORE_JSON': {'ac_exportKeyStoreJson': {
            par_d.get("CHAINID"): u.get("z7_AC_EXPORT_KEYSTORE_JSON_chainId"),
            par_d.get("ADDRESS"): u.get("z7_AC_EXPORT_KEYSTORE_JSON_address"),
            par_d.get("PASSWORD"): u.get("z7_AC_EXPORT_KEYSTORE_JSON_password")}},

        'AC_GET_ACCOUNT_BYADDRESS': {'ac_getAccountByAddress': {
            par_d.get("CHAINID"): u.get("z8_AC_GET_ACCOUNT_BYADDRESS_chainId"),
            par_d.get("ADDRESS"): u.get("z8_AC_GET_ACCOUNT_BYADDRESS_address")}},

        'AC_GET_ACCOUNT_LIST': {'ac_getAccountList': {
            par_d.get("CHAINID"): u.get("z9_AC_GET_ACCOUNT_LIST_chainId")}},

        'AC_GET_ADDRESS_LIST': {'ac_getAddressList': {
            par_d.get("CHAINID"): u.get("z10_AC_GET_ADDRESS_LIST_chainId"),
            par_d.get("PAGENUMBER"): u.get("z10_AC_GET_ADDRESS_LIST_pageNumber"),
            par_d.get("PAGESIZE"): u.get("z10_AC_GET_ADDRESS_LIST_pageSize")}},

        'AC_GET_ADDRESS_PREFIX_BY_CHAINID': {'ac_getAddressPrefixByChainId': {
            par_d.get("CHAINID"): u.get("z11_AC_GET_ADDRESS_PREFIX_BY_CHAINID_chainId")}},

        'AC_GET_ALIASBY_ADDRESS': {'ac_getAliasByAddress': {
            par_d.get("CHAINID"): u.get("z12_AC_GET_ALIASBY_ADDRESS_chainId"),
            par_d.get("ADDRESS"): u.get("z12_AC_GET_ALIASBY_ADDRESS_address")}},

        'AC_GET_ALL_ADDRESS_PREFIX': {'ac_getAllAddressPrefix': {
            par_d.get("CHAINID"): u.get("z13_AC_GET_ALL_ADDRESS_PREFIX_chainId")}},

        'AC_GET_ALL_PRIKEY': {'ac_getAllPriKey': {
            par_d.get("CHAINID"): u.get("z14_AC_GET_ALL_PRIKEY_chainId"),
            par_d.get("PASSWORD"): u.get("z14_AC_GET_ALL_PRIKEY_password")}},

        'AC_GET_ENCRYPTED_ADDRESS_LIST': {'ac_getEncryptedAddressList': {
            par_d.get("CHAINID"): u.get("z15_AC_GET_ENCRYPTED_ADDRESS_LIST_chainId")}},

        'AC_GET_MULTI_SIGN_ACCOUNT': {'ac_getMultiSignAccount': {
            par_d.get("CHAINID"): u.get("z16_AC_GET_MULTI_SIGN_ACCOUNT_chainId"),
            par_d.get("ADDRESS"): u.get("z16_AC_GET_MULTI_SIGN_ACCOUNT_address")}},

        'AC_GET_PUBKEY': {'ac_getPubKey': {
            par_d.get("CHAINID"): u.get("z17_AC_GET_PUBKEY_chainId"),
            par_d.get("ADDRESS"): u.get("z17_AC_GET_PUBKEY_address"),
            par_d.get("PASSWORD"): u.get("z17_AC_GET_PUBKEY_password")}},

        'AC_IMPORT_ACCOUNT_BY_KEYSTORE': {'ac_importAccountByKeystore': {
            par_d.get("CHAINID"): u.get("z18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_chainId"),
            par_d.get("PASSWORD"): u.get("z18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_password"),
            par_d.get("KEYSTORE"): u.get("z18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_keyStore"),
            par_d.get("OVERWRITE"):
                u.get("z18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_overwrite")}},

        'AC_IMPORT_ACCOUNT_BY_PRIKEY': {'ac_importAccountByPriKey': {
            par_d.get("CHAINID"): u.get("z19_AC_IMPORT_ACCOUNT_BY_PRIKEY_chainId"),
            par_d.get("PASSWORD"): u.get("z19_AC_IMPORT_ACCOUNT_BY_PRIKEY_password"),
            par_d.get("PRIKEY"): u.get("z19_AC_IMPORT_ACCOUNT_BY_PRIKEY_priKey"),
            par_d.get("OVERWRITE"): u.get("z19_AC_IMPORT_ACCOUNT_BY_PRIKEY_overwrite")}},

        'AC_IS_ALIAS_USABLE': {'ac_isAliasUsable': {
            par_d.get("CHAINID"): u.get("z20_AC_IS_ALIAS_USABLE_chainId"),
            par_d.get("ALIAS"): u.get("z20_AC_IS_ALIAS_USABLE_alias")}},

        'AC_IS_MULTISIGN_ACCOUNT_BUILDER': {'ac_isMultiSignAccountBuilder': {
            par_d.get("CHAINID"): u.get("z21_AC_IS_MULTISIGN_ACCOUNT_BUILDER_chainId"),
            par_d.get("ADDRESS"): u.get("z21_AC_IS_MULTISIGN_ACCOUNT_BUILDER_address"),
            par_d.get("PUBKEY"): u.get("z21_AC_IS_MULTISIGN_ACCOUNT_BUILDER_pubKey")}},

        'AC_REMOVE_ACCOUNT': {'ac_removeAccount': {
            par_d.get("CHAINID"): u.get("z22_AC_REMOVE_ACCOUNT_chainId"),
            par_d.get("ADDRESS"): u.get("z22_AC_REMOVE_ACCOUNT_address"),
            par_d.get("PASSWORD"): u.get("z22_AC_REMOVE_ACCOUNT_password")}},

        'AC_REMOVE_MULTISIGN_ACCOUNT': {'ac_removeMultiSignAccount': {
            par_d.get("CHAINID"): u.get("z23_AC_REMOVE_MULTISIGN_ACCOUNT_chainId"),
            par_d.get("ADDRESS"): u.get("z23_AC_REMOVE_MULTISIGN_ACCOUNT_address")}},

        'AC_SET_ALIAS': {'ac_setAlias': {
            par_d.get("CHAINID"): u.get("z24_AC_SET_ALIAS_chainId"),
            par_d.get("ADDRESS"): u.get("z24_AC_SET_ALIAS_address"),
            par_d.get("PASSWORD"): u.get("z24_AC_SET_ALIAS_password"),
            par_d.get("ALIAS"): u.get("z24_AC_SET_ALIAS_alias")}},

        'AC_SET_MULTISIGN_ALIAS': {'ac_setMultiSignAlias': {
            par_d.get("CHAINID"): u.get("z25_AC_SET_MULTISIGN_ALIAS_chainId"),
            par_d.get("ADDRESS"): u.get("z25_AC_SET_MULTISIGN_ALIAS_address"),
            par_d.get("ALIAS"): u.get("z25_AC_SET_MULTISIGN_ALIAS_alias"),
            par_d.get("SIGNADDRESS"): u.get("z25_AC_SET_MULTISIGN_ALIAS_signAddress"),
            par_d.get("SIGNPASSWORD"): u.get("z25_AC_SET_MULTISIGN_ALIAS_signPassword")}},

        'AC_SET_REMARK': {'ac_setRemark': {
            par_d.get("CHAINID"): u.get("z26_AC_SET_REMARK_chainId"),
            par_d.get("ADDRESS"): u.get("z26_AC_SET_REMARK_address"),
            par_d.get("REMARK"): u.get("z26_AC_SET_REMARK_remark")}},

        'AC_SIGN_BLOCKDIGEST': {'ac_signBlockDigest': {
            par_d.get("CHAINID"): u.get("z27_AC_SIGN_BLOCKDIGEST_chainId"),
            par_d.get("ADDRESS"): u.get("z27_AC_SIGN_BLOCKDIGEST_address"),
            par_d.get("PASSWORD"): u.get("z27_AC_SIGN_BLOCKDIGEST_password"),
            par_d.get("DATA"): u.get("z27_AC_SIGN_BLOCKDIGEST_data")}},

        'AC_SIGN_DIGEST': {'ac_signDigest': {
            par_d.get("CHAINID"): u.get("z28_AC_SIGN_DIGEST_chainId"),
            par_d.get("ADDRESS"): u.get("z28_AC_SIGN_DIGEST_address"),
            par_d.get("PASSWORD"): u.get("z28_AC_SIGN_DIGEST_password"),
            par_d.get("DATA"): u.get("z28_AC_SIGN_DIGEST_data")}},

        'AC_SIGN_MULTISIGN_TRANSACTION': {'ac_signMultiSignTransaction': {
            par_d.get("CHAINID"): u.get("z29_AC_SIGN_MULTISIGN_TRANSACTION_chainId"),
            par_d.get("TX"): u.get("z29_AC_SIGN_MULTISIGN_TRANSACTION_tx"),
            par_d.get("SIGNADDRESS"):
                u.get("z29_AC_SIGN_MULTISIGN_TRANSACTION_signAddress"),
            par_d.get("SIGNPASSWORD"):
                u.get("z29_AC_SIGN_MULTISIGN_TRANSACTION_signPassword")}},

        'AC_TRANSFER': {'ac_transfer': {
            par_d.get("CHAINID"): u.get("z30_AC_TRANSFER_chainId"),
            par_d.get("INPUTS"): u.get("z30_AC_TRANSFER_inputs"),
            par_d.get("OUTPUTS"): u.get("z30_AC_TRANSFER_outputs"),
            par_d.get("REMARK"): u.get("z30_AC_TRANSFER_remark")}},

        'AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD': {'ac_updateOfflineAccountPassword': {
            par_d.get("CHAINID"): u.get("z31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_chainId"),
            par_d.get("ADDRESS"): u.get("z31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_address"),
            par_d.get("PASSWORD"):
                u.get("z31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_password"),
            par_d.get("NEWPASSWORD"): u.get(
                "z31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_newPassword"),
            par_d.get("PRIKEY"): u.get("z31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_priKey")}},

        'AC_UPDATE_PASSWORD': {'ac_updatePassword': {
            par_d.get("CHAINID"): u.get("z32_AC_UPDATE_PASSWORD_chainId"),
            par_d.get("ADDRESS"): u.get("z32_AC_UPDATE_PASSWORD_address"),
            par_d.get("PASSWORD"): u.get("z32_AC_UPDATE_PASSWORD_password"),
            par_d.get("NEWPASSWORD"): u.get("z32_AC_UPDATE_PASSWORD_newPassword")}},

        'AC_VALIDATION_PASSWORD': {'ac_validationPassword': {
            par_d.get("CHAINID"): u.get("z33_AC_VALIDATION_PASSWORD_chainId"),
            par_d.get("ADDRESS"): u.get("z33_AC_VALIDATION_PASSWORD_address"),
            par_d.get("PASSWORD"): u.get("z33_AC_VALIDATION_PASSWORD_password")}},

        'AC_VERIFY_SIGN_DATA': {'ac_verifySignData': {
            par_d.get("PUBKEY"): u.get("z34_AC_VERIFY_SIGN_DATA_pubKey"),
            par_d.get("SIG"): u.get("z34_AC_VERIFY_SIGN_DATA_sig"),
            par_d.get("DATA"): u.get("z34_AC_VERIFY_SIGN_DATA_data")}},

        'BATCH_VALIDATE_BEGIN': {'batchValidateBegin': {
            par_d.get("CHAINID"): u.get("z35_BATCH_VALIDATE_BEGIN_chainId")}},

        'BLOCK_VALIDATE': {'blockValidate': {
            par_d.get("CHAINID"): u.get("z36_BLOCK_VALIDATE_chainId"),
            par_d.get("TXLIST"): u.get("z36_BLOCK_VALIDATE_txList")}},

        'CANCEL_CROSSCHAIN': {'cancelCrossChain': {
            par_d.get("CHAINID"): u.get("z38_CANCEL_CROSSCHAIN_chainId"),
            par_d.get("ASSETID"): u.get("z38_CANCEL_CROSSCHAIN_assetId")}},

        'CHECK_BLOCK_VERSION': {'checkBlockVersion': {
            par_d.get("CHAINID"): u.get("z39_CHECK_BLOCK_VERSION_chainId"),
            par_d.get("EXTENDSDATA"): u.get("z39_CHECK_BLOCK_VERSION_extendsData")}},

        'CM_ASSET': {'cm_asset': {
            par_d.get("CHAINID"): u.get("z40_CM_ASSET_chainId"),
            par_d.get("ASSETID"): u.get("z40_CM_ASSET_assetId")}},

        'CM_ASSET_CIRCULATE_COMMIT': {'cm_assetCirculateCommit': {
            par_d.get("CHAINID"): u.get("z41_CM_ASSET_CIRCULATE_COMMIT_chainId"),
            par_d.get("TXLIST"): u.get("z41_CM_ASSET_CIRCULATE_COMMIT_txList"),
            par_d.get("BLOCKHEADER"): u.get(
                "z41_CM_ASSET_CIRCULATE_COMMIT_blockHeader")}},

        'CM_ASSET_CIRCULATE_ROLLBACK': {'cm_assetCirculateRollBack': {
            par_d.get("CHAINID"): u.get("z42_CM_ASSET_CIRCULATE_ROLLBACK_chainId"),
            par_d.get("TXLIST"): u.get("z42_CM_ASSET_CIRCULATE_ROLLBACK_txList"),
            par_d.get("BLOCKHEADER"): u.get(
                "z42_CM_ASSET_CIRCULATE_ROLLBACK_blockHeader")}},

        'CM_ASSET_CIRCULATE_VALIDATOR': {'cm_assetCirculateValidator': {
            par_d.get("CHAINID"): u.get("z43_CM_ASSET_CIRCULATE_VALIDATOR_chainId"),
            par_d.get("TX"): u.get("z43_CM_ASSET_CIRCULATE_VALIDATOR_tx")}},

        'CM_ASSET_DISABLE': {'cm_assetDisable': {
            par_d.get("CHAINID"): u.get("z44_CM_ASSET_DISABLE_chainId"),
            par_d.get("ASSETID"): u.get("z44_CM_ASSET_DISABLE_assetId"),
            par_d.get("ADDRESS"): u.get("z44_CM_ASSET_DISABLE_address"),
            par_d.get("PASSWORD"): u.get("z44_CM_ASSET_DISABLE_password")}},

        'CM_ASSET_REG': {'cm_assetReg': {
            par_d.get("CHAINID"): u.get("z45_CM_ASSET_REG_chainId"),
            par_d.get("ASSETID"): u.get("z45_CM_ASSET_REG_assetId"),
            par_d.get("SYMBOL"): u.get("z45_CM_ASSET_REG_symbol"),
            par_d.get("ASSETNAME"): u.get("z45_CM_ASSET_REG_assetName"),
            par_d.get("INITNUMBER"): u.get("z45_CM_ASSET_REG_initNumber"),
            par_d.get("DECIMALPLACES"): u.get("z45_CM_ASSET_REG_decimalPlaces"),
            par_d.get("ADDRESS"): u.get("z45_CM_ASSET_REG_address"),
            par_d.get("PASSWORD"): u.get("z45_CM_ASSET_REG_password")}},

        'CM_CHAIN': {'cm_chain': {
            par_d.get("CHAINID"): u.get("z46_CM_CHAIN_chainId")}},

        'CM_CHAIN_ACTIVE': {'cm_chainActive': {
            par_d.get("CHAINID"): u.get("z47_CM_CHAIN_ACTIVE_chainId"),
            par_d.get("CHAINNAME"): u.get("z47_CM_CHAIN_ACTIVE_chainName"),
            par_d.get("ADDRESSTYPE"): u.get("z47_CM_CHAIN_ACTIVE_addressType"),
            par_d.get("ADDRESSPREFIX"): u.get("z47_CM_CHAIN_ACTIVE_addressPrefix"),
            par_d.get("MAGICNUMBER"): u.get("z47_CM_CHAIN_ACTIVE_magicNumber"),
            par_d.get("MINAVAILABLENODENUM"): u.get(
                "z47_CM_CHAIN_ACTIVE_minAvailableNodeNum"),
            par_d.get("ASSETID"): u.get("z47_CM_CHAIN_ACTIVE_assetId"),
            par_d.get("SYMBOL"): u.get("z47_CM_CHAIN_ACTIVE_symbol"),
            par_d.get("ASSETNAME"): u.get("z47_CM_CHAIN_ACTIVE_assetName"),
            par_d.get("INITNUMBER"): u.get("z47_CM_CHAIN_ACTIVE_initNumber"),
            par_d.get("DECIMALPLACES"): u.get("z47_CM_CHAIN_ACTIVE_decimalPlaces"),
            par_d.get("ADDRESS"): u.get("z47_CM_CHAIN_ACTIVE_address"),
            par_d.get("PASSWORD"): u.get("z47_CM_CHAIN_ACTIVE_password"),
            par_d.get("VERIFIERLIST"): u.get("z47_CM_CHAIN_ACTIVE_verifierList"),
            par_d.get("SIGNATUREBFTRATIO"): u.get(
                "z47_CM_CHAIN_ACTIVE_signatureBFTRatio"),
            par_d.get("MAXSIGNATURECOUNT"): u.get(
                "z47_CM_CHAIN_ACTIVE_maxSignatureCount")}},

        'CM_CHAIN_REG': {'cm_chainReg': {
            par_d.get("CHAINID"): u.get("z48_CM_CHAIN_REG_chainId"),
            par_d.get("CHAINNAME"): u.get("z48_CM_CHAIN_REG_chainName"),
            par_d.get("ADDRESSTYPE"): u.get("z48_CM_CHAIN_REG_addressType"),
            par_d.get("ADDRESSPREFIX"): u.get("z48_CM_CHAIN_REG_addressPrefix"),
            par_d.get("MAGICNUMBER"): u.get("z48_CM_CHAIN_REG_magicNumber"),
            par_d.get("MINAVAILABLENODENUM"): u.get(
                "z48_CM_CHAIN_REG_minAvailableNodeNum"),
            par_d.get("ASSETID"): u.get("z48_CM_CHAIN_REG_assetId"),
            par_d.get("SYMBOL"): u.get("z48_CM_CHAIN_REG_symbol"),
            par_d.get("ASSETNAME"): u.get("z48_CM_CHAIN_REG_assetName"),
            par_d.get("INITNUMBER"): u.get("z48_CM_CHAIN_REG_initNumber"),
            par_d.get("DECIMALPLACES"): u.get("z48_CM_CHAIN_REG_decimalPlaces"),
            par_d.get("ADDRESS"): u.get("z48_CM_CHAIN_REG_address"),
            par_d.get("PASSWORD"): u.get("z48_CM_CHAIN_REG_password"),
            par_d.get("VERIFIERLIST"): u.get("z48_CM_CHAIN_REG_verifierList"),
            par_d.get("SIGNATUREBFTRATIO"): u.get("z48_CM_CHAIN_REG_signatureBFTRatio"),
            par_d.get("MAXSIGNATURECOUNT"): u.get("z48_CM_CHAIN_REG_maxSignatureCount")}},

        'CM_GET_CHAIN_ASSET': {'cm_getChainAsset': {
            par_d.get("CHAINID"): u.get("z49_CM_GET_CHAIN_ASSET_chainId"),
            par_d.get("ASSETCHAINID"): u.get("z49_CM_GET_CHAIN_ASSET_assetChainId"),
            par_d.get("ASSETID"): u.get("z49_CM_GET_CHAIN_ASSET_assetId")}},

        'CM_GET_CIRCULATE_CHAIN_ASSET': {'cm_getCirculateChainAsset': {
            par_d.get("CIRCULATECHAINID"): u.get(
                "z50_CM_GET_CIRCULATE_CHAIN_ASSET_circulateChainId"),
            par_d.get("ASSETCHAINID"): u.get(
                "z50_CM_GET_CIRCULATE_CHAIN_ASSET_assetChainId"),
            par_d.get("ASSETID"): u.get("z50_CM_GET_CIRCULATE_CHAIN_ASSET_assetId")}},

        'COMMIT_BATCH_UNCONFIRMED_TXS': {'commitBatchUnconfirmedTxs': {
            par_d.get("CHAINID"): u.get("z51_COMMIT_BATCH_UNCONFIRMED_TXS_chainId"),
            par_d.get("TXLIST"): u.get("z51_COMMIT_BATCH_UNCONFIRMED_TXS_txList")}},

        'COMMIT_BLOCKTXS': {'commitBlockTxs': {
            par_d.get("CHAINID"): u.get("z52_COMMIT_BLOCKTXS_chainId"),
            par_d.get("TXLIST"): u.get("z52_COMMIT_BLOCKTXS_txList"),
            par_d.get("BLOCKHEIGHT"): u.get("z52_COMMIT_BLOCKTXS_blockHeight")}},

        'COMMIT_UNCONFIRMEDTX': {'commitUnconfirmedTx': {
            par_d.get("CHAINID"): u.get("z53_COMMIT_UNCONFIRMEDTX_chainId"),
            par_d.get("TX"): u.get("z53_COMMIT_UNCONFIRMEDTX_tx")}},

        'CREATE_AGENT_VALID': {'createAgentValid': {
            par_d.get("CHAINID"): u.get("z55_CREATE_AGENT_VALID_chainId"),
            par_d.get("TX"): u.get("z55_CREATE_AGENT_VALID_tx")}},

        'CREATE_CROSSTX': {'createCrossTx': {
            par_d.get("CHAINID"): u.get("z56_CREATE_CROSSTX_chainId"),
            par_d.get("LISTFROM"): u.get("z56_CREATE_CROSSTX_listFrom"),
            par_d.get("LISTTO"): u.get("z56_CREATE_CROSSTX_listTo"),
            par_d.get("REMARK"): u.get("z56_CREATE_CROSSTX_remark")}},

        'CROSSCHAIN_REGISTER_CHANGE': {'crossChainRegisterChange': {
            par_d.get("CHAINID"): u.get("z57_CROSSCHAIN_REGISTER_CHANGE_chainId")}},

        'CS_ADD_BLOCK': {'cs_addBlock': {
            par_d.get("CHAINID"): u.get("z58_CS_ADD_BLOCK_chainId"),
            par_d.get("BLOCKHEADER"): u.get("z58_CS_ADD_BLOCK_blockHeader")}},

        'CS_ADD_EVIDENCE_RECORD': {'cs_addEvidenceRecord': {
            par_d.get("CHAINID"): u.get("z59_CS_ADD_EVIDENCE_RECORD_chainId"),
            par_d.get("BLOCKHEADER"): u.get("z59_CS_ADD_EVIDENCE_RECORD_blockHeader"),
            par_d.get("EVIDENCEHEADER"): u.get(
                "z59_CS_ADD_EVIDENCE_RECORD_evidenceHeader")}},

        'CS_CHAIN_ROLLBACK': {'cs_chainRollBack': {
            par_d.get("CHAINID"): u.get("z60_CS_CHAIN_ROLLBACK_chainId"),
            par_d.get("HEIGHT"): u.get("z60_CS_CHAIN_ROLLBACK_height")}},

        'CS_CONTRACT_DEPOSIT': {'cs_contractDeposit': {
            par_d.get("CHAINID"): u.get("z61_CS_CONTRACT_DEPOSIT_chainId"),
            par_d.get("AGENTHASH"): u.get("z61_CS_CONTRACT_DEPOSIT_agentHash"),
            par_d.get("DEPOSIT"): u.get("z61_CS_CONTRACT_DEPOSIT_deposit"),
            par_d.get("CONTRACTADDRESS"): u.get(
                "z61_CS_CONTRACT_DEPOSIT_contractAddress"),
            par_d.get("CONTRACTSENDER"): u.get("z61_CS_CONTRACT_DEPOSIT_contractSender"),
            par_d.get("CONTRACTBALANCE"): u.get(
                "z61_CS_CONTRACT_DEPOSIT_contractBalance"),
            par_d.get("CONTRACTNONCE"): u.get("z61_CS_CONTRACT_DEPOSIT_contractNonce"),
            par_d.get("BLOCKTIME"): u.get("z61_CS_CONTRACT_DEPOSIT_blockTime")}},

        'CS_CONTRACT_WITHDRAW': {'cs_contractWithdraw': {
            par_d.get("CHAINID"): u.get("z62_CS_CONTRACT_WITHDRAW_chainId"),
            par_d.get("JOINAGENTHASH"): u.get("z62_CS_CONTRACT_WITHDRAW_joinAgentHash"),
            par_d.get("CONTRACTADDRESS"): u.get(
                "z62_CS_CONTRACT_WITHDRAW_contractAddress"),
            par_d.get("CONTRACTSENDER"): u.get("z62_CS_CONTRACT_WITHDRAW_contractSender"),
            par_d.get("CONTRACTBALANCE"): u.get(
                "z62_CS_CONTRACT_WITHDRAW_contractBalance"),
            par_d.get("CONTRACTNONCE"): u.get("z62_CS_CONTRACT_WITHDRAW_contractNonce"),
            par_d.get("BLOCKTIME"): u.get("z62_CS_CONTRACT_WITHDRAW_blockTime")}},

        'CS_CREATE_AGENT': {'cs_createAgent': {
            par_d.get("CHAINID"): u.get("z63_CS_CREATE_AGENT_chainId"),
            par_d.get("AGENTADDRESS"): u.get("z63_CS_CREATE_AGENT_agentAddress"),
            par_d.get("PACKINGADDRESS"): u.get("z63_CS_CREATE_AGENT_packingAddress"),
            par_d.get("REWARDADDRESS"): u.get("z63_CS_CREATE_AGENT_rewardAddress"),
            par_d.get("COMMISSIONRATE"): u.get("z63_CS_CREATE_AGENT_commissionRate"),
            par_d.get("DEPOSIT"): u.get("z63_CS_CREATE_AGENT_deposit"),
            par_d.get("PASSWORD"): u.get("z63_CS_CREATE_AGENT_password")}},

        'CS_CREATE_CONTRACT_AGENT': {'cs_createContractAgent': {
            par_d.get("CHAINID"): u.get("z64_CS_CREATE_CONTRACT_AGENT_chainId"),
            par_d.get("PACKINGADDRESS"): u.get(
                "z64_CS_CREATE_CONTRACT_AGENT_packingAddress"),
            par_d.get("DEPOSIT"): u.get("z64_CS_CREATE_CONTRACT_AGENT_deposit"),
            par_d.get("COMMISSIONRATE"): u.get(
                "z64_CS_CREATE_CONTRACT_AGENT_commissionRate"),
            par_d.get("CONTRACTADDRESS"): u.get(
                "z64_CS_CREATE_CONTRACT_AGENT_contractAddress"),
            par_d.get("CONTRACTSENDER"): u.get(
                "z64_CS_CREATE_CONTRACT_AGENT_contractSender"),
            par_d.get("CONTRACTBALANCE"): u.get(
                "z64_CS_CREATE_CONTRACT_AGENT_contractBalance"),
            par_d.get("CONTRACTNONCE"): u.get(
                "z64_CS_CREATE_CONTRACT_AGENT_contractNonce"),
            par_d.get("BLOCKTIME"): u.get("z64_CS_CREATE_CONTRACT_AGENT_blockTime")}},

        'CS_CREATE_MULTI_AGENT': {'cs_createMultiAgent': {
            par_d.get("CHAINID"): u.get("z65_CS_CREATE_MULTI_AGENT_chainId"),
            par_d.get("AGENTADDRESS"): u.get("z65_CS_CREATE_MULTI_AGENT_agentAddress"),
            par_d.get("PACKINGADDRESS"): u.get(
                "z65_CS_CREATE_MULTI_AGENT_packingAddress"),
            par_d.get("REWARDADDRESS"): u.get("z65_CS_CREATE_MULTI_AGENT_rewardAddress"),
            par_d.get("COMMISSIONRATE"): u.get(
                "z65_CS_CREATE_MULTI_AGENT_commissionRate"),
            par_d.get("DEPOSIT"): u.get("z65_CS_CREATE_MULTI_AGENT_deposit"),
            par_d.get("PASSWORD"): u.get("z65_CS_CREATE_MULTI_AGENT_password"),
            par_d.get("SIGNADDRESS"): u.get("z65_CS_CREATE_MULTI_AGENT_signAddress")}},

        'CS_DEPOSIT_TOAGENT': {'cs_depositToAgent': {
            par_d.get("CHAINID"): u.get("z66_CS_DEPOSIT_TOAGENT_chainId"),
            par_d.get("ADDRESS"): u.get("z66_CS_DEPOSIT_TOAGENT_address"),
            par_d.get("AGENTHASH"): u.get("z66_CS_DEPOSIT_TOAGENT_agentHash"),
            par_d.get("DEPOSIT"): u.get("z66_CS_DEPOSIT_TOAGENT_deposit"),
            par_d.get("PASSWORD"): u.get("z66_CS_DEPOSIT_TOAGENT_password")}},

        'CS_DOUBLE_SPEND_RECORD': {'cs_doubleSpendRecord': {
            par_d.get("CHAINID"): u.get("z67_CS_DOUBLE_SPEND_RECORD_chainId"),
            par_d.get("BLOCK"): u.get("z67_CS_DOUBLE_SPEND_RECORD_block"),
            par_d.get("TX"): u.get("z67_CS_DOUBLE_SPEND_RECORD_tx")}},

        'CS_GET_AGENT_ADDRESS_LIST': {'cs_get_AgentAddressList': {
            par_d.get("CHAINID"): u.get("z68_CS_GET_AGENT_ADDRESS_LIST_chainId")}},

        'CS_GET_AGENT_CHANGE_INFO': {'cs_getAgentChangeInfo': {
            par_d.get("CHAINID"): u.get("z69_CS_GET_AGENT_CHANGE_INFO_chainId")}},

        'CS_GET_AGENT_INFO': {'cs_getAgentInfo': {
            par_d.get("CHAINID"): u.get("z70_CS_GET_AGENT_INFO_chainId"),
            par_d.get("AGENTHASH"): u.get("z70_CS_GET_AGENT_INFO_agentHash")}},

        'CS_GET_AGENT_LIST': {'cs_getAgentList': {
            par_d.get("CHAINID"): u.get("z71_CS_GET_AGENT_LIST_chainId"),
            par_d.get("PAGENUMBER"): u.get("z71_CS_GET_AGENT_LIST_pageNumber"),
            par_d.get("PAGESIZE"): u.get("z71_CS_GET_AGENT_LIST_pageSize"),
            par_d.get("KEYWORD"): u.get("z71_CS_GET_AGENT_LIST_keyWord")}},

        'CS_GET_AGENT_STATUS': {'cs_getAgentStatus': {
            par_d.get("CHAINID"): u.get("z72_CS_GET_AGENT_STATUS_chainId"),
            par_d.get("AGENTHASH"): u.get("z72_CS_GET_AGENT_STATUS_agentHash")}},

        'CS_GET_CONSENSUS_CONFIG': {'cs_getConsensusConfig': {
            par_d.get("CHAINID"): u.get("z73_CS_GET_CONSENSUS_CONFIG_chainId")}},

        'CS_GET_CONTRACT_AGENT_INFO': {'cs_getContractAgentInfo': {
            par_d.get("CHAINID"): u.get("z74_CS_GET_CONTRACT_AGENT_INFO_chainId"),
            par_d.get("AGENTHASH"): u.get("z74_CS_GET_CONTRACT_AGENT_INFO_agentHash"),
            par_d.get("CONTRACTADDRESS"): u.get(
                "z74_CS_GET_CONTRACT_AGENT_INFO_contractAddress"),
            par_d.get("CONTRACTSENDER"): u.get(
                "z74_CS_GET_CONTRACT_AGENT_INFO_contractSender")}},

        'CS_GET_CONTRACT_DEPOSIT_INFO': {'cs_getContractDepositInfo': {
            par_d.get("CHAINID"): u.get("z75_CS_GET_CONTRACT_DEPOSIT_INFO_chainId"),
            par_d.get("JOINAGENTHASH"): u.get(
                "z75_CS_GET_CONTRACT_DEPOSIT_INFO_joinAgentHash"),
            par_d.get("CONTRACTADDRESS"): u.get(
                "z75_CS_GET_CONTRACT_DEPOSIT_INFO_contractAddress"),
            par_d.get("CONTRACTSENDER"): u.get(
                "z75_CS_GET_CONTRACT_DEPOSIT_INFO_contractSender")}},

        'CS_GET_DEPOSIT_LIST': {'cs_getDepositList': {
            par_d.get("CHAINID"): u.get("z76_CS_GET_DEPOSIT_LIST_chainId"),
            par_d.get("PAGENUMBER"): u.get("z76_CS_GET_DEPOSIT_LIST_pageNumber"),
            par_d.get("PAGESIZE"): u.get("z76_CS_GET_DEPOSIT_LIST_pageSize"),
            par_d.get("ADDRESS"): u.get("z76_CS_GET_DEPOSIT_LIST_address"),
            par_d.get("AGENTHASH"): u.get("z76_CS_GET_DEPOSIT_LIST_agentHash")}},

        'CS_GET_INFO': {'cs_getInfo': {
            par_d.get("CHAINID"): u.get("z77_CS_GET_INFO_chainId"),
            par_d.get("ADDRESS"): u.get("z77_CS_GET_INFO_address")}},

        'CS_GET_PACKER_INFO': {'cs_getPackerInfo': {
            par_d.get("CHAINID"): u.get("z78_CS_GET_PACKER_INFO_chainId")}},

        'CS_GET_PUBLISH_LIST': {'cs_getPublishList': {
            par_d.get("CHAINID"): u.get("z79_CS_GET_PUBLISH_LIST_chainId"),
            par_d.get("ADDRESS"): u.get("z79_CS_GET_PUBLISH_LIST_address"),
            par_d.get("TYPE"): u.get("z79_CS_GET_PUBLISH_LIST_type")}},

        'CS_GET_ROUND_INFO': {'cs_getRoundInfo': {
            par_d.get("CHAINID"): u.get("z80_CS_GET_ROUND_INFO_chainId")}},

        'CS_GET_ROUND_MEMBER_LIST': {'cs_getRoundMemberList': {
            par_d.get("CHAINID"): u.get("z81_CS_GET_ROUND_MEMBER_LIST_chainId"),
            par_d.get("EXTEND"): u.get("z81_CS_GET_ROUND_MEMBER_LIST_extend")}},

        'CS_GET_SEED_NODE_INFO': {'cs_getSeedNodeInfo': {
            par_d.get("CHAINID"): u.get("z82_CS_GET_SEED_NODE_INFO_chainId")}},

        'CS_GET_WHOLEINFO': {'cs_getwholeinfo': {
            par_d.get("CHAINID"): u.get("z83_CS_GET_WHOLEINFO_chainId")}},

        'CS_MULTI_DEPOSIT': {'cs_multiDeposit': {
            par_d.get("CHAINID"): u.get("z84_CS_MULTI_DEPOSIT_chainId"),
            par_d.get("ADDRESS"): u.get("z84_CS_MULTI_DEPOSIT_address"),
            par_d.get("AGENTHASH"): u.get("z84_CS_MULTI_DEPOSIT_agentHash"),
            par_d.get("DEPOSIT"): u.get("z84_CS_MULTI_DEPOSIT_deposit"),
            par_d.get("PASSWORD"): u.get("z84_CS_MULTI_DEPOSIT_password"),
            par_d.get("SIGNADDRESS"): u.get("z84_CS_MULTI_DEPOSIT_signAddress")}},

        'CS_MULTI_WITHDRAW': {'cs_multiWithdraw': {
            par_d.get("CHAINID"): u.get("z85_CS_MULTI_WITHDRAW_chainId"),
            par_d.get("ADDRESS"): u.get("z85_CS_MULTI_WITHDRAW_address"),
            par_d.get("TXHASH"): u.get("z85_CS_MULTI_WITHDRAW_txHash"),
            par_d.get("PASSWORD"): u.get("z85_CS_MULTI_WITHDRAW_password"),
            par_d.get("SIGNADDRESS"): u.get("z85_CS_MULTI_WITHDRAW_signAddress")}},

        'CS_RANDOM_RAW_SEEDS_COUNT': {'cs_random_raw_seeds_count': {
            par_d.get("CHAINID"): u.get("z86_CS_RANDOM_RAW_SEEDS_COUNT_chainId"),
            par_d.get("HEIGHT"): u.get("z86_CS_RANDOM_RAW_SEEDS_COUNT_height"),
            par_d.get("COUNT"): u.get("z86_CS_RANDOM_RAW_SEEDS_COUNT_count")}},

        'CS_RANDOM_RAW_SEEDS_HEIGHT': {'cs_random_raw_seeds_height': {
            par_d.get("CHAINID"): u.get("z87_CS_RANDOM_RAW_SEEDS_HEIGHT_chainId"),
            par_d.get("STARTHEIGHT"): u.get("z87_CS_RANDOM_RAW_SEEDS_HEIGHT_startHeight"),
            par_d.get("ENDHEIGHT"): u.get("z87_CS_RANDOM_RAW_SEEDS_HEIGHT_endHeight")}},

        'CS_RANDOM_SEED_COUNT': {'cs_random_seed_count': {
            par_d.get("CHAINID"): u.get("z88_CS_RANDOM_SEED_COUNT_chainId"),
            par_d.get("HEIGHT"): u.get("z88_CS_RANDOM_SEED_COUNT_height"),
            par_d.get("COUNT"): u.get("z88_CS_RANDOM_SEED_COUNT_count"),
            par_d.get("ALGORITHM"): u.get("z88_CS_RANDOM_SEED_COUNT_algorithm")}},

        'CS_RANDOM_SEED_HEIGHT': {'cs_random_seed_height': {
            par_d.get("CHAINID"): u.get("z89_CS_RANDOM_SEED_HEIGHT_chainId"),
            par_d.get("STARTHEIGHT"): u.get("z89_CS_RANDOM_SEED_HEIGHT_startHeight"),
            par_d.get("ENDHEIGHT"): u.get("z89_CS_RANDOM_SEED_HEIGHT_endHeight"),
            par_d.get("ALGORITHM"): u.get("z89_CS_RANDOM_SEED_HEIGHT_algorithm")}},

        'CS_RECEIVE_HEADERLIST': {'cs_receiveHeaderList': {
            par_d.get("CHAINID"): u.get("z90_CS_RECEIVE_HEADERLIST_chainId"),
            par_d.get("HEADERLIST"): u.get("z90_CS_RECEIVE_HEADERLIST_headerList")}},

        'CS_RUN_CHAIN': {'cs_runChain': {
            par_d.get("CHAINID"): u.get("z91_CS_RUN_CHAIN_chainId")}},

        'CS_RUN_MAINCHAIN': {'cs_runMainChain': {
            par_d.get("CHAINID"): u.get("z92_CS_RUN_MAINCHAIN_chainId")}},

        'CS_STOPAGENT': {'cs_stopAgent': {
            par_d.get("CHAINID"): u.get("z93_CS_STOPAGENT_chainId"),
            par_d.get("ADDRESS"): u.get("z93_CS_STOPAGENT_address"),
            par_d.get("PASSWORD"): u.get("z93_CS_STOPAGENT_password")}},

        'CS_STOP_AGENT': {'cs_stopagent': {
            par_d.get("CHAINID"): u.get("z94_CS_STOP_AGENT_chainId"),
            par_d.get("ADDRESS"): u.get("z94_CS_STOP_AGENT_address"),
            par_d.get("PASSWORD"): u.get("z94_CS_STOP_AGENT_password")}},

        'CS_STOPCHAIN': {'cs_stopChain': {
            par_d.get("CHAINID"): u.get("z95_CS_STOPCHAIN_chainId")}},

        'CS_STOP_CHAIN': {'cs_stopchain': {
            par_d.get("CHAINID"): u.get("z96_CS_STOP_CHAIN_chainId")}},

        'CS_STOP_CONTRACT_AGENT': {'cs_stopContractAgent': {
            par_d.get("CHAINID"): u.get("z97_CS_STOP_CONTRACT_AGENT_chainId"),
            par_d.get("CONTRACTADDRESS"): u.get(
                "z97_CS_STOP_CONTRACT_AGENT_contractAddress"),
            par_d.get("CONTRACTSENDER"): u.get(
                "z97_CS_STOP_CONTRACT_AGENT_contractSender"),
            par_d.get("CONTRACTBALANCE"): u.get(
                "z97_CS_STOP_CONTRACT_AGENT_contractBalance"),
            par_d.get("CONTRACTNONCE"): u.get("z97_CS_STOP_CONTRACT_AGENT_contractNonce"),
            par_d.get("BLOCKTIME"): u.get("z97_CS_STOP_CONTRACT_AGENT_blockTime")}},

        'CS_STOP_MULTI_AGENT': {'cs_stopMultiAgent': {
            par_d.get("CHAINID"): u.get("z98_CS_STOP_MULTI_AGENT_chainId"),
            par_d.get("ADDRESS"): u.get("z98_CS_STOP_MULTI_AGENT_address"),
            par_d.get("PASSWORD"): u.get("z98_CS_STOP_MULTI_AGENT_password"),
            par_d.get("SIGNADDRESS"): u.get("z98_CS_STOP_MULTI_AGENT_signAddress")}},

        'CS_TRIGGER_COINBASE_CONTRACT': {'cs_triggerCoinBaseContract': {
            par_d.get("CHAINID"): u.get("z99_CS_TRIGGER_COINBASE_CONTRACT_chainId"),
            par_d.get("TX"): u.get("z99_CS_TRIGGER_COINBASE_CONTRACT_tx"),
            par_d.get("BLOCKHEADER"): u.get(
                "z99_CS_TRIGGER_COINBASE_CONTRACT_blockHeader"),
            par_d.get("STATEROOT"): u.get("z99_CS_TRIGGER_COINBASE_CONTRACT_stateRoot")}},

        'CS_UPDATE_AGENT_CONSENSUS_STATUS': {'cs_updateAgentConsensusStatus': {
            par_d.get("CHAINID"): u.get(
                "z100_CS_UPDATE_AGENT_CONSENSUS_STATUS_chainId")}},

        'CS_UPDATE_AGENT_STATUS': {'cs_updateAgentStatus': {
            par_d.get("CHAINID"): u.get("z101_CS_UPDATE_AGENT_STATUS_chainId"),
            par_d.get("STATUS"): u.get("z101_CS_UPDATE_AGENT_STATUS_status")}},

        'CS_VALIDBLOCK': {'cs_validBlock': {
            par_d.get("CHAINID"): u.get("z102_CS_VALIDBLOCK_chainId"),
            par_d.get("DOWNLOAD"): u.get("z102_CS_VALIDBLOCK_download"),
            par_d.get("BLOCK"): u.get("z102_CS_VALIDBLOCK_block")}},

        'CS_WITHDRAW': {'cs_withdraw': {
            par_d.get("CHAINID"): u.get("z103_CS_WITHDRAW_chainId"),
            par_d.get("ADDRESS"): u.get("z103_CS_WITHDRAW_address"),
            par_d.get("TXHASH"): u.get("z103_CS_WITHDRAW_txHash"),
            par_d.get("PASSWORD"): u.get("z103_CS_WITHDRAW_password")}},

        'DEPOSIT_VALID': {'depositValid': {
            par_d.get("CHAINID"): u.get("z104_DEPOSIT_VALID_chainId"),
            par_d.get("TX"): u.get("z104_DEPOSIT_VALID_tx")}},

        'GET_ASSETS_BY_ID': {'getAssetsById': {
            par_d.get("CHAINID"): u.get("z105_GET_ASSETS_BY_ID_chainId"),
            par_d.get("ASSETIDS"): u.get("z105_GET_ASSETS_BY_ID_assetIds")}},

        'GET_BALANCE': {'getBalance': {
            par_d.get("CHAINID"): u.get("z106_GET_BALANCE_chainId"),
            par_d.get("ASSETCHAINID"): u.get("z106_GET_BALANCE_assetChainId"),
            par_d.get("ASSETID"): u.get("z106_GET_BALANCE_assetId"),
            par_d.get("ADDRESS"): u.get("z106_GET_BALANCE_address")}},

        'GET_BALANCE_NONCE': {'getBalanceNonce': {
            par_d.get("CHAINID"): u.get("z107_GET_BALANCE_NONCE_chainId"),
            par_d.get("ASSETCHAINID"): u.get("z107_GET_BALANCE_NONCE_assetChainId"),
            par_d.get("ASSETID"): u.get("z107_GET_BALANCE_NONCE_assetId"),
            par_d.get("ADDRESS"): u.get("z107_GET_BALANCE_NONCE_address"),
            par_d.get("ISCONFIRMED"): u.get("z107_GET_BALANCE_NONCE_isConfirmed")}},

        'GET_BLOCK_BY_HASH': {'getBlockByHash': {
            par_d.get("CHAINID"): u.get("z108_GET_BLOCK_BY_HASH_chainId"),
            par_d.get("HASH"): u.get("z108_GET_BLOCK_BY_HASH_hash")}},

        'GET_BLOCK_BY_HEIGHT': {'getBlockByHeight': {
            par_d.get("CHAINID"): u.get("z109_GET_BLOCK_BY_HEIGHT_chainId"),
            par_d.get("HEIGHT"): u.get("z109_GET_BLOCK_BY_HEIGHT_height")}},

        'GET_BLOCKHEADER_BY_HASH': {'getBlockHeaderByHash': {
            par_d.get("CHAINID"): u.get("z110_GET_BLOCKHEADER_BY_HASH_chainId"),
            par_d.get("HASH"): u.get("z110_GET_BLOCKHEADER_BY_HASH_hash")}},

        'GET_BLOCKHEADER_BY_HEIGHT': {'getBlockHeaderByHeight': {
            par_d.get("CHAINID"): u.get("z111_GET_BLOCKHEADER_BY_HEIGHT_chainId"),
            par_d.get("HEIGHT"): u.get("z111_GET_BLOCKHEADER_BY_HEIGHT_height")}},

        'GET_BLOCKHEADER_PO_BY_HASH': {'getBlockHeaderPoByHash': {
            par_d.get("CHAINID"): u.get("z112_GET_BLOCKHEADER_PO_BY_HASH_chainId"),
            par_d.get("HASH"): u.get("z112_GET_BLOCKHEADER_PO_BY_HASH_hash")}},

        'GET_BLOCKHEADER_POBY_HEIGHT': {'getBlockHeaderPoByHeight': {
            par_d.get("CHAINID"): u.get("z113_GET_BLOCKHEADER_POBY_HEIGHT_chainId"),
            par_d.get("HEIGHT"): u.get("z113_GET_BLOCKHEADER_POBY_HEIGHT_height")}},

        'GET_BLOCKHEADERS_BY_HEIGHT_RANGE': {'getBlockHeadersByHeightRange': {
            par_d.get("CHAINID"): u.get("z114_GET_BLOCKHEADERS_BY_HEIGHT_RANGE_chainId"),
            par_d.get("BEGIN"): u.get("z114_GET_BLOCKHEADERS_BY_HEIGHT_RANGE_begin"),
            par_d.get("END"): u.get("z114_GET_BLOCKHEADERS_BY_HEIGHT_RANGE_end")}},

        'GET_BLOCKHEADERS_FOR_PROTOCOL': {'getBlockHeadersForProtocol': {
            par_d.get("CHAINID"): u.get("z115_GET_BLOCKHEADERS_FOR_PROTOCOL_chainId"),
            par_d.get("INTERVAL"): u.get("z115_GET_BLOCKHEADERS_FOR_PROTOCOL_interval")}},

        'GET_BYZANTINE_COUNT': {'getByzantineCount': {
            par_d.get("CHAINID"): u.get("z116_GET_BYZANTINE_COUNT_chainId")}},

        'GET_CIRCULAT': {'getCirculat': {
            par_d.get("CHAINID"): u.get("z117_GET_CIRCULAT_chainId"),
            par_d.get("NODEID"): u.get("z117_GET_CIRCULAT_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z117_GET_CIRCULAT_messageBody")}},

        'GET_CROSSTX_STATE': {'getCrossTxState': {
            par_d.get("CHAINID"): u.get("z119_GET_CROSSTX_STATE_chainId"),
            par_d.get("TXHASH"): u.get("z119_GET_CROSSTX_STATE_txHash")}},

        'GET_CTX': {'getCtx': {
            par_d.get("CHAINID"): u.get("z120_GET_CTX_chainId"),
            par_d.get("NODEID"): u.get("z120_GET_CTX_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z120_GET_CTX_messageBody")}},

        'GET_CTX_STATE': {'getCtxState': {
            par_d.get("CHAINID"): u.get("z121_GET_CTX_STATE_chainId"),
            par_d.get("NODEID"): u.get("z121_GET_CTX_STATE_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z121_GET_CTX_STATE_messageBody")}},

        'GET_FRIEND_CHAIN_CIRCULATE': {'getFriendChainCirculate': {
            par_d.get("CHAINID"): u.get("z122_GET_FRIEND_CHAIN_CIRCULATE_chainId"),
            par_d.get("ASSETIDS"): u.get("z122_GET_FRIEND_CHAIN_CIRCULATE_assetIds")}},

        'GET_LATEST_BLOCKHEADERS': {'getLatestBlockHeaders': {
            par_d.get("CHAINID"): u.get("z123_GET_LATEST_BLOCKHEADERS_chainId"),
            par_d.get("SIZE"): u.get("z123_GET_LATEST_BLOCKHEADERS_size")}},

        'GET_LATEST_ROUND_BLOCKHEADERS': {'getLatestRoundBlockHeaders': {
            par_d.get("CHAINID"): u.get("z124_GET_LATEST_ROUND_BLOCKHEADERS_chainId"),
            par_d.get("ROUND"): u.get("z124_GET_LATEST_ROUND_BLOCKHEADERS_round")}},

        'GET_NONCE': {'getNonce': {
            par_d.get("CHAINID"): u.get("z125_GET_NONCE_chainId"),
            par_d.get("ASSETCHAINID"): u.get("z125_GET_NONCE_assetChainId"),
            par_d.get("ASSETID"): u.get("z125_GET_NONCE_assetId"),
            par_d.get("ADDRESS"): u.get("z125_GET_NONCE_address"),
            par_d.get("ISCONFIRMED"): u.get("z125_GET_NONCE_isConfirmed")}},

        'GET_OTHERCTX': {'getOtherCtx': {
            par_d.get("CHAINID"): u.get("z126_GET_OTHERCTX_chainId"),
            par_d.get("NODEID"): u.get("z126_GET_OTHERCTX_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z126_GET_OTHERCTX_messageBody")}},

        'GET_ROUND_BLOCKHEADERS': {'getRoundBlockHeaders': {
            par_d.get("CHAINID"): u.get("z128_GET_ROUND_BLOCKHEADERS_chainId"),
            par_d.get("HEIGHT"): u.get("z128_GET_ROUND_BLOCKHEADERS_height"),
            par_d.get("ROUND"): u.get("z128_GET_ROUND_BLOCKHEADERS_round")}},

        'GET_STATUS': {'getStatus': {
            par_d.get("CHAINID"): u.get("z129_GET_STATUS_chainId")}},

        'GET_VERSION': {'getVersion': {
            par_d.get("CHAINID"): u.get("z130_GET_VERSION_chainId")}},

        'INFO': {'info': {
            par_d.get("CHAINID"): u.get("z131_INFO_chainId")}},

        'LATEST_BLOCK': {'latestBlock': {
            par_d.get("CHAINID"): u.get("z132_LATEST_BLOCK_chainId")}},

        'LATEST_BLOCKHEADER': {'latestBlockHeader': {
            par_d.get("CHAINID"): u.get("z133_LATEST_BLOCKHEADER_chainId")}},

        'LATEST_BLOCKHEADER_PO': {'latestBlockHeaderPo': {
            par_d.get("CHAINID"): u.get("z134_LATEST_BLOCKHEADER_PO_chainId")}},

        'LATEST_HEIGHT': {'latestHeight': {
            par_d.get("CHAINID"): u.get("z135_LATEST_HEIGHT_chainId")}},

        'MSG_PROCESS': {'msgProcess': {
            par_d.get("CHAINID"): u.get("z137_MSG_PROCESS_chainId"),
            par_d.get("NODEID"): u.get("z137_MSG_PROCESS_nodeId"),
            par_d.get("CMD"): u.get("z137_MSG_PROCESS_cmd"),
            par_d.get("MESSAGEBODY"): u.get("z137_MSG_PROCESS_messageBody")}},

        'NEW_BLOCK_HEIGHT': {'newBlockHeight': {
            par_d.get("CHAINID"): u.get("z138_NEW_BLOCK_HEIGHT_chainId"),
            par_d.get("HEIGHT"): u.get("z138_NEW_BLOCK_HEIGHT_height")}},

        'NW_ACTIVE_CROSS': {'nw_activeCross': {
            par_d.get("CHAINID"): u.get("z139_NW_ACTIVE_CROSS_chainId"),
            par_d.get("MAXOUT"): u.get("z139_NW_ACTIVE_CROSS_maxOut"),
            par_d.get("MAXIN"): u.get("z139_NW_ACTIVE_CROSS_maxIn"),
            par_d.get("SEEDIPS"): u.get("z139_NW_ACTIVE_CROSS_seedIps")}},

        'NW_ADD_NODES': {'nw_addNodes': {
            par_d.get("CHAINID"): u.get("z140_NW_ADD_NODES_chainId"),
            par_d.get("ISCROSS"): u.get("z140_NW_ADD_NODES_isCross"),
            par_d.get("NODES"): u.get("z140_NW_ADD_NODES_nodes")}},

        'NW_BROADCAST': {'nw_broadcast': {
            par_d.get("CHAINID"): u.get("z141_NW_BROADCAST_chainId"),
            par_d.get("EXCLUDENODES"): u.get("z141_NW_BROADCAST_excludeNodes"),
            par_d.get("MESSAGEBODY"): u.get("z141_NW_BROADCAST_messageBody"),
            par_d.get("COMMAND"): u.get("z141_NW_BROADCAST_command"),
            par_d.get("ISCROSS"): u.get("z141_NW_BROADCAST_isCross"),
            par_d.get("PERCENT"): u.get("z141_NW_BROADCAST_percent")}},

        'NW_CREATE_NODEGROUP': {'nw_createNodeGroup': {
            par_d.get("CHAINID"): u.get("z142_NW_CREATE_NODEGROUP_chainId"),
            par_d.get("MAGICNUMBER"): u.get("z142_NW_CREATE_NODEGROUP_magicNumber"),
            par_d.get("MAXOUT"): u.get("z142_NW_CREATE_NODEGROUP_maxOut"),
            par_d.get("MAXIN"): u.get("z142_NW_CREATE_NODEGROUP_maxIn"),
            par_d.get("MINAVAILABLECOUNT"): u.get(
                "z142_NW_CREATE_NODEGROUP_minAvailableCount"),
            par_d.get("ISCROSSGROUP"): u.get("z142_NW_CREATE_NODEGROUP_isCrossGroup")}},

        'NW_DEL_NODES': {'nw_delNodes': {
            par_d.get("CHAINID"): u.get("z143_NW_DEL_NODES_chainId"),
            par_d.get("NODES"): u.get("z143_NW_DEL_NODES_nodes")}},

        'NW_GET_CHAIN_CONNECT_AMOUNT': {'nw_getChainConnectAmount': {
            par_d.get("CHAINID"): u.get("z144_NW_GET_CHAIN_CONNECT_AMOUNT_chainId"),
            par_d.get("ISCROSS"): u.get("z144_NW_GET_CHAIN_CONNECT_AMOUNT_isCross")}},

        'NW_GET_GROUP_BY_CHAINID': {'nw_getGroupByChainId': {
            par_d.get("CHAINID"): u.get("z145_NW_GET_GROUP_BY_CHAINID_chainId")}},

        'NW_GET_GROUPS': {'nw_getGroups': {
            par_d.get("STARTPAGE"): u.get("z146_NW_GET_GROUPS_startPage"),
            par_d.get("PAGESIZE"): u.get("z146_NW_GET_GROUPS_pageSize")}},

        'NW_GET_NODES': {'nw_getNodes': {
            par_d.get("CHAINID"): u.get("z147_NW_GET_NODES_chainId"),
            par_d.get("STATE"): u.get("z147_NW_GET_NODES_state"),
            par_d.get("ISCROSS"): u.get("z147_NW_GET_NODES_isCross"),
            par_d.get("STARTPAGE"): u.get("z147_NW_GET_NODES_startPage"),
            par_d.get("PAGESIZE"): u.get("z147_NW_GET_NODES_pageSize")}},

        'NW_INFO': {'nw_info': {
            par_d.get("CHAINID"): u.get("z149_NW_INFO_chainId")}},

        'NW_NODES': {'nw_nodes': {
            par_d.get("CHAINID"): u.get("z150_NW_NODES_chainId")}},

        'NW_PROTOCOL_REGISTER': {'nw_protocolRegister': {
            par_d.get("ROLE"): u.get("z151_NW_PROTOCOL_REGISTER_role"),
            par_d.get("PROTOCOLCMDS"): u.get("z151_NW_PROTOCOL_REGISTER_protocolCmds")}},

        'NW_RECONNECT': {'nw_reconnect': {
            par_d.get("CHAINID"): u.get("z152_NW_RECONNECT_chainId")}},

        'NW_SEND_PEERS_MSG': {'nw_sendPeersMsg': {
            par_d.get("CHAINID"): u.get("z153_NW_SEND_PEERS_MSG_chainId"),
            par_d.get("NODES"): u.get("z153_NW_SEND_PEERS_MSG_nodes"),
            par_d.get("MESSAGEBODY"): u.get("z153_NW_SEND_PEERS_MSG_messageBody"),
            par_d.get("COMMAND"): u.get("z153_NW_SEND_PEERS_MSG_command")}},

        'NW_UPDATE_NODE_INFO': {'nw_updateNodeInfo': {
            par_d.get("CHAINID"): u.get("z154_NW_UPDATE_NODE_INFO_chainId"),
            par_d.get("NODEID"): u.get("z154_NW_UPDATE_NODE_INFO_nodeId"),
            par_d.get("BLOCKHEIGHT"): u.get("z154_NW_UPDATE_NODE_INFO_blockHeight"),
            par_d.get("BLOCKHASH"): u.get("z154_NW_UPDATE_NODE_INFO_blockHash")}},

        'PARAM_TEST_CMD': {'paramTestCmd': {
            par_d.get("INTCOUNT"): u.get("z155_PARAM_TEST_CMD_intCount"),
            par_d.get("BYTECOUNT"): u.get("z155_PARAM_TEST_CMD_byteCount"),
            par_d.get("SHORTCOUNT"): u.get("z155_PARAM_TEST_CMD_shortCount"),
            par_d.get("LONGCOUNT"): u.get("z155_PARAM_TEST_CMD_longCount")}},

        'PROTOCOL_VERSION_CHANGE': {'protocolVersionChange': {
            par_d.get("CHAINID"): u.get("z156_PROTOCOL_VERSION_CHANGE_chainId"),
            par_d.get("PROTOCOLVERSION"): u.get(
                "z156_PROTOCOL_VERSION_CHANGE_protocolVersion")}},

        'RECEIVE_PACKING_BLOCK': {'receivePackingBlock': {
            par_d.get("CHAINID"): u.get("z157_RECEIVE_PACKING_BLOCK_chainId"),
            par_d.get("BLOCK"): u.get("z157_RECEIVE_PACKING_BLOCK_block")}},

        'RECV_CIRCULAT': {'recvCirculat': {
            par_d.get("CHAINID"): u.get("z158_RECV_CIRCULAT_chainId"),
            par_d.get("NODEID"): u.get("z158_RECV_CIRCULAT_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z158_RECV_CIRCULAT_messageBody")}},

        'RECV_CTX': {'recvCtx': {
            par_d.get("CHAINID"): u.get("z159_RECV_CTX_chainId"),
            par_d.get("NODEID"): u.get("z159_RECV_CTX_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z159_RECV_CTX_messageBody")}},

        'RECV_CTX_HASH': {'recvCtxHash': {
            par_d.get("CHAINID"): u.get("z160_RECV_CTX_HASH_chainId"),
            par_d.get("NODEID"): u.get("z160_RECV_CTX_HASH_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z160_RECV_CTX_HASH_messageBody")}},

        'RECV_CTX_SIGN': {'recvCtxSign': {
            par_d.get("CHAINID"): u.get("z161_RECV_CTX_SIGN_chainId"),
            par_d.get("NODEID"): u.get("z161_RECV_CTX_SIGN_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z161_RECV_CTX_SIGN_messageBody")}},

        'RECV_CTX_STATE': {'recvCtxState': {
            par_d.get("CHAINID"): u.get("z162_RECV_CTX_STATE_chainId"),
            par_d.get("NODEID"): u.get("z162_RECV_CTX_STATE_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z162_RECV_CTX_STATE_messageBody")}},

        'RECV_OTHER_CTX': {'recvOtherCtx': {
            par_d.get("CHAINID"): u.get("z163_RECV_OTHER_CTX_chainId"),
            par_d.get("NODEID"): u.get("z163_RECV_OTHER_CTX_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z163_RECV_OTHER_CTX_messageBody")}},

        'RECV_REGCHAIN': {'recvRegChain': {
            par_d.get("CHAINID"): u.get("z164_RECV_REGCHAIN_chainId"),
            par_d.get("NODEID"): u.get("z164_RECV_REGCHAIN_nodeId"),
            par_d.get("MESSAGEBODY"): u.get("z164_RECV_REGCHAIN_messageBody")}},

        'REGISTER_PROTOCOL': {'registerProtocol': {
            par_d.get("CHAINID"): u.get("z166_REGISTER_PROTOCOL_chainId"),
            par_d.get("MODULECODE"): u.get("z166_REGISTER_PROTOCOL_moduleCode"),
            par_d.get("LIST"): u.get("z166_REGISTER_PROTOCOL_list")}},

        'ROLLBACK_BLOCK_TXS': {'rollBackBlockTxs': {
            par_d.get("CHAINID"): u.get("z167_ROLLBACK_BLOCK_TXS_chainId"),
            par_d.get("TXLIST"): u.get("z167_ROLLBACK_BLOCK_TXS_txList"),
            par_d.get("BLOCKHEIGHT"): u.get("z167_ROLLBACK_BLOCK_TXS_blockHeight")}},

        'ROLLBACK_UNCONFIRM_TX': {'rollBackUnconfirmTx': {
            par_d.get("CHAINID"): u.get("z168_ROLLBACK_UNCONFIRM_TX_chainId"),
            par_d.get("TX"): u.get("z168_ROLLBACK_UNCONFIRM_TX_tx")}},

        'ROLLBACK_BLOCK': {'rollbackBlock': {
            par_d.get("CHAINID"): u.get("z169_ROLLBACK_BLOCK_chainId"),
            par_d.get("BLOCKHEADER"): u.get("z169_ROLLBACK_BLOCK_blockHeader")}},

        'ROLLBACK_TX_VALIDATE_STATUS': {'rollbackTxValidateStatus': {
            par_d.get("CHAINID"): u.get("z170_ROLLBACK_TX_VALIDATE_STATUS_chainId"),
            par_d.get("TX"): u.get("z170_ROLLBACK_TX_VALIDATE_STATUS_tx")}},

        'SAVE_BLOCK': {'saveBlock': {
            par_d.get("CHAINID"): u.get("z171_SAVE_BLOCK_chainId"),
            par_d.get("BLOCKHEADER"): u.get("z171_SAVE_BLOCK_blockHeader")}},

        'SC_BATCH_BEFORE_END': {'sc_batch_before_end': {
            par_d.get("CHAINID"): u.get("z172_SC_BATCH_BEFORE_END_chainId"),
            par_d.get("BLOCKTYPE"): u.get("z172_SC_BATCH_BEFORE_END_blockType"),
            par_d.get("BLOCKHEIGHT"): u.get("z172_SC_BATCH_BEFORE_END_blockHeight")}},

        'SC_BATCH_BEGIN': {'sc_batch_begin': {
            par_d.get("CHAINID"): u.get("z173_SC_BATCH_BEGIN_chainId"),
            par_d.get("BLOCKTYPE"): u.get("z173_SC_BATCH_BEGIN_blockType"),
            par_d.get("BLOCKHEIGHT"): u.get("z173_SC_BATCH_BEGIN_blockHeight"),
            par_d.get("BLOCKTIME"): u.get("z173_SC_BATCH_BEGIN_blockTime"),
            par_d.get("PACKINGADDRESS"): u.get("z173_SC_BATCH_BEGIN_packingAddress"),
            par_d.get("PRESTATEROOT"): u.get("z173_SC_BATCH_BEGIN_preStateRoot")}},

        'SC_BATCH_END': {'sc_batch_end': {
            par_d.get("CHAINID"): u.get("z174_SC_BATCH_END_chainId"),
            par_d.get("BLOCKHEIGHT"): u.get("z174_SC_BATCH_END_blockHeight")}},

        'SC_CALL': {'sc_call': {
            par_d.get("CHAINID"): u.get("z175_SC_CALL_chainId"),
            par_d.get("SENDER"): u.get("z175_SC_CALL_sender"),
            par_d.get("PASSWORD"): u.get("z175_SC_CALL_password"),
            par_d.get("VALUE"): u.get("z175_SC_CALL_value"),
            par_d.get("GASLIMIT"): u.get("z175_SC_CALL_gasLimit"),
            par_d.get("PRICE"): u.get("z175_SC_CALL_price"),
            par_d.get("CONTRACTADDRESS"): u.get("z175_SC_CALL_contractAddress"),
            par_d.get("METHODNAME"): u.get("z175_SC_CALL_methodName"),
            par_d.get("METHODDESC"): u.get("z175_SC_CALL_methodDesc"),
            par_d.get("ARGS"): u.get("z175_SC_CALL_args"),
            par_d.get("REMARK"): u.get("z175_SC_CALL_remark")}},

        'SC_CALL_VALIDATOR': {'sc_call_validator': {
            par_d.get("CHAINID"): u.get("z176_SC_CALL_VALIDATOR_chainId"),
            par_d.get("TX"): u.get("z176_SC_CALL_VALIDATOR_tx")}},

        'SC_CONSTRUCTOR': {'sc_constructor': {
            par_d.get("CHAINID"): u.get("z177_SC_CONSTRUCTOR_chainId"),
            par_d.get("CONTRACTCODE"): u.get("z177_SC_CONSTRUCTOR_contractCode")}},

        'SC_CONTRACT_INFO': {'sc_contract_info': {
            par_d.get("CHAINID"): u.get("z178_SC_CONTRACT_INFO_chainId"),
            par_d.get("CONTRACTADDRESS"): u.get(
                "z178_SC_CONTRACT_INFO_contractAddress")}},

        'SC_CONTRACT_OFFLINE_TX_HASH_LIST': {'sc_contract_offline_tx_hash_list': {
            par_d.get("CHAINID"): u.get("z179_SC_CONTRACT_OFFLINE_TX_HASH_LIST_chainId"),
            par_d.get("BLOCKHASH"): u.get(
                "z179_SC_CONTRACT_OFFLINE_TX_HASH_LIST_blockHash")}},

        'SC_CONTRACT_RESULT': {'sc_contract_result': {
            par_d.get("CHAINID"): u.get("z180_SC_CONTRACT_RESULT_chainId"),
            par_d.get("HASH"): u.get("z180_SC_CONTRACT_RESULT_hash")}},

        'SC_CONTRACT_RESULT_LIST': {'sc_contract_result_list': {
            par_d.get("CHAINID"): u.get("z181_SC_CONTRACT_RESULT_LIST_chainId"),
            par_d.get("HASHLIST"): u.get("z181_SC_CONTRACT_RESULT_LIST_hashList")}},

        'SC_CONTRACT_TX': {'sc_contract_tx': {
            par_d.get("CHAINID"): u.get("z182_SC_CONTRACT_TX_chainId"),
            par_d.get("HASH"): u.get("z182_SC_CONTRACT_TX_hash")}},

        'SC_CREATE': {'sc_create': {
            par_d.get("CHAINID"): u.get("z183_SC_CREATE_chainId"),
            par_d.get("SENDER"): u.get("z183_SC_CREATE_sender"),
            par_d.get("PASSWORD"): u.get("z183_SC_CREATE_password"),
            par_d.get("ALIAS"): u.get("z183_SC_CREATE_alias"),
            par_d.get("GASLIMIT"): u.get("z183_SC_CREATE_gasLimit"),
            par_d.get("PRICE"): u.get("z183_SC_CREATE_price"),
            par_d.get("CONTRACTCODE"): u.get("z183_SC_CREATE_contractCode"),
            par_d.get("ARGS"): u.get("z183_SC_CREATE_args"),
            par_d.get("REMARK"): u.get("z183_SC_CREATE_remark")}},

        'SC_CREATE_VALIDATOR': {'sc_create_validator': {
            par_d.get("CHAINID"): u.get("z184_SC_CREATE_VALIDATOR_chainId"),
            par_d.get("TX"): u.get("z184_SC_CREATE_VALIDATOR_tx")}},

        'SC_DELETE': {'sc_delete': {
            par_d.get("CHAINID"): u.get("z185_SC_DELETE_chainId"),
            par_d.get("SENDER"): u.get("z185_SC_DELETE_sender"),
            par_d.get("PASSWORD"): u.get("z185_SC_DELETE_password"),
            par_d.get("CONTRACTADDRESS"): u.get("z185_SC_DELETE_contractAddress"),
            par_d.get("REMARK"): u.get("z185_SC_DELETE_remark")}},

        'SC_DELETE_VALIDATOR': {'sc_delete_validator': {
            par_d.get("CHAINID"): u.get("z186_SC_DELETE_VALIDATOR_chainId"),
            par_d.get("TX"): u.get("z186_SC_DELETE_VALIDATOR_tx")}},

        'SC_IMPUTED_CALL_GAS': {'sc_imputed_call_gas': {
            par_d.get("CHAINID"): u.get("z187_SC_IMPUTED_CALL_GAS_chainId"),
            par_d.get("SENDER"): u.get("z187_SC_IMPUTED_CALL_GAS_sender"),
            par_d.get("VALUE"): u.get("z187_SC_IMPUTED_CALL_GAS_value"),
            par_d.get("CONTRACTADDRESS"): u.get(
                "z187_SC_IMPUTED_CALL_GAS_contractAddress"),
            par_d.get("METHODNAME"): u.get("z187_SC_IMPUTED_CALL_GAS_methodName"),
            par_d.get("METHODDESC"): u.get("z187_SC_IMPUTED_CALL_GAS_methodDesc"),
            par_d.get("ARGS"): u.get("z187_SC_IMPUTED_CALL_GAS_args")}},

        'SC_IMPUTED_CREATE_GAS': {'sc_imputed_create_gas': {
            par_d.get("CHAINID"): u.get("z188_SC_IMPUTED_CREATE_GAS_chainId"),
            par_d.get("SENDER"): u.get("z188_SC_IMPUTED_CREATE_GAS_sender"),
            par_d.get("CONTRACTCODE"): u.get("z188_SC_IMPUTED_CREATE_GAS_contractCode"),
            par_d.get("ARGS"): u.get("z188_SC_IMPUTED_CREATE_GAS_args")}},

        'SC_INITIAL_ACCOUNT_TOKEN': {'sc_initial_account_token': {
            par_d.get("CHAINID"): u.get("z189_SC_INITIAL_ACCOUNT_TOKEN_chainId"),
            par_d.get("ADDRESS"): u.get("z189_SC_INITIAL_ACCOUNT_TOKEN_address")}},

        'SC_INVOKE_CONTRACT': {'sc_invoke_contract': {
            par_d.get("CHAINID"): u.get("z190_SC_INVOKE_CONTRACT_chainId"),
            par_d.get("BLOCKTYPE"): u.get("z190_SC_INVOKE_CONTRACT_blockType"),
            par_d.get("TX"): u.get("z190_SC_INVOKE_CONTRACT_tx")}},

        'SC_INVOKE_VIEW': {'sc_invoke_view': {
            par_d.get("CHAINID"): u.get("z191_SC_INVOKE_VIEW_chainId"),
            par_d.get("CONTRACTADDRESS"): u.get("z191_SC_INVOKE_VIEW_contractAddress"),
            par_d.get("METHODNAME"): u.get("z191_SC_INVOKE_VIEW_methodName"),
            par_d.get("METHODDESC"): u.get("z191_SC_INVOKE_VIEW_methodDesc"),
            par_d.get("ARGS"): u.get("z191_SC_INVOKE_VIEW_args")}},

        'SC_PACKAGE_BATCH_END': {'sc_package_batch_end': {
            par_d.get("CHAINID"): u.get("z192_SC_PACKAGE_BATCH_END_chainId"),
            par_d.get("BLOCKHEIGHT"): u.get("z192_SC_PACKAGE_BATCH_END_blockHeight")}},

        'SC_TOKEN_ASSETS_LIST': {'sc_token_assets_list': {
            par_d.get("CHAINID"): u.get("z193_SC_TOKEN_ASSETS_LIST_chainId"),
            par_d.get("ADDRESS"): u.get("z193_SC_TOKEN_ASSETS_LIST_address"),
            par_d.get("PAGENUMBER"): u.get("z193_SC_TOKEN_ASSETS_LIST_pageNumber"),
            par_d.get("PAGESIZE"): u.get("z193_SC_TOKEN_ASSETS_LIST_pageSize")}},

        'SC_TOKEN_BALANCE': {'sc_token_balance': {
            par_d.get("CHAINID"): u.get("z194_SC_TOKEN_BALANCE_chainId"),
            par_d.get("CONTRACTADDRESS"): u.get("z194_SC_TOKEN_BALANCE_contractAddress"),
            par_d.get("ADDRESS"): u.get("z194_SC_TOKEN_BALANCE_address")}},

        'SC_TOKEN_TRANSFER': {'sc_token_transfer': {
            par_d.get("CHAINID"): u.get("z195_SC_TOKEN_TRANSFER_chainId"),
            par_d.get("ADDRESS"): u.get("z195_SC_TOKEN_TRANSFER_address"),
            par_d.get("TOADDRESS"): u.get("z195_SC_TOKEN_TRANSFER_toAddress"),
            par_d.get("CONTRACTADDRESS"): u.get("z195_SC_TOKEN_TRANSFER_contractAddress"),
            par_d.get("PASSWORD"): u.get("z195_SC_TOKEN_TRANSFER_password"),
            par_d.get("AMOUNT"): u.get("z195_SC_TOKEN_TRANSFER_amount"),
            par_d.get("REMARK"): u.get("z195_SC_TOKEN_TRANSFER_remark")}},

        'SC_TOKEN_TRANSFER_LIST': {'sc_token_transfer_list': {
            par_d.get("CHAINID"): u.get("z196_SC_TOKEN_TRANSFER_LIST_chainId"),
            par_d.get("ADDRESS"): u.get("z196_SC_TOKEN_TRANSFER_LIST_address"),
            par_d.get("PAGENUMBER"): u.get("z196_SC_TOKEN_TRANSFER_LIST_pageNumber"),
            par_d.get("PAGESIZE"): u.get("z196_SC_TOKEN_TRANSFER_LIST_pageSize")}},

        'SC_TRANSFER': {'sc_transfer': {
            par_d.get("CHAINID"): u.get("z197_SC_TRANSFER_chainId"),
            par_d.get("ADDRESS"): u.get("z197_SC_TRANSFER_address"),
            par_d.get("TOADDRESS"): u.get("z197_SC_TRANSFER_toAddress"),
            par_d.get("PASSWORD"): u.get("z197_SC_TRANSFER_password"),
            par_d.get("AMOUNT"): u.get("z197_SC_TRANSFER_amount"),
            par_d.get("REMARK"): u.get("z197_SC_TRANSFER_remark")}},

        'SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT': {
            'sc_trigger_payable_for_consensus_contract': {
                par_d.get("CHAINID"): u.get(
                    "z198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_chainId"),
                par_d.get("STATEROOT"): u.get(
                    "z198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_stateRoot"),
                par_d.get("BLOCKHEIGHT"): u.get(
                    "z198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_blockHeight"),
                par_d.get("CONTRACTADDRESS"): u.get(
                    "z198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_contractAddress"),
                par_d.get("TX"): u.get(
                    "z198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_tx")}},

        'SC_UPLOAD': {'sc_upload': {
            par_d.get("CHAINID"): u.get("z199_SC_UPLOAD_chainId"),
            par_d.get("JARFILEDATA"): u.get("z199_SC_UPLOAD_jarFileData")}},

        'SC_VALIDATE_CALL': {'sc_validate_call': {
            par_d.get("CHAINID"): u.get("z200_SC_VALIDATE_CALL_chainId"),
            par_d.get("SENDER"): u.get("z200_SC_VALIDATE_CALL_sender"),
            par_d.get("VALUE"): u.get("z200_SC_VALIDATE_CALL_value"),
            par_d.get("GASLIMIT"): u.get("z200_SC_VALIDATE_CALL_gasLimit"),
            par_d.get("PRICE"): u.get("z200_SC_VALIDATE_CALL_price"),
            par_d.get("CONTRACTADDRESS"): u.get("z200_SC_VALIDATE_CALL_contractAddress"),
            par_d.get("METHODNAME"): u.get("z200_SC_VALIDATE_CALL_methodName"),
            par_d.get("METHODDESC"): u.get("z200_SC_VALIDATE_CALL_methodDesc"),
            par_d.get("ARGS"): u.get("z200_SC_VALIDATE_CALL_args")}},

        'SC_VALIDATE_CREATE': {'sc_validate_create': {
            par_d.get("CHAINID"): u.get("z201_SC_VALIDATE_CREATE_chainId"),
            par_d.get("SENDER"): u.get("z201_SC_VALIDATE_CREATE_sender"),
            par_d.get("GASLIMIT"): u.get("z201_SC_VALIDATE_CREATE_gasLimit"),
            par_d.get("PRICE"): u.get("z201_SC_VALIDATE_CREATE_price"),
            par_d.get("CONTRACTCODE"): u.get("z201_SC_VALIDATE_CREATE_contractCode"),
            par_d.get("ARGS"): u.get("z201_SC_VALIDATE_CREATE_args")}},

        'SC_VALIDATE_DELETE': {'sc_validate_delete': {
            par_d.get("CHAINID"): u.get("z202_SC_VALIDATE_DELETE_chainId"),
            par_d.get("CONTRACTADDRESS"): u.get(
                "z202_SC_VALIDATE_DELETE_contractAddress")}},

        'STOP_AGENTVALID': {'stopAgentValid': {
            par_d.get("CHAINID"): u.get("z203_STOP_AGENTVALID_chainId"),
            par_d.get("TX"): u.get("z203_STOP_AGENTVALID_tx")}},

        'TX_COMMIT': {'txCommit': {
            par_d.get("CHAINID"): u.get("z204_TX_COMMIT_chainId"),
            par_d.get("TXLIST"): u.get("z204_TX_COMMIT_txList"),
            par_d.get("BLOCKHEADER"): u.get("z204_TX_COMMIT_blockHeader")}},

        'TX_VALIDATOR': {'txValidator': {
            par_d.get("CHAINID"): u.get("z205_TX_VALIDATOR_chainId"),
            par_d.get("TXLIST"): u.get("z205_TX_VALIDATOR_txList"),
            par_d.get("BLOCKHEADER"): u.get("z205_TX_VALIDATOR_blockHeader")}},

        'TX_BACK_PACKABLE_TXS': {'tx_backPackableTxs': {
            par_d.get("CHAINID"): u.get("z206_TX_BACK_PACKABLE_TXS_chainId"),
            par_d.get("TXLIST"): u.get("z206_TX_BACK_PACKABLE_TXS_txList")}},

        'TX_BATCH_VERIFY': {'tx_batchVerify': {
            par_d.get("CHAINID"): u.get("z207_TX_BATCH_VERIFY_chainId"),
            par_d.get("TXLIST"): u.get("z207_TX_BATCH_VERIFY_txList"),
            par_d.get("BLOCKHEADER"): u.get("z207_TX_BATCH_VERIFY_blockHeader"),
            par_d.get("PRESTATEROOT"): u.get("z207_TX_BATCH_VERIFY_preStateRoot")}},

        'TX_BL_STATE': {'tx_bl_state': {
            par_d.get("CHAINID"): u.get("z208_TX_BL_STATE_chainId"),
            par_d.get("STATUS"): u.get("z208_TX_BL_STATE_status")}},

        'TX_BLOCK_HEIGHT': {'tx_blockHeight': {
            par_d.get("CHAINID"): u.get("z209_TX_BLOCK_HEIGHT_chainId"),
            par_d.get("HEIGHT"): u.get("z209_TX_BLOCK_HEIGHT_height")}},

        'TX_CS_STATE': {'tx_cs_state': {
            par_d.get("CHAINID"): u.get("z210_TX_CS_STATE_chainId"),
            par_d.get("PACKAGING"): u.get("z210_TX_CS_STATE_packaging")}},

        'TX_GET_BLOCKTXS': {'tx_getBlockTxs': {
            par_d.get("CHAINID"): u.get("z211_TX_GET_BLOCKTXS_chainId"),
            par_d.get("TXHASHLIST"): u.get("z211_TX_GET_BLOCKTXS_txHashList")}},

        'TX_GET_BLOCKTXS_EXTEND': {'tx_getBlockTxsExtend': {
            par_d.get("CHAINID"): u.get("z212_TX_GET_BLOCKTXS_EXTEND_chainId"),
            par_d.get("TXHASHLIST"): u.get("z212_TX_GET_BLOCKTXS_EXTEND_txHashList"),
            par_d.get("ALLHITS"): u.get("z212_TX_GET_BLOCKTXS_EXTEND_allHits")}},

        'TX_GET_CONFIRMED_TX': {'tx_getConfirmedTx': {
            par_d.get("CHAINID"): u.get("z213_TX_GET_CONFIRMED_TX_chainId"),
            par_d.get("TXHASH"): u.get("z213_TX_GET_CONFIRMED_TX_txHash")}},

        'TX_GET_CONFIRMED_TX_CLIENT': {'tx_getConfirmedTxClient': {
            par_d.get("CHAINID"): u.get("z214_TX_GET_CONFIRMED_TX_CLIENT_chainId"),
            par_d.get("TXHASH"): u.get("z214_TX_GET_CONFIRMED_TX_CLIENT_txHash")}},

        'TX_GET_NONEXISTENT_UNCONFIRMED_HASHS': {'tx_getNonexistentUnconfirmedHashs': {
            par_d.get("CHAINID"): u.get(
                "z215_TX_GET_NONEXISTENT_UNCONFIRMED_HASHS_chainId"),
            par_d.get("TXHASHLIST"): u.get(
                "z215_TX_GET_NONEXISTENT_UNCONFIRMED_HASHS_txHashList")}},

        'TX_GET_SYSTEMTYPES': {'tx_getSystemTypes': {
            par_d.get("CHAINID"): u.get("z216_TX_GET_SYSTEMTYPES_chainId")}},

        'TX_GET_TX': {'tx_getTx': {
            par_d.get("CHAINID"): u.get("z217_TX_GET_TX_chainId"),
            par_d.get("TXHASH"): u.get("z217_TX_GET_TX_txHash")}},

        'TX_GET_TX_CLIENT': {'tx_getTxClient': {
            par_d.get("CHAINID"): u.get("z218_TX_GET_TX_CLIENT_chainId"),
            par_d.get("TXHASH"): u.get("z218_TX_GET_TX_CLIENT_txHash")}},

        'TX_NEWTX': {'tx_newTx': {
            par_d.get("CHAINID"): u.get("z219_TX_NEWTX_chainId"),
            par_d.get("TX"): u.get("z219_TX_NEWTX_tx")}},

        'TX_PACKABLE_TXS': {'tx_packableTxs': {
            par_d.get("CHAINID"): u.get("z220_TX_PACKABLE_TXS_chainId"),
            par_d.get("ENDTIMESTAMP"): u.get("z220_TX_PACKABLE_TXS_endTimestamp"),
            par_d.get("MAXTXDATASIZE"): u.get("z220_TX_PACKABLE_TXS_maxTxDataSize"),
            par_d.get("BLOCKTIME"): u.get("z220_TX_PACKABLE_TXS_blockTime"),
            par_d.get("PACKINGADDRESS"): u.get("z220_TX_PACKABLE_TXS_packingAddress"),
            par_d.get("PRESTATEROOT"): u.get("z220_TX_PACKABLE_TXS_preStateRoot")}},

        'TX_REGISTER': {'tx_register': {
            par_d.get("CHAINID"): u.get("z221_TX_REGISTER_chainId"),
            par_d.get("MODULECODE"): u.get("z221_TX_REGISTER_moduleCode"),
            par_d.get("LIST"): u.get("z221_TX_REGISTER_list"),
            par_d.get("DELLIST"): u.get("z221_TX_REGISTER_delList")}},

        'TX_ROLLBACK': {'tx_rollback': {
            par_d.get("CHAINID"): u.get("z222_TX_ROLLBACK_chainId"),
            par_d.get("TXHASHLIST"): u.get("z222_TX_ROLLBACK_txHashList"),
            par_d.get("BLOCKHEADER"): u.get("z222_TX_ROLLBACK_blockHeader")}},

        'TX_SAVE': {'tx_save': {
            par_d.get("CHAINID"): u.get("z223_TX_SAVE_chainId"),
            par_d.get("TXLIST"): u.get("z223_TX_SAVE_txList"),
            par_d.get("CONTRACTLIST"): u.get("z223_TX_SAVE_contractList"),
            par_d.get("BLOCKHEADER"): u.get("z223_TX_SAVE_blockHeader")}},

        'TX_VERIFY_TX': {'tx_verifyTx': {
            par_d.get("CHAINID"): u.get("z224_TX_VERIFY_TX_chainId"),
            par_d.get("TX"): u.get("z224_TX_VERIFY_TX_tx")}},

        'UPDATE_CHAIN_ASSET': {'updateChainAsset': {
            par_d.get("CHAINID"): u.get("z225_UPDATE_CHAIN_ASSET_chainId"),
            par_d.get("ASSETS"): u.get("z225_UPDATE_CHAIN_ASSET_assets")}},

        'VERIFY_COINDATA': {'verifyCoinData': {
            par_d.get("CHAINID"): u.get("z226_VERIFY_COINDATA_chainId"),
            par_d.get("TX"): u.get("z226_VERIFY_COINDATA_tx")}},

        'VERIFY_COINDATA_BATCH_PACKAGED': {'verifyCoinDataBatchPackaged': {
            par_d.get("CHAINID"): u.get("z227_VERIFY_COINDATA_BATCH_PACKAGED_chainId"),
            par_d.get("TXLIST"): u.get("z227_VERIFY_COINDATA_BATCH_PACKAGED_txList")}},

        'WITHDRAW_VALID': {'withdrawValid': {
            par_d.get("CHAINID"): u.get("z228_WITHDRAW_VALID_chainId"),
            par_d.get("TX"): u.get("z228_WITHDRAW_VALID_tx")}}
    }
