# note: Items in Constants typically don't change frequently

__ALL__ = \
 ['ADDRESS', 'ADDRESSPREFIX', 'ADDRESSTYPE', 'AGENTADDRESS', 'AGENTHASH', 'ALGORITHM', 'ALIAS',
  'ALLHITS', 'AMOUNT', 'ARGS', 'ASSETCHAINID', 'ASSETID', 'ASSETIDS', 'ASSETINFOLIST', 'ASSETNAME',
  'ASSETS', 'BEGIN', 'BLOCK', 'BLOCKHASH', 'BLOCKHEADER', 'BLOCKHEIGHT', 'BLOCKTIME', 'BLOCKTYPE',
  'BYTECOUNT', 'CHAINID', 'CHAINNAME', 'CIRCULATECHAINID', 'CMD', 'CMDREGISTERLIST', 'COMMAND',
  'COMMISSIONRATE', 'CONTRACTADDRESS', 'CONTRACTBALANCE', 'CONTRACTCODE', 'CONTRACTLIST', 'CONTRACTNONCE',
  'CONTRACTSENDER', 'COUNT', 'DATA', 'DECIMALPLACES', 'DELLIST', 'DEPOSIT', 'DOWNLOAD', 'END', 'ENDHEIGHT',
  'ENDTIMESTAMP', 'EVIDENCEHEADER', 'EXCLUDENODES', 'EXTEND', 'EXTENDSDATA', 'FILEPATH',
  'FRESTARTIFRUNNING', 'GASLIMIT', 'HASH', 'HASHLIST', 'HEADERLIST', 'HEIGHT', 'INITNUMBER', 'INPUTS',
  'INTCOUNT', 'INTERVAL', 'ISCONFIRMED', 'ISCROSS', 'ISCROSSGROUP', 'JARFILEDATA', 'JOINAGENTHASH',
  'KEYSTORE', 'KEYWORD', 'LIST', 'LISTFROM', 'LISTTO', 'LMAXCPUS', 'LMODULENAME', 'LMODULEVERSION',
  'LONGCOUNT', 'MAGICNUMBER', 'MAXIN', 'MAXOUT', 'MAXSIGNATURECOUNT', 'MAXTXDATASIZE', 'MESSAGEBODY',
  'METHODDESC', 'METHODNAME', 'MINAVAILABLECOUNT', 'MINAVAILABLENODENUM', 'MINSIGNS', 'MODULECODE',
  'NEWPASSWORD', 'NODEID', 'NODES', 'OUTPUTS', 'OVERWRITE', 'PACKAGING', 'PACKINGADDRESS', 'PAGENUMBER',
  'PAGESIZE', 'PASSWORD', 'PERCENT', 'PREFIXLIST', 'PRESTATEROOT', 'PRICE', 'PRIKEY', 'PROTOCOLCMDS',
  'PROTOCOLVERSION', 'PUBKEY', 'PUBKEYS', 'REGISTERTIME', 'REMARK', 'REWARDADDRESS', 'ROLE', 'ROUND',
  'SEEDIPS', 'SENDER', 'SHORTCOUNT', 'SIG', 'SIGNADDRESS', 'SIGNATUREBFTRATIO', 'SIGNPASSWORD', 'SIZE',
  'STARTHEIGHT', 'STARTPAGE', 'STATE', 'STATEROOT', 'STATUS', 'SYMBOL', 'TOADDRESS', 'TX', 'TXHASH',
  'TXHASHLIST', 'TXLIST', 'TYPE', 'USABLE', 'VALUE', 'VERIFIERLIST', 'my_address', 'my_addressPrefix',
  'my_addressType', 'my_agentAddress', 'my_agentHash',
  'my_algorithm', 'my_alias', 'my_allHits', 'my_amount', 'my_args', 'my_assetChainId',
  'my_assetId',
  'my_assetIds', 'my_assetInfoList', 'my_assetName', 'my_assets', 'my_begin', 'my_block',
  'my_blockHash', 'my_blockHeader', 'my_blockHeight', 'my_blockTime', 'my_blockType',
  'my_byteCount',
  'my_chainId', 'my_chainName', 'my_circulateChainId', 'my_cmd', 'my_cmdRegisterList',
  'my_command',
  'my_commissionRate', 'my_contractAddress', 'my_contractBalance', 'my_contractCode',
  'my_contractList', 'my_contractNonce', 'my_contractSender', 'my_count', 'my_data',
  'my_decimalPlaces', 'my_delList', 'my_deposit', 'my_download', 'my_end', 'my_endHeight',
  'my_endTimestamp', 'my_evidenceHeader', 'my_excludeNodes', 'my_extend', 'my_extendsData',
  'my_fRestartIfRunning', 'my_filePath', 'my_gasLimit', 'my_hash', 'my_hashList',
  'my_headerList',
  'my_height', 'my_initNumber', 'my_inputs', 'my_intCount', 'my_interval', 'my_isConfirmed',
  'my_isCross', 'my_isCrossGroup', 'my_jarFileData', 'my_joinAgentHash', 'my_keyStore',
  'my_keyWord',
  'my_lMaxCPUs', 'my_lModuleName', 'my_lModuleVersion', 'my_list', 'my_listFrom', 'my_listTo',
  'my_longCount', 'my_magicNumber', 'my_maxIn', 'my_maxOut', 'my_maxSignatureCount',
  'my_maxTxDataSize', 'my_messageBody', 'my_methodDesc', 'my_methodName',
  'my_minAvailableCount',
  'my_minAvailableNodeNum', 'my_minSigns', 'my_moduleCode', 'my_newPassword', 'my_nodeId',
  'my_nodes', 'my_outputs', 'my_overwrite', 'my_packaging', 'my_packingAddress',
  'my_pageNumber',
  'my_pageSize', 'my_password', 'my_percent', 'my_preStateRoot', 'my_prefixList', 'my_priKey',
  'my_price', 'my_protocolCmds', 'my_protocolVersion', 'my_pubKey', 'my_pubKeys',
  'my_registerTime',
  'my_remark', 'my_rewardAddress', 'my_role', 'my_round', 'my_seedIps', 'my_sender',
  'my_shortCount',
  'my_sig', 'my_signAddress', 'my_signPassword', 'my_signatureBFTRatio', 'my_size',
  'my_startHeight',
  'my_startPage', 'my_state', 'my_stateRoot', 'my_status', 'my_symbol', 'my_toAddress', 'my_tx',
  'my_txHash', 'my_txHashList', 'my_txList', 'my_type', 'my_usable', 'my_value',
  'my_verifierList']


