#!/usr/bin/python3.7
"""
by Nancy Schorr for Nuls, None),
(December, None),
(2019

"""
# Do not edit this file to run queries - only for adding or changing methods
# from UserSettings.nulsws_USER_PARAMS import *
# from UserSettings.nulsws_USER_PARAMS import _5_AC_CREATE_OFFLINE_ACCOUNT_chainId
# from Libraries.Constants.nulsws_CONSTANTS_API_LABELS import *
# # from Libraries.Constants.nulsws_CONSTANTS_otherlabels import *
# from Libraries.Constants.nulsws_CONSTANTS_PARAM_LABELS import *
# import Libraries.Constants.nulsws_CONSTANTS_PARAM_LABELS
# import UserSettings.nulsws_USER_PARAMS
# from UserSettings import nulsws_USER_PARAMS
#
# from importlib import import_module
# import importlib.util
#
# importlib.

from UserSettings.nulsws_USER_PARAMS import *
from Libraries.Constants.nulsws_CONSTANTS_API_LABELS import *
from Libraries.Constants.Dictionaires.nulsws_CONSTANTS_PARAM_LABELS import param_name_dict as p

# list of lists of tups
USER_CALLS_DB = [
    [
        AC_CREATE_OFFLINE_ACCOUNT, [
        (p.get("CHAINID"), _5_AC_CREATE_OFFLINE_ACCOUNT_chainId),
        (p.get("COUNT"), _5_AC_CREATE_OFFLINE_ACCOUNT_count),
        (p.get("PASSWORD"), _5_AC_CREATE_OFFLINE_ACCOUNT_password)
    ]],
    [
        AC_EXPORT_ACCOUNT_KEYSTORE, [
        (p.get("CHAINID"), _6_AC_EXPORT_ACCOUNT_KEYSTORE_chainId),
        (p.get("ADDRESS"), _6_AC_EXPORT_ACCOUNT_KEYSTORE_address),
        (p.get("PASSWORD"), _6_AC_EXPORT_ACCOUNT_KEYSTORE_password),
        (p.get("FILEPATH"), _6_AC_EXPORT_ACCOUNT_KEYSTORE_filePath)
    ]],
    [
        AC_EXPORT_KEYSTORE_JSON, [
        (p.get("CHAINID"), _7_AC_EXPORT_KEYSTORE_JSON_chainId),
        (p.get("ADDRESS"), _7_AC_EXPORT_KEYSTORE_JSON_address),
        (p.get("PASSWORD"), _7_AC_EXPORT_KEYSTORE_JSON_password)
    ]],
    [
        AC_GET_ACCOUNT_BYADDRESS, [
        (p.get("CHAINID"), _8_AC_GET_ACCOUNT_BYADDRESS_chainId),
        (p.get("ADDRESS"), _8_AC_GET_ACCOUNT_BYADDRESS_address)
    ]],
    [
        AC_GET_ACCOUNT_LIST, [
        (p.get("CHAINID"), _9_AC_GET_ACCOUNT_LIST_chainId)
    ]],
    [
        AC_GET_ADDRESS_LIST, [
        (p.get("CHAINID"), _10_AC_GET_ADDRESS_LIST_chainId),
        (p.get("PAGENUMBER"), _10_AC_GET_ADDRESS_LIST_pageNumber),
        (p.get("PAGESIZE"), _10_AC_GET_ADDRESS_LIST_pageSize)
    ]],
    [
        AC_GET_ADDRESS_PREFIX_BY_CHAINID, [
        (p.get("CHAINID"), _11_AC_GET_ADDRESS_PREFIX_BY_CHAINID_chainId)
    ]],
    [
        AC_GET_ALIASBY_ADDRESS, [
        (p.get("CHAINID"), _12_AC_GET_ALIASBY_ADDRESS_chainId),
        (p.get("ADDRESS"), _12_AC_GET_ALIASBY_ADDRESS_address)
    ]],
    [
        AC_GET_ALL_PRIKEY, [
        (p.get("CHAINID"), _14_AC_GET_ALL_PRIKEY_chainId),
        (p.get("PASSWORD"), _14_AC_GET_ALL_PRIKEY_password)
    ]],
    [
        AC_GET_ENCRYPTED_ADDRESS_LIST, [
        (p.get("CHAINID"), _15_AC_GET_ENCRYPTED_ADDRESS_LIST_chainId)
    ]],
    [
        AC_GET_MULTI_SIGN_ACCOUNT, [
        (p.get("CHAINID"), _16_AC_GET_MULTI_SIGN_ACCOUNT_chainId),
        (p.get("ADDRESS"), _16_AC_GET_MULTI_SIGN_ACCOUNT_address)
    ]],
    [
        AC_GET_PUBKEY, [
        (p.get("CHAINID"), _17_AC_GET_PUBKEY_chainId),
        (p.get("ADDRESS"), _17_AC_GET_PUBKEY_address),
        (p.get("PASSWORD"), _17_AC_GET_PUBKEY_password)
    ]],
    [
        AC_IMPORT_ACCOUNT_BY_KEYSTORE, [
        (p.get("CHAINID"), _18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_chainId),
        (p.get("PASSWORD"), _18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_password),
        (p.get("KEYSTORE"), _18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_keyStore),
        (p.get("OVERWRITE"), _18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_overwrite)
    ]],
    [
        AC_IMPORT_ACCOUNT_BY_PRIKEY, [
        (p.get("CHAINID"), _19_AC_IMPORT_ACCOUNT_BY_PRIKEY_chainId),
        (p.get("PASSWORD"), _19_AC_IMPORT_ACCOUNT_BY_PRIKEY_password),
        (p.get("PRIKEY"), _19_AC_IMPORT_ACCOUNT_BY_PRIKEY_priKey),
        (p.get("OVERWRITE"), _19_AC_IMPORT_ACCOUNT_BY_PRIKEY_overwrite)
    ]],
    [
        AC_IS_ALIAS_USABLE, [
        (p.get("CHAINID"), _20_AC_IS_ALIAS_USABLE_chainId),
        (p.get("ALIAS"), _20_AC_IS_ALIAS_USABLE_alias)
    ]],
    [
        AC_IS_MULTISIGN_ACCOUNT_BUILDER, [
        (p.get("CHAINID"), _21_AC_IS_MULTISIGN_ACCOUNT_BUILDER_chainId),
        (p.get("ADDRESS"), _21_AC_IS_MULTISIGN_ACCOUNT_BUILDER_address),
        (p.get("PUBKEY"), _21_AC_IS_MULTISIGN_ACCOUNT_BUILDER_pubKey)
    ]],
    [
        AC_REMOVE_ACCOUNT, [
        (p.get("CHAINID"), _22_AC_REMOVE_ACCOUNT_chainId),
        (p.get("ADDRESS"), _22_AC_REMOVE_ACCOUNT_address),
        (p.get("PASSWORD"), _22_AC_REMOVE_ACCOUNT_password)
    ]],
    [
        AC_REMOVE_MULTISIGN_ACCOUNT, [
        (p.get("CHAINID"), _23_AC_REMOVE_MULTISIGN_ACCOUNT_chainId),
        (p.get("ADDRESS"), _23_AC_REMOVE_MULTISIGN_ACCOUNT_address)
    ]],
    [
        AC_SET_ALIAS, [
        (p.get("CHAINID"), _24_AC_SET_ALIAS_chainId),
        (p.get("ADDRESS"), _24_AC_SET_ALIAS_address),
        (p.get("PASSWORD"), _24_AC_SET_ALIAS_password),
        (p.get("ALIAS"), _24_AC_SET_ALIAS_alias)
    ]],
    [
        AC_SET_MULTISIGN_ALIAS, [
        (p.get("CHAINID"), _25_AC_SET_MULTISIGN_ALIAS_chainId),
        (p.get("ADDRESS"), _25_AC_SET_MULTISIGN_ALIAS_address),
        (p.get("ALIAS"), _25_AC_SET_MULTISIGN_ALIAS_alias),
        (p.get("SIGNADDRESS"), _25_AC_SET_MULTISIGN_ALIAS_signAddress),
        (p.get("SIGNPASSWORD"), _25_AC_SET_MULTISIGN_ALIAS_signPassword)
    ]],
    [
        AC_SET_REMARK, [
        (p.get("CHAINID"), _26_AC_SET_REMARK_chainId),
        (p.get("ADDRESS"), _26_AC_SET_REMARK_address),
        (p.get("REMARK"), _26_AC_SET_REMARK_remark)
    ]],
    [
        AC_SIGN_BLOCKDIGEST, [
        (p.get("CHAINID"), _27_AC_SIGN_BLOCKDIGEST_chainId),
        (p.get("ADDRESS"), _27_AC_SIGN_BLOCKDIGEST_address),
        (p.get("PASSWORD"), _27_AC_SIGN_BLOCKDIGEST_password),
        (p.get("DATA"), _27_AC_SIGN_BLOCKDIGEST_data)
    ]],
    [
        AC_SIGN_DIGEST, [
        (p.get("CHAINID"), _28_AC_SIGN_DIGEST_chainId),
        (p.get("ADDRESS"), _28_AC_SIGN_DIGEST_address),
        (p.get("PASSWORD"), _28_AC_SIGN_DIGEST_password),
        (p.get("DATA"), _28_AC_SIGN_DIGEST_data)
    ]],
    [
        AC_SIGN_MULTISIGN_TRANSACTION, [
        (p.get("CHAINID"), _29_AC_SIGN_MULTISIGN_TRANSACTION_chainId),
        (p.get("TX"), _29_AC_SIGN_MULTISIGN_TRANSACTION_tx),
        (p.get("SIGNADDRESS"), _29_AC_SIGN_MULTISIGN_TRANSACTION_signAddress),
        (p.get("SIGNPASSWORD"), _29_AC_SIGN_MULTISIGN_TRANSACTION_signPassword)
    ]],
    [
        AC_TRANSFER, [
        (p.get("CHAINID"), _30_AC_TRANSFER_chainId),
        (p.get("INPUTS"), _30_AC_TRANSFER_inputs),
        (p.get("OUTPUTS"), _30_AC_TRANSFER_outputs),
        (p.get("REMARK"), _30_AC_TRANSFER_remark)
    ]],
    [
        AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD, [
        (p.get("CHAINID"), _31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_chainId),
        (p.get("ADDRESS"), _31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_address),
        (p.get("PASSWORD"), _31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_password),
        (p.get("NEWPASSWORD"), _31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_newPassword),
        (p.get("PRIKEY"), _31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_priKey)
    ]],
    [
        AC_UPDATE_PASSWORD, [
        (p.get("CHAINID"), _32_AC_UPDATE_PASSWORD_chainId),
        (p.get("ADDRESS"), _32_AC_UPDATE_PASSWORD_address),
        (p.get("PASSWORD"), _32_AC_UPDATE_PASSWORD_password),
        (p.get("NEWPASSWORD"), _32_AC_UPDATE_PASSWORD_newPassword)
    ]],
    [
        AC_VALIDATION_PASSWORD, [
        (p.get("CHAINID"), _33_AC_VALIDATION_PASSWORD_chainId),
        (p.get("ADDRESS"), _33_AC_VALIDATION_PASSWORD_address),
        (p.get("PASSWORD"), _33_AC_VALIDATION_PASSWORD_password)
    ]],
    [
        AC_VERIFY_SIGN_DATA, [
        (p.get("PUBKEY"), _34_AC_VERIFY_SIGN_DATA_pubKey),
        (p.get("SIG"), _34_AC_VERIFY_SIGN_DATA_sig),
        (p.get("DATA"), _34_AC_VERIFY_SIGN_DATA_data)
    ]],
    [
        BATCH_VALIDATE_BEGIN, [
        (p.get("CHAINID"), _35_BATCH_VALIDATE_BEGIN_chainId)
    ]],
    [
        BLOCK_VALIDATE, [
        (p.get("CHAINID"), _36_BLOCK_VALIDATE_chainId),
        (p.get("TXLIST"), _36_BLOCK_VALIDATE_txList)
    ]],
    [
        CANCEL_CROSSCHAIN, [
        (p.get("CHAINID"), _38_CANCEL_CROSSCHAIN_chainId),
        (p.get("ASSETID"), _38_CANCEL_CROSSCHAIN_assetId)
    ]],
    [
        CHECK_BLOCK_VERSION, [
        (p.get("CHAINID"), _39_CHECK_BLOCK_VERSION_chainId),
        (p.get("EXTENDSDATA"), _39_CHECK_BLOCK_VERSION_extendsData)
    ]],
    [
        CM_ASSET, [
        (p.get("CHAINID"), _40_CM_ASSET_chainId),
        (p.get("ASSETID"), _40_CM_ASSET_assetId)
    ]],
    [
        CM_ASSET_CIRCULATE_COMMIT, [
        (p.get("CHAINID"), _41_CM_ASSET_CIRCULATE_COMMIT_chainId),
        (p.get("TXLIST"), _41_CM_ASSET_CIRCULATE_COMMIT_txList),
        (p.get("BLOCKHEADER"), _41_CM_ASSET_CIRCULATE_COMMIT_blockHeader)
    ]],
    [
        CM_ASSET_CIRCULATE_ROLLBACK, [
        (p.get("CHAINID"), _42_CM_ASSET_CIRCULATE_ROLLBACK_chainId),
        (p.get("TXLIST"), _42_CM_ASSET_CIRCULATE_ROLLBACK_txList),
        (p.get("BLOCKHEADER"), _42_CM_ASSET_CIRCULATE_ROLLBACK_blockHeader)
    ]],
    [
        CM_ASSET_CIRCULATE_VALIDATOR, [
        (p.get("CHAINID"), _43_CM_ASSET_CIRCULATE_VALIDATOR_chainId),
        (p.get("TX"), _43_CM_ASSET_CIRCULATE_VALIDATOR_tx)
    ]],
    [
        CM_ASSET_DISABLE, [
        (p.get("CHAINID"), _44_CM_ASSET_DISABLE_chainId),
        (p.get("ASSETID"), _44_CM_ASSET_DISABLE_assetId),
        (p.get("ADDRESS"), _44_CM_ASSET_DISABLE_address),
        (p.get("PASSWORD"), _44_CM_ASSET_DISABLE_password)
    ]],
    [
        CM_ASSET_REG, [
        (p.get("CHAINID"), _45_CM_ASSET_REG_chainId),
        (p.get("ASSETID"), _45_CM_ASSET_REG_assetId),
        (p.get("SYMBOL"), _45_CM_ASSET_REG_symbol),
        (p.get("ASSETNAME"), _45_CM_ASSET_REG_assetName),
        (p.get("INITNUMBER"), _45_CM_ASSET_REG_initNumber),
        (p.get("DECIMALPLACES"), _45_CM_ASSET_REG_decimalPlaces),
        (p.get("ADDRESS"), _45_CM_ASSET_REG_address),
        (p.get("PASSWORD"), _45_CM_ASSET_REG_password)
    ]],
    [
        CM_CHAIN, [
        (p.get("CHAINID"), _46_CM_CHAIN_chainId)
    ]],
    [
        CM_CHAIN_ACTIVE, [
        (p.get("CHAINID"), _47_CM_CHAIN_ACTIVE_chainId),
        (p.get("CHAINNAME"), _47_CM_CHAIN_ACTIVE_chainName),
        (p.get("ADDRESSTYPE"), _47_CM_CHAIN_ACTIVE_addressType),
        (p.get("ADDRESSPREFIX"), _47_CM_CHAIN_ACTIVE_addressPrefix),
        (p.get("MAGICNUMBER"), _47_CM_CHAIN_ACTIVE_magicNumber),
        (p.get("MINAVAILABLENODENUM"), _47_CM_CHAIN_ACTIVE_minAvailableNodeNum),
        (p.get("ASSETID"), _47_CM_CHAIN_ACTIVE_assetId),
        (p.get("SYMBOL"), _47_CM_CHAIN_ACTIVE_symbol),
        (p.get("ASSETNAME"), _47_CM_CHAIN_ACTIVE_assetName),
        (p.get("INITNUMBER"), _47_CM_CHAIN_ACTIVE_initNumber),
        (p.get("DECIMALPLACES"), _47_CM_CHAIN_ACTIVE_decimalPlaces),
        (p.get("ADDRESS"), _47_CM_CHAIN_ACTIVE_address),
        (p.get("PASSWORD"), _47_CM_CHAIN_ACTIVE_password),
        (p.get("VERIFIERLIST"), _47_CM_CHAIN_ACTIVE_verifierList),
        (p.get("SIGNATUREBFTRATIO"), _47_CM_CHAIN_ACTIVE_signatureBFTRatio),
        (p.get("MAXSIGNATURECOUNT"), _47_CM_CHAIN_ACTIVE_maxSignatureCount)
    ]],
    [
        CM_CHAIN_REG, [
        (p.get("CHAINID"), _48_CM_CHAIN_REG_chainId),
        (p.get("CHAINNAME"), _48_CM_CHAIN_REG_chainName),
        (p.get("ADDRESSTYPE"), _48_CM_CHAIN_REG_addressType),
        (p.get("ADDRESSPREFIX"), _48_CM_CHAIN_REG_addressPrefix),
        (p.get("MAGICNUMBER"), _48_CM_CHAIN_REG_magicNumber),
        (p.get("MINAVAILABLENODENUM"), _48_CM_CHAIN_REG_minAvailableNodeNum),
        (p.get("ASSETID"), _48_CM_CHAIN_REG_assetId),
        (p.get("SYMBOL"), _48_CM_CHAIN_REG_symbol),
        (p.get("ASSETNAME"), _48_CM_CHAIN_REG_assetName),
        (p.get("INITNUMBER"), _48_CM_CHAIN_REG_initNumber),
        (p.get("DECIMALPLACES"), _48_CM_CHAIN_REG_decimalPlaces),
        (p.get("ADDRESS"), _48_CM_CHAIN_REG_address),
        (p.get("PASSWORD"), _48_CM_CHAIN_REG_password),
        (p.get("VERIFIERLIST"), _48_CM_CHAIN_REG_verifierList),
        (p.get("SIGNATUREBFTRATIO"), _48_CM_CHAIN_REG_signatureBFTRatio),
        (p.get("MAXSIGNATURECOUNT"), _48_CM_CHAIN_REG_maxSignatureCount)
    ]],
    [
        CM_GET_CHAIN_ASSET, [
        (p.get("CHAINID"), _49_CM_GET_CHAIN_ASSET_chainId),
        (p.get("ASSETCHAINID"), _49_CM_GET_CHAIN_ASSET_assetChainId),
        (p.get("ASSETID"), _49_CM_GET_CHAIN_ASSET_assetId)
    ]],
    [
        CM_GET_CIRCULATE_CHAIN_ASSET, [
        (p.get("CIRCULATECHAINID"), _50_CM_GET_CIRCULATE_CHAIN_ASSET_circulateChainId),
        (p.get("ASSETCHAINID"), _50_CM_GET_CIRCULATE_CHAIN_ASSET_assetChainId),
        (p.get("ASSETID"), _50_CM_GET_CIRCULATE_CHAIN_ASSET_assetId)
    ]],
    [
        COMMIT_BATCH_UNCONFIRMED_TXS, [
        (p.get("CHAINID"), _51_COMMIT_BATCH_UNCONFIRMED_TXS_chainId),
        (p.get("TXLIST"), _51_COMMIT_BATCH_UNCONFIRMED_TXS_txList)
    ]],
    [
        COMMIT_BLOCKTXS, [
        (p.get("CHAINID"), _52_COMMIT_BLOCKTXS_chainId),
        (p.get("TXLIST"), _52_COMMIT_BLOCKTXS_txList),
        (p.get("BLOCKHEIGHT"), _52_COMMIT_BLOCKTXS_blockHeight)
    ]],
    [
        COMMIT_UNCONFIRMEDTX, [
        (p.get("CHAINID"), _53_COMMIT_UNCONFIRMEDTX_chainId),
        (p.get("TX"), _53_COMMIT_UNCONFIRMEDTX_tx)
    ]],
    [
        CREATE_AGENT_VALID, [
        (p.get("CHAINID"), _55_CREATE_AGENT_VALID_chainId),
        (p.get("TX"), _55_CREATE_AGENT_VALID_tx)
    ]],
    [
        CREATE_CROSSTX, [
        (p.get("CHAINID"), _56_CREATE_CROSSTX_chainId),
        (p.get("LISTFROM"), _56_CREATE_CROSSTX_listFrom),
        (p.get("LISTTO"), _56_CREATE_CROSSTX_listTo),
        (p.get("REMARK"), _56_CREATE_CROSSTX_remark)
    ]],
    [
        CROSSCHAIN_REGISTER_CHANGE, [
        (p.get("CHAINID"), _57_CROSSCHAIN_REGISTER_CHANGE_chainId)
    ]],
    [
        CS_ADD_BLOCK, [
        (p.get("CHAINID"), _58_CS_ADD_BLOCK_chainId),
        (p.get("BLOCKHEADER"), _58_CS_ADD_BLOCK_blockHeader)
    ]],
    [
        CS_ADD_EVIDENCE_RECORD, [
        (p.get("CHAINID"), _59_CS_ADD_EVIDENCE_RECORD_chainId),
        (p.get("BLOCKHEADER"), _59_CS_ADD_EVIDENCE_RECORD_blockHeader),
        (p.get("EVIDENCEHEADER"), _59_CS_ADD_EVIDENCE_RECORD_evidenceHeader)
    ]],
    [
        CS_CHAIN_ROLLBACK, [
        (p.get("CHAINID"), _60_CS_CHAIN_ROLLBACK_chainId),
        (p.get("HEIGHT"), _60_CS_CHAIN_ROLLBACK_height)
    ]],
    [
        CS_CONTRACT_DEPOSIT, [
        (p.get("CHAINID"), _61_CS_CONTRACT_DEPOSIT_chainId),
        (p.get("AGENTHASH"), _61_CS_CONTRACT_DEPOSIT_agentHash),
        (p.get("DEPOSIT"), _61_CS_CONTRACT_DEPOSIT_deposit),
        (p.get("CONTRACTADDRESS"), _61_CS_CONTRACT_DEPOSIT_contractAddress),
        (p.get("CONTRACTSENDER"), _61_CS_CONTRACT_DEPOSIT_contractSender),
        (p.get("CONTRACTBALANCE"), _61_CS_CONTRACT_DEPOSIT_contractBalance),
        (p.get("CONTRACTNONCE"), _61_CS_CONTRACT_DEPOSIT_contractNonce),
        (p.get("BLOCKTIME"), _61_CS_CONTRACT_DEPOSIT_blockTime)
    ]],
    [
        CS_CONTRACT_WITHDRAW, [
        (p.get("CHAINID"), _62_CS_CONTRACT_WITHDRAW_chainId),
        (p.get("JOINAGENTHASH"), _62_CS_CONTRACT_WITHDRAW_joinAgentHash),
        (p.get("CONTRACTADDRESS"), _62_CS_CONTRACT_WITHDRAW_contractAddress),
        (p.get("CONTRACTSENDER"), _62_CS_CONTRACT_WITHDRAW_contractSender),
        (p.get("CONTRACTBALANCE"), _62_CS_CONTRACT_WITHDRAW_contractBalance),
        (p.get("CONTRACTNONCE"), _62_CS_CONTRACT_WITHDRAW_contractNonce),
        (p.get("BLOCKTIME"), _62_CS_CONTRACT_WITHDRAW_blockTime)
    ]],
    [
        CS_CREATE_AGENT, [
        (p.get("CHAINID"), _63_CS_CREATE_AGENT_chainId),
        (p.get("AGENTADDRESS"), _63_CS_CREATE_AGENT_agentAddress),
        (p.get("PACKINGADDRESS"), _63_CS_CREATE_AGENT_packingAddress),
        (p.get("REWARDADDRESS"), _63_CS_CREATE_AGENT_rewardAddress),
        (p.get("COMMISSIONRATE"), _63_CS_CREATE_AGENT_commissionRate),
        (p.get("DEPOSIT"), _63_CS_CREATE_AGENT_deposit),
        (p.get("PASSWORD"), _63_CS_CREATE_AGENT_password)
    ]],
    [
        CS_CREATE_CONTRACT_AGENT, [
        (p.get("CHAINID"), _64_CS_CREATE_CONTRACT_AGENT_chainId),
        (p.get("PACKINGADDRESS"), _64_CS_CREATE_CONTRACT_AGENT_packingAddress),
        (p.get("DEPOSIT"), _64_CS_CREATE_CONTRACT_AGENT_deposit),
        (p.get("COMMISSIONRATE"), _64_CS_CREATE_CONTRACT_AGENT_commissionRate),
        (p.get("CONTRACTADDRESS"), _64_CS_CREATE_CONTRACT_AGENT_contractAddress),
        (p.get("CONTRACTSENDER"), _64_CS_CREATE_CONTRACT_AGENT_contractSender),
        (p.get("CONTRACTBALANCE"), _64_CS_CREATE_CONTRACT_AGENT_contractBalance),
        (p.get("CONTRACTNONCE"), _64_CS_CREATE_CONTRACT_AGENT_contractNonce),
        (p.get("BLOCKTIME"), _64_CS_CREATE_CONTRACT_AGENT_blockTime)
    ]],
    [
        CS_CREATE_MULTI_AGENT, [
        (p.get("CHAINID"), _65_CS_CREATE_MULTI_AGENT_chainId),
        (p.get("AGENTADDRESS"), _65_CS_CREATE_MULTI_AGENT_agentAddress),
        (p.get("PACKINGADDRESS"), _65_CS_CREATE_MULTI_AGENT_packingAddress),
        (p.get("REWARDADDRESS"), _65_CS_CREATE_MULTI_AGENT_rewardAddress),
        (p.get("COMMISSIONRATE"), _65_CS_CREATE_MULTI_AGENT_commissionRate),
        (p.get("DEPOSIT"), _65_CS_CREATE_MULTI_AGENT_deposit),
        (p.get("PASSWORD"), _65_CS_CREATE_MULTI_AGENT_password),
        (p.get("SIGNADDRESS"), _65_CS_CREATE_MULTI_AGENT_signAddress)
    ]],
    [
        CS_DEPOSIT_TOAGENT, [
        (p.get("CHAINID"), _66_CS_DEPOSIT_TOAGENT_chainId),
        (p.get("ADDRESS"), _66_CS_DEPOSIT_TOAGENT_address),
        (p.get("AGENTHASH"), _66_CS_DEPOSIT_TOAGENT_agentHash),
        (p.get("DEPOSIT"), _66_CS_DEPOSIT_TOAGENT_deposit),
        (p.get("PASSWORD"), _66_CS_DEPOSIT_TOAGENT_password)
    ]],
    [
        CS_DOUBLE_SPEND_RECORD, [
        (p.get("CHAINID"), _67_CS_DOUBLE_SPEND_RECORD_chainId),
        (p.get("BLOCK"), _67_CS_DOUBLE_SPEND_RECORD_block),
        (p.get("TX"), _67_CS_DOUBLE_SPEND_RECORD_tx)
    ]],
    [
        CS_GET_AGENT_ADDRESS_LIST, [
        (p.get("CHAINID"), _68_CS_GET_AGENT_ADDRESS_LIST_chainId)
    ]],
    [
        CS_GET_AGENT_CHANGE_INFO, [
        (p.get("CHAINID"), _69_CS_GET_AGENT_CHANGE_INFO_chainId)
    ]],
    [
        CS_GET_AGENT_INFO, [
        (p.get("CHAINID"), _70_CS_GET_AGENT_INFO_chainId),
        (p.get("AGENTHASH"), _70_CS_GET_AGENT_INFO_agentHash)
    ]],
    [
        CS_GET_AGENT_LIST, [
        (p.get("CHAINID"), _71_CS_GET_AGENT_LIST_chainId),
        (p.get("PAGENUMBER"), _71_CS_GET_AGENT_LIST_pageNumber),
        (p.get("PAGESIZE"), _71_CS_GET_AGENT_LIST_pageSize),
        (p.get("KEYWORD"), _71_CS_GET_AGENT_LIST_keyWord)
    ]],
    [
        CS_GET_AGENT_STATUS, [
        (p.get("CHAINID"), _72_CS_GET_AGENT_STATUS_chainId),
        (p.get("AGENTHASH"), _72_CS_GET_AGENT_STATUS_agentHash)
    ]],
    [
        CS_GET_CONSENSUS_CONFIG, [
        (p.get("CHAINID"), _73_CS_GET_CONSENSUS_CONFIG_chainId)
    ]],
    [
        CS_GET_CONTRACT_AGENT_INFO, [
        (p.get("CHAINID"), _74_CS_GET_CONTRACT_AGENT_INFO_chainId),
        (p.get("AGENTHASH"), _74_CS_GET_CONTRACT_AGENT_INFO_agentHash),
        (p.get("CONTRACTADDRESS"), _74_CS_GET_CONTRACT_AGENT_INFO_contractAddress),
        (p.get("CONTRACTSENDER"), _74_CS_GET_CONTRACT_AGENT_INFO_contractSender)
    ]],
    [
        CS_GET_CONTRACT_DEPOSIT_INFO, [
        (p.get("CHAINID"), _75_CS_GET_CONTRACT_DEPOSIT_INFO_chainId),
        (p.get("JOINAGENTHASH"), _75_CS_GET_CONTRACT_DEPOSIT_INFO_joinAgentHash),
        (p.get("CONTRACTADDRESS"), _75_CS_GET_CONTRACT_DEPOSIT_INFO_contractAddress),
        (p.get("CONTRACTSENDER"), _75_CS_GET_CONTRACT_DEPOSIT_INFO_contractSender)
    ]],
    [
        CS_GET_DEPOSIT_LIST, [
        (p.get("CHAINID"), _76_CS_GET_DEPOSIT_LIST_chainId),
        (p.get("PAGENUMBER"), _76_CS_GET_DEPOSIT_LIST_pageNumber),
        (p.get("PAGESIZE"), _76_CS_GET_DEPOSIT_LIST_pageSize),
        (p.get("ADDRESS"), _76_CS_GET_DEPOSIT_LIST_address),
        (p.get("AGENTHASH"), _76_CS_GET_DEPOSIT_LIST_agentHash)
    ]],
    [
        CS_GET_INFO, [
        (p.get("CHAINID"), _77_CS_GET_INFO_chainId),
        (p.get("ADDRESS"), _77_CS_GET_INFO_address)
    ]],
    [
        CS_GET_PACKER_INFO, [
        (p.get("CHAINID"), _78_CS_GET_PACKER_INFO_chainId)
    ]],
    [
        CS_GET_PUBLISH_LIST, [
        (p.get("CHAINID"), _79_CS_GET_PUBLISH_LIST_chainId),
        (p.get("ADDRESS"), _79_CS_GET_PUBLISH_LIST_address),
        (p.get("TYPE"), _79_CS_GET_PUBLISH_LIST_type)
    ]],
    [
        CS_GET_ROUND_INFO, [
        (p.get("CHAINID"), _80_CS_GET_ROUND_INFO_chainId)
    ]],
    [
        CS_GET_ROUND_MEMBER_LIST, [
        (p.get("CHAINID"), _81_CS_GET_ROUND_MEMBER_LIST_chainId),
        (p.get("EXTEND"), _81_CS_GET_ROUND_MEMBER_LIST_extend)
    ]],
    [
        CS_GET_SEED_NODE_INFO, [
        (p.get("CHAINID"), _82_CS_GET_SEED_NODE_INFO_chainId)
    ]],
    [
        CS_GET_WHOLEINFO, [
        (p.get("CHAINID"), _83_CS_GET_WHOLEINFO_chainId)
    ]],
    [
        CS_MULTI_DEPOSIT, [
        (p.get("CHAINID"), _84_CS_MULTI_DEPOSIT_chainId),
        (p.get("ADDRESS"), _84_CS_MULTI_DEPOSIT_address),
        (p.get("AGENTHASH"), _84_CS_MULTI_DEPOSIT_agentHash),
        (p.get("DEPOSIT"), _84_CS_MULTI_DEPOSIT_deposit),
        (p.get("PASSWORD"), _84_CS_MULTI_DEPOSIT_password),
        (p.get("SIGNADDRESS"), _84_CS_MULTI_DEPOSIT_signAddress)
    ]],
    [
        CS_MULTI_WITHDRAW, [
        (p.get("CHAINID"), _85_CS_MULTI_WITHDRAW_chainId),
        (p.get("ADDRESS"), _85_CS_MULTI_WITHDRAW_address),
        (p.get("TXHASH"), _85_CS_MULTI_WITHDRAW_txHash),
        (p.get("PASSWORD"), _85_CS_MULTI_WITHDRAW_password),
        (p.get("SIGNADDRESS"), _85_CS_MULTI_WITHDRAW_signAddress)
    ]],
    [
        CS_RANDOM_RAW_SEEDS_COUNT, [
        (p.get("CHAINID"), _86_CS_RANDOM_RAW_SEEDS_COUNT_chainId),
        (p.get("HEIGHT"), _86_CS_RANDOM_RAW_SEEDS_COUNT_height),
        (p.get("COUNT"), _86_CS_RANDOM_RAW_SEEDS_COUNT_count)
    ]],
    [
        CS_RANDOM_RAW_SEEDS_HEIGHT, [
        (p.get("CHAINID"), _87_CS_RANDOM_RAW_SEEDS_HEIGHT_chainId),
        (p.get("STARTHEIGHT"), _87_CS_RANDOM_RAW_SEEDS_HEIGHT_startHeight),
        (p.get("ENDHEIGHT"), _87_CS_RANDOM_RAW_SEEDS_HEIGHT_endHeight)
    ]],
    [
        CS_RANDOM_SEED_COUNT, [
        (p.get("CHAINID"), _88_CS_RANDOM_SEED_COUNT_chainId),
        (p.get("HEIGHT"), _88_CS_RANDOM_SEED_COUNT_height),
        (p.get("COUNT"), _88_CS_RANDOM_SEED_COUNT_count),
        (p.get("ALGORITHM"), _88_CS_RANDOM_SEED_COUNT_algorithm)
    ]],
    [
        CS_RANDOM_SEED_HEIGHT, [
        (p.get("CHAINID"), _89_CS_RANDOM_SEED_HEIGHT_chainId),
        (p.get("STARTHEIGHT"), _89_CS_RANDOM_SEED_HEIGHT_startHeight),
        (p.get("ENDHEIGHT"), _89_CS_RANDOM_SEED_HEIGHT_endHeight),
        (p.get("ALGORITHM"), _89_CS_RANDOM_SEED_HEIGHT_algorithm)
    ]],
    [
        CS_RECEIVE_HEADERLIST, [
        (p.get("CHAINID"), _90_CS_RECEIVE_HEADERLIST_chainId),
        (p.get("HEADERLIST"), _90_CS_RECEIVE_HEADERLIST_headerList)
    ]],
    [
        CS_RUN_CHAIN, [
        (p.get("CHAINID"), _91_CS_RUN_CHAIN_chainId)
    ]],
    [
        CS_RUN_MAINCHAIN, [
        (p.get("CHAINID"), _92_CS_RUN_MAINCHAIN_chainId)
    ]],
    [
        CS_STOPAGENT, [
        (p.get("CHAINID"), _93_CS_STOPAGENT_chainId),
        (p.get("ADDRESS"), _93_CS_STOPAGENT_address),
        (p.get("PASSWORD"), _93_CS_STOPAGENT_password)
    ]],
    [
        CS_STOP_AGENT, [
        (p.get("CHAINID"), _94_CS_STOP_AGENT_chainId),
        (p.get("ADDRESS"), _94_CS_STOP_AGENT_address),
        (p.get("PASSWORD"), _94_CS_STOP_AGENT_password)
    ]],
    [
        CS_STOPCHAIN, [
        (p.get("CHAINID"), _95_CS_STOPCHAIN_chainId)
    ]],
    [
        CS_STOP_CHAIN, [
        (p.get("CHAINID"), _96_CS_STOP_CHAIN_chainId)
    ]],
    [
        CS_STOP_CONTRACT_AGENT, [
        (p.get("CHAINID"), _97_CS_STOP_CONTRACT_AGENT_chainId),
        (p.get("CONTRACTADDRESS"), _97_CS_STOP_CONTRACT_AGENT_contractAddress),
        (p.get("CONTRACTSENDER"), _97_CS_STOP_CONTRACT_AGENT_contractSender),
        (p.get("CONTRACTBALANCE"), _97_CS_STOP_CONTRACT_AGENT_contractBalance),
        (p.get("CONTRACTNONCE"), _97_CS_STOP_CONTRACT_AGENT_contractNonce),
        (p.get("BLOCKTIME"), _97_CS_STOP_CONTRACT_AGENT_blockTime)
    ]],
    [
        CS_STOP_MULTI_AGENT, [
        (p.get("CHAINID"), _98_CS_STOP_MULTI_AGENT_chainId),
        (p.get("ADDRESS"), _98_CS_STOP_MULTI_AGENT_address),
        (p.get("PASSWORD"), _98_CS_STOP_MULTI_AGENT_password),
        (p.get("SIGNADDRESS"), _98_CS_STOP_MULTI_AGENT_signAddress)
    ]],
    [
        CS_TRIGGER_COINBASE_CONTRACT, [
        (p.get("CHAINID"), _99_CS_TRIGGER_COINBASE_CONTRACT_chainId),
        (p.get("TX"), _99_CS_TRIGGER_COINBASE_CONTRACT_tx),
        (p.get("BLOCKHEADER"), _99_CS_TRIGGER_COINBASE_CONTRACT_blockHeader),
        (p.get("STATEROOT"), _99_CS_TRIGGER_COINBASE_CONTRACT_stateRoot)
    ]],
    [
        CS_UPDATE_AGENT_CONSENSUS_STATUS, [
        (p.get("CHAINID"), _100_CS_UPDATE_AGENT_CONSENSUS_STATUS_chainId)
    ]],
    [
        CS_UPDATE_AGENT_STATUS, [
        (p.get("CHAINID"), _101_CS_UPDATE_AGENT_STATUS_chainId),
        (p.get("STATUS"), _101_CS_UPDATE_AGENT_STATUS_status)
    ]],
    [
        CS_VALIDBLOCK, [
        (p.get("CHAINID"), _102_CS_VALIDBLOCK_chainId),
        (p.get("DOWNLOAD"), _102_CS_VALIDBLOCK_download),
        (p.get("BLOCK"), _102_CS_VALIDBLOCK_block)
    ]],
    [
        CS_WITHDRAW, [
        (p.get("CHAINID"), _103_CS_WITHDRAW_chainId),
        (p.get("ADDRESS"), _103_CS_WITHDRAW_address),
        (p.get("TXHASH"), _103_CS_WITHDRAW_txHash),
        (p.get("PASSWORD"), _103_CS_WITHDRAW_password)
    ]],
    [
        DEPOSIT_VALID, [
        (p.get("CHAINID"), _104_DEPOSIT_VALID_chainId),
        (p.get("TX"), _104_DEPOSIT_VALID_tx)
    ]],
    [
        GET_ASSETS_BY_ID, [
        (p.get("CHAINID"), _105_GET_ASSETS_BY_ID_chainId),
        (p.get("ASSETIDS"), _105_GET_ASSETS_BY_ID_assetIds)
    ]],
    [
        GET_BALANCE, [
        (p.get("CHAINID"), _106_GET_BALANCE_chainId),
        (p.get("ASSETCHAINID"), _106_GET_BALANCE_assetChainId),
        (p.get("ASSETID"), _106_GET_BALANCE_assetId),
        (p.get("ADDRESS"), _106_GET_BALANCE_address)
    ]],
    [
        GET_BALANCE_NONCE, [
        (p.get("CHAINID"), _107_GET_BALANCE_NONCE_chainId),
        (p.get("ASSETCHAINID"), _107_GET_BALANCE_NONCE_assetChainId),
        (p.get("ASSETID"), _107_GET_BALANCE_NONCE_assetId),
        (p.get("ADDRESS"), _107_GET_BALANCE_NONCE_address),
        (p.get("ISCONFIRMED"), _107_GET_BALANCE_NONCE_isConfirmed)
    ]],
    [
        GET_BLOCK_BY_HASH, [
        (p.get("CHAINID"), _108_GET_BLOCK_BY_HASH_chainId),
        (p.get("HASH"), _108_GET_BLOCK_BY_HASH_hash)
    ]],
    [
        GET_BLOCK_BY_HEIGHT, [
        (p.get("CHAINID"), _109_GET_BLOCK_BY_HEIGHT_chainId),
        (p.get("HEIGHT"), _109_GET_BLOCK_BY_HEIGHT_height)
    ]],
    [
        GET_BLOCKHEADER_BY_HASH, [
        (p.get("CHAINID"), _110_GET_BLOCKHEADER_BY_HASH_chainId),
        (p.get("HASH"), _110_GET_BLOCKHEADER_BY_HASH_hash)
    ]],
    [
        GET_BLOCKHEADER_BY_HEIGHT, [
        (p.get("CHAINID"), _111_GET_BLOCKHEADER_BY_HEIGHT_chainId),
        (p.get("HEIGHT"), _111_GET_BLOCKHEADER_BY_HEIGHT_height)
    ]],
    [
        GET_BLOCKHEADER_PO_BY_HASH, [
        (p.get("CHAINID"), _112_GET_BLOCKHEADER_PO_BY_HASH_chainId),
        (p.get("HASH"), _112_GET_BLOCKHEADER_PO_BY_HASH_hash)
    ]],
    [
        GET_BLOCKHEADER_POBY_HEIGHT, [
        (p.get("CHAINID"), _113_GET_BLOCKHEADER_POBY_HEIGHT_chainId),
        (p.get("HEIGHT"), _113_GET_BLOCKHEADER_POBY_HEIGHT_height)
    ]],
    [
        GET_BLOCKHEADERS_BY_HEIGHT_RANGE, [
        (p.get("CHAINID"), _114_GET_BLOCKHEADERS_BY_HEIGHT_RANGE_chainId),
        (p.get("BEGIN"), _114_GET_BLOCKHEADERS_BY_HEIGHT_RANGE_begin),
        (p.get("END"), _114_GET_BLOCKHEADERS_BY_HEIGHT_RANGE_end)
    ]],
    [
        GET_BLOCKHEADERS_FOR_PROTOCOL, [
        (p.get("CHAINID"), _115_GET_BLOCKHEADERS_FOR_PROTOCOL_chainId),
        (p.get("INTERVAL"), _115_GET_BLOCKHEADERS_FOR_PROTOCOL_interval)
    ]],
    [
        GET_BYZANTINE_COUNT, [
        (p.get("CHAINID"), _116_GET_BYZANTINE_COUNT_chainId)
    ]],
    [
        GET_CIRCULAT, [
        (p.get("CHAINID"), _117_GET_CIRCULAT_chainId),
        (p.get("NODEID"), _117_GET_CIRCULAT_nodeId),
        (p.get("MESSAGEBODY"), _117_GET_CIRCULAT_messageBody)
    ]],
    [
        GET_CROSSTX_STATE, [
        (p.get("CHAINID"), _119_GET_CROSSTX_STATE_chainId),
        (p.get("TXHASH"), _119_GET_CROSSTX_STATE_txHash)
    ]],
    [
        GET_CTX, [
        (p.get("CHAINID"), _120_GET_CTX_chainId),
        (p.get("NODEID"), _120_GET_CTX_nodeId),
        (p.get("MESSAGEBODY"), _120_GET_CTX_messageBody)
    ]],
    [
        GET_CTX_STATE, [
        (p.get("CHAINID"), _121_GET_CTX_STATE_chainId),
        (p.get("NODEID"), _121_GET_CTX_STATE_nodeId),
        (p.get("MESSAGEBODY"), _121_GET_CTX_STATE_messageBody)
    ]],
    [
        GET_FRIEND_CHAIN_CIRCULATE, [
        (p.get("CHAINID"), _122_GET_FRIEND_CHAIN_CIRCULATE_chainId),
        (p.get("ASSETIDS"), _122_GET_FRIEND_CHAIN_CIRCULATE_assetIds)
    ]],
    [
        GET_LATEST_BLOCKHEADERS, [
        (p.get("CHAINID"), _123_GET_LATEST_BLOCKHEADERS_chainId),
        (p.get("SIZE"), _123_GET_LATEST_BLOCKHEADERS_size)
    ]],
    [
        GET_LATEST_ROUND_BLOCKHEADERS, [
        (p.get("CHAINID"), _124_GET_LATEST_ROUND_BLOCKHEADERS_chainId),
        (p.get("ROUND"), _124_GET_LATEST_ROUND_BLOCKHEADERS_round)
    ]],
    [
        GET_NONCE, [
        (p.get("CHAINID"), _125_GET_NONCE_chainId),
        (p.get("ASSETCHAINID"), _125_GET_NONCE_assetChainId),
        (p.get("ASSETID"), _125_GET_NONCE_assetId),
        (p.get("ADDRESS"), _125_GET_NONCE_address),
        (p.get("ISCONFIRMED"), _125_GET_NONCE_isConfirmed)
    ]],
    [
        GET_OTHERCTX, [
        (p.get("CHAINID"), _126_GET_OTHERCTX_chainId),
        (p.get("NODEID"), _126_GET_OTHERCTX_nodeId),
        (p.get("MESSAGEBODY"), _126_GET_OTHERCTX_messageBody)
    ]],
    [
        GET_ROUND_BLOCKHEADERS, [
        (p.get("CHAINID"), _128_GET_ROUND_BLOCKHEADERS_chainId),
        (p.get("HEIGHT"), _128_GET_ROUND_BLOCKHEADERS_height),
        (p.get("ROUND"), _128_GET_ROUND_BLOCKHEADERS_round)
    ]],
    [
        GET_STATUS, [
        (p.get("CHAINID"), _129_GET_STATUS_chainId)
    ]],
    [
        GET_VERSION, [
        (p.get("CHAINID"), _130_GET_VERSION_chainId)
    ]],
    [
        INFO, [
        (p.get("CHAINID"), _131_INFO_chainId)
    ]],
    [
        LATEST_BLOCK, [
        (p.get("CHAINID"), _132_LATEST_BLOCK_chainId)
    ]],
    [
        LATEST_BLOCKHEADER, [
        (p.get("CHAINID"), _133_LATEST_BLOCKHEADER_chainId)
    ]],
    [
        LATEST_BLOCKHEADER_PO, [
        (p.get("CHAINID"), _134_LATEST_BLOCKHEADER_PO_chainId)
    ]],
    [
        LATEST_HEIGHT, [
        (p.get("CHAINID"), _135_LATEST_HEIGHT_chainId)
    ]],
    [
        MSG_PROCESS, [
        (p.get("CHAINID"), _137_MSG_PROCESS_chainId),
        (p.get("NODEID"), _137_MSG_PROCESS_nodeId),
        (p.get("CMD"), _137_MSG_PROCESS_cmd),
        (p.get("MESSAGEBODY"), _137_MSG_PROCESS_messageBody)
    ]],
    [
        NEW_BLOCK_HEIGHT, [
        (p.get("CHAINID"), _138_NEW_BLOCK_HEIGHT_chainId),
        (p.get("HEIGHT"), _138_NEW_BLOCK_HEIGHT_height)
    ]],
    [
        NW_ACTIVE_CROSS, [
        (p.get("CHAINID"), _139_NW_ACTIVE_CROSS_chainId),
        (p.get("MAXOUT"), _139_NW_ACTIVE_CROSS_maxOut),
        (p.get("MAXIN"), _139_NW_ACTIVE_CROSS_maxIn),
        (p.get("SEEDIPS"), _139_NW_ACTIVE_CROSS_seedIps)
    ]],
    [
        NW_ADD_NODES, [
        (p.get("CHAINID"), _140_NW_ADD_NODES_chainId),
        (p.get("ISCROSS"), _140_NW_ADD_NODES_isCross),
        (p.get("NODES"), _140_NW_ADD_NODES_nodes)
    ]],
    [
        NW_BROADCAST, [
        (p.get("CHAINID"), _141_NW_BROADCAST_chainId),
        (p.get("EXCLUDENODES"), _141_NW_BROADCAST_excludeNodes),
        (p.get("MESSAGEBODY"), _141_NW_BROADCAST_messageBody),
        (p.get("COMMAND"), _141_NW_BROADCAST_command),
        (p.get("ISCROSS"), _141_NW_BROADCAST_isCross),
        (p.get("PERCENT"), _141_NW_BROADCAST_percent)
    ]],
    [
        NW_CREATE_NODEGROUP, [
        (p.get("CHAINID"), _142_NW_CREATE_NODEGROUP_chainId),
        (p.get("MAGICNUMBER"), _142_NW_CREATE_NODEGROUP_magicNumber),
        (p.get("MAXOUT"), _142_NW_CREATE_NODEGROUP_maxOut),
        (p.get("MAXIN"), _142_NW_CREATE_NODEGROUP_maxIn),
        (p.get("MINAVAILABLECOUNT"), _142_NW_CREATE_NODEGROUP_minAvailableCount),
        (p.get("ISCROSSGROUP"), _142_NW_CREATE_NODEGROUP_isCrossGroup)
    ]],
    [
        NW_DEL_NODES, [
        (p.get("CHAINID"), _143_NW_DEL_NODES_chainId),
        (p.get("NODES"), _143_NW_DEL_NODES_nodes)
    ]],
    [
        NW_GET_CHAIN_CONNECT_AMOUNT, [
        (p.get("CHAINID"), _144_NW_GET_CHAIN_CONNECT_AMOUNT_chainId),
        (p.get("ISCROSS"), _144_NW_GET_CHAIN_CONNECT_AMOUNT_isCross)
    ]],
    [
        NW_GET_GROUP_BY_CHAINID, [
        (p.get("CHAINID"), _145_NW_GET_GROUP_BY_CHAINID_chainId)
    ]],
    [
        NW_GET_GROUPS, [
        (p.get("STARTPAGE"), _146_NW_GET_GROUPS_startPage),
        (p.get("PAGESIZE"), _146_NW_GET_GROUPS_pageSize)
    ]],
    [
        NW_GET_NODES, [
        (p.get("CHAINID"), _147_NW_GET_NODES_chainId),
        (p.get("STATE"), _147_NW_GET_NODES_state),
        (p.get("ISCROSS"), _147_NW_GET_NODES_isCross),
        (p.get("STARTPAGE"), _147_NW_GET_NODES_startPage),
        (p.get("PAGESIZE"), _147_NW_GET_NODES_pageSize)
    ]],
    [
        NW_INFO, [
        (p.get("CHAINID"), _149_NW_INFO_chainId)
    ]],
    [
        NW_NODES, [
        (p.get("CHAINID"), _150_NW_NODES_chainId)
    ]],
    [
        NW_PROTOCOL_REGISTER, [
        (p.get("ROLE"), _151_NW_PROTOCOL_REGISTER_role),
        (p.get("PROTOCOLCMDS"), _151_NW_PROTOCOL_REGISTER_protocolCmds)
    ]],
    [
        NW_RECONNECT, [
        (p.get("CHAINID"), _152_NW_RECONNECT_chainId)
    ]],
    [
        NW_SEND_PEERS_MSG, [
        (p.get("CHAINID"), _153_NW_SEND_PEERS_MSG_chainId),
        (p.get("NODES"), _153_NW_SEND_PEERS_MSG_nodes),
        (p.get("MESSAGEBODY"), _153_NW_SEND_PEERS_MSG_messageBody),
        (p.get("COMMAND"), _153_NW_SEND_PEERS_MSG_command)
    ]],
    [
        NW_UPDATE_NODE_INFO, [
        (p.get("CHAINID"), _154_NW_UPDATE_NODE_INFO_chainId),
        (p.get("NODEID"), _154_NW_UPDATE_NODE_INFO_nodeId),
        (p.get("BLOCKHEIGHT"), _154_NW_UPDATE_NODE_INFO_blockHeight),
        (p.get("BLOCKHASH"), _154_NW_UPDATE_NODE_INFO_blockHash)
    ]],
    [
        PARAM_TEST_CMD, [
        (p.get("INTCOUNT"), _155_PARAM_TEST_CMD_intCount),
        (p.get("BYTECOUNT"), _155_PARAM_TEST_CMD_byteCount),
        (p.get("SHORTCOUNT"), _155_PARAM_TEST_CMD_shortCount),
        (p.get("LONGCOUNT"), _155_PARAM_TEST_CMD_longCount)
    ]],
    [
        PROTOCOL_VERSION_CHANGE, [
        (p.get("CHAINID"), _156_PROTOCOL_VERSION_CHANGE_chainId),
        (p.get("PROTOCOLVERSION"), _156_PROTOCOL_VERSION_CHANGE_protocolVersion)
    ]],
    [
        RECEIVE_PACKING_BLOCK, [
        (p.get("CHAINID"), _157_RECEIVE_PACKING_BLOCK_chainId),
        (p.get("BLOCK"), _157_RECEIVE_PACKING_BLOCK_block)
    ]],
    [
        RECV_CIRCULAT, [
        (p.get("CHAINID"), _158_RECV_CIRCULAT_chainId),
        (p.get("NODEID"), _158_RECV_CIRCULAT_nodeId),
        (p.get("MESSAGEBODY"), _158_RECV_CIRCULAT_messageBody)
    ]],
    [
        RECV_CTX, [
        (p.get("CHAINID"), _159_RECV_CTX_chainId),
        (p.get("NODEID"), _159_RECV_CTX_nodeId),
        (p.get("MESSAGEBODY"), _159_RECV_CTX_messageBody)
    ]],
    [
        RECV_CTX_HASH, [
        (p.get("CHAINID"), _160_RECV_CTX_HASH_chainId),
        (p.get("NODEID"), _160_RECV_CTX_HASH_nodeId),
        (p.get("MESSAGEBODY"), _160_RECV_CTX_HASH_messageBody)
    ]],
    [
        RECV_CTX_SIGN, [
        (p.get("CHAINID"), _161_RECV_CTX_SIGN_chainId),
        (p.get("NODEID"), _161_RECV_CTX_SIGN_nodeId),
        (p.get("MESSAGEBODY"), _161_RECV_CTX_SIGN_messageBody)
    ]],
    [
        RECV_CTX_STATE, [
        (p.get("CHAINID"), _162_RECV_CTX_STATE_chainId),
        (p.get("NODEID"), _162_RECV_CTX_STATE_nodeId),
        (p.get("MESSAGEBODY"), _162_RECV_CTX_STATE_messageBody)
    ]],
    [
        RECV_OTHER_CTX, [
        (p.get("CHAINID"), _163_RECV_OTHER_CTX_chainId),
        (p.get("NODEID"), _163_RECV_OTHER_CTX_nodeId),
        (p.get("MESSAGEBODY"), _163_RECV_OTHER_CTX_messageBody)
    ]],
    [
        RECV_REGCHAIN, [
        (p.get("CHAINID"), _164_RECV_REGCHAIN_chainId),
        (p.get("NODEID"), _164_RECV_REGCHAIN_nodeId),
        (p.get("MESSAGEBODY"), _164_RECV_REGCHAIN_messageBody)
    ]],
    [
        REGISTER_PROTOCOL, [
        (p.get("CHAINID"), _166_REGISTER_PROTOCOL_chainId),
        (p.get("MODULECODE"), _166_REGISTER_PROTOCOL_moduleCode),
        (p.get("LIST"), _166_REGISTER_PROTOCOL_list)
    ]],
    [
        ROLLBACK_BLOCK_TXS, [
        (p.get("CHAINID"), _167_ROLLBACK_BLOCK_TXS_chainId),
        (p.get("TXLIST"), _167_ROLLBACK_BLOCK_TXS_txList),
        (p.get("BLOCKHEIGHT"), _167_ROLLBACK_BLOCK_TXS_blockHeight)
    ]],
    [
        ROLLBACK_UNCONFIRM_TX, [
        (p.get("CHAINID"), _168_ROLLBACK_UNCONFIRM_TX_chainId),
        (p.get("TX"), _168_ROLLBACK_UNCONFIRM_TX_tx)
    ]],
    [
        ROLLBACK_BLOCK, [
        (p.get("CHAINID"), _169_ROLLBACK_BLOCK_chainId),
        (p.get("BLOCKHEADER"), _169_ROLLBACK_BLOCK_blockHeader)
    ]],
    [
        ROLLBACK_TX_VALIDATE_STATUS, [
        (p.get("CHAINID"), _170_ROLLBACK_TX_VALIDATE_STATUS_chainId),
        (p.get("TX"), _170_ROLLBACK_TX_VALIDATE_STATUS_tx)
    ]],
    [
        SAVE_BLOCK, [
        (p.get("CHAINID"), _171_SAVE_BLOCK_chainId),
        (p.get("BLOCKHEADER"), _171_SAVE_BLOCK_blockHeader)
    ]],
    [
        SC_BATCH_BEFORE_END, [
        (p.get("CHAINID"), _172_SC_BATCH_BEFORE_END_chainId),
        (p.get("BLOCKTYPE"), _172_SC_BATCH_BEFORE_END_blockType),
        (p.get("BLOCKHEIGHT"), _172_SC_BATCH_BEFORE_END_blockHeight)
    ]],
    [
        SC_BATCH_BEGIN, [
        (p.get("CHAINID"), _173_SC_BATCH_BEGIN_chainId),
        (p.get("BLOCKTYPE"), _173_SC_BATCH_BEGIN_blockType),
        (p.get("BLOCKHEIGHT"), _173_SC_BATCH_BEGIN_blockHeight),
        (p.get("BLOCKTIME"), _173_SC_BATCH_BEGIN_blockTime),
        (p.get("PACKINGADDRESS"), _173_SC_BATCH_BEGIN_packingAddress),
        (p.get("PRESTATEROOT"), _173_SC_BATCH_BEGIN_preStateRoot)
    ]],
    [
        SC_BATCH_END, [
        (p.get("CHAINID"), _174_SC_BATCH_END_chainId),
        (p.get("BLOCKHEIGHT"), _174_SC_BATCH_END_blockHeight)
    ]],
    [
        SC_CALL, [
        (p.get("CHAINID"), _175_SC_CALL_chainId),
        (p.get("SENDER"), _175_SC_CALL_sender),
        (p.get("PASSWORD"), _175_SC_CALL_password),
        (p.get("VALUE"), _175_SC_CALL_value),
        (p.get("GASLIMIT"), _175_SC_CALL_gasLimit),
        (p.get("PRICE"), _175_SC_CALL_price),
        (p.get("CONTRACTADDRESS"), _175_SC_CALL_contractAddress),
        (p.get("METHODNAME"), _175_SC_CALL_methodName),
        (p.get("METHODDESC"), _175_SC_CALL_methodDesc),
        (p.get("ARGS"), _175_SC_CALL_args),
        (p.get("REMARK"), _175_SC_CALL_remark)
    ]],
    [
        SC_CALL_VALIDATOR, [
        (p.get("CHAINID"), _176_SC_CALL_VALIDATOR_chainId),
        (p.get("TX"), _176_SC_CALL_VALIDATOR_tx)
    ]],
    [
        SC_CONSTRUCTOR, [
        (p.get("CHAINID"), _177_SC_CONSTRUCTOR_chainId),
        (p.get("CONTRACTCODE"), _177_SC_CONSTRUCTOR_contractCode)
    ]],
    [
        SC_CONTRACT_INFO, [
        (p.get("CHAINID"), _178_SC_CONTRACT_INFO_chainId),
        (p.get("CONTRACTADDRESS"), _178_SC_CONTRACT_INFO_contractAddress)
    ]],
    [
        SC_CONTRACT_OFFLINE_TX_HASH_LIST, [
        (p.get("CHAINID"), _179_SC_CONTRACT_OFFLINE_TX_HASH_LIST_chainId),
        (p.get("BLOCKHASH"), _179_SC_CONTRACT_OFFLINE_TX_HASH_LIST_blockHash)
    ]],
    [
        SC_CONTRACT_RESULT, [
        (p.get("CHAINID"), _180_SC_CONTRACT_RESULT_chainId),
        (p.get("HASH"), _180_SC_CONTRACT_RESULT_hash)
    ]],
    [
        SC_CONTRACT_RESULT_LIST, [
        (p.get("CHAINID"), _181_SC_CONTRACT_RESULT_LIST_chainId),
        (p.get("HASHLIST"), _181_SC_CONTRACT_RESULT_LIST_hashList)
    ]],
    [
        SC_CONTRACT_TX, [
        (p.get("CHAINID"), _182_SC_CONTRACT_TX_chainId),
        (p.get("HASH"), _182_SC_CONTRACT_TX_hash)
    ]],
    [
        SC_CREATE, [
        (p.get("CHAINID"), _183_SC_CREATE_chainId),
        (p.get("SENDER"), _183_SC_CREATE_sender),
        (p.get("PASSWORD"), _183_SC_CREATE_password),
        (p.get("ALIAS"), _183_SC_CREATE_alias),
        (p.get("GASLIMIT"), _183_SC_CREATE_gasLimit),
        (p.get("PRICE"), _183_SC_CREATE_price),
        (p.get("CONTRACTCODE"), _183_SC_CREATE_contractCode),
        (p.get("ARGS"), _183_SC_CREATE_args),
        (p.get("REMARK"), _183_SC_CREATE_remark)
    ]],
    [
        SC_CREATE_VALIDATOR, [
        (p.get("CHAINID"), _184_SC_CREATE_VALIDATOR_chainId),
        (p.get("TX"), _184_SC_CREATE_VALIDATOR_tx)
    ]],
    [
        SC_DELETE, [
        (p.get("CHAINID"), _185_SC_DELETE_chainId),
        (p.get("SENDER"), _185_SC_DELETE_sender),
        (p.get("PASSWORD"), _185_SC_DELETE_password),
        (p.get("CONTRACTADDRESS"), _185_SC_DELETE_contractAddress),
        (p.get("REMARK"), _185_SC_DELETE_remark)
    ]],
    [
        SC_DELETE_VALIDATOR, [
        (p.get("CHAINID"), _186_SC_DELETE_VALIDATOR_chainId),
        (p.get("TX"), _186_SC_DELETE_VALIDATOR_tx)
    ]],
    [
        SC_IMPUTED_CALL_GAS, [
        (p.get("CHAINID"), _187_SC_IMPUTED_CALL_GAS_chainId),
        (p.get("SENDER"), _187_SC_IMPUTED_CALL_GAS_sender),
        (p.get("VALUE"), _187_SC_IMPUTED_CALL_GAS_value),
        (p.get("CONTRACTADDRESS"), _187_SC_IMPUTED_CALL_GAS_contractAddress),
        (p.get("METHODNAME"), _187_SC_IMPUTED_CALL_GAS_methodName),
        (p.get("METHODDESC"), _187_SC_IMPUTED_CALL_GAS_methodDesc),
        (p.get("ARGS"), _187_SC_IMPUTED_CALL_GAS_args)
    ]],
    [
        SC_IMPUTED_CREATE_GAS, [
        (p.get("CHAINID"), _188_SC_IMPUTED_CREATE_GAS_chainId),
        (p.get("SENDER"), _188_SC_IMPUTED_CREATE_GAS_sender),
        (p.get("CONTRACTCODE"), _188_SC_IMPUTED_CREATE_GAS_contractCode),
        (p.get("ARGS"), _188_SC_IMPUTED_CREATE_GAS_args)
    ]],
    [
        SC_INITIAL_ACCOUNT_TOKEN, [
        (p.get("CHAINID"), _189_SC_INITIAL_ACCOUNT_TOKEN_chainId),
        (p.get("ADDRESS"), _189_SC_INITIAL_ACCOUNT_TOKEN_address)
    ]],
    [
        SC_INVOKE_CONTRACT, [
        (p.get("CHAINID"), _190_SC_INVOKE_CONTRACT_chainId),
        (p.get("BLOCKTYPE"), _190_SC_INVOKE_CONTRACT_blockType),
        (p.get("TX"), _190_SC_INVOKE_CONTRACT_tx)
    ]],
    [
        SC_INVOKE_VIEW, [
        (p.get("CHAINID"), _191_SC_INVOKE_VIEW_chainId),
        (p.get("CONTRACTADDRESS"), _191_SC_INVOKE_VIEW_contractAddress),
        (p.get("METHODNAME"), _191_SC_INVOKE_VIEW_methodName),
        (p.get("METHODDESC"), _191_SC_INVOKE_VIEW_methodDesc),
        (p.get("ARGS"), _191_SC_INVOKE_VIEW_args)
    ]],
    [
        SC_PACKAGE_BATCH_END, [
        (p.get("CHAINID"), _192_SC_PACKAGE_BATCH_END_chainId),
        (p.get("BLOCKHEIGHT"), _192_SC_PACKAGE_BATCH_END_blockHeight)
    ]],
    [
        SC_TOKEN_ASSETS_LIST, [
        (p.get("CHAINID"), _193_SC_TOKEN_ASSETS_LIST_chainId),
        (p.get("ADDRESS"), _193_SC_TOKEN_ASSETS_LIST_address),
        (p.get("PAGENUMBER"), _193_SC_TOKEN_ASSETS_LIST_pageNumber),
        (p.get("PAGESIZE"), _193_SC_TOKEN_ASSETS_LIST_pageSize)
    ]],
    [
        SC_TOKEN_BALANCE, [
        (p.get("CHAINID"), _194_SC_TOKEN_BALANCE_chainId),
        (p.get("CONTRACTADDRESS"), _194_SC_TOKEN_BALANCE_contractAddress),
        (p.get("ADDRESS"), _194_SC_TOKEN_BALANCE_address)
    ]],
    [
        SC_TOKEN_TRANSFER, [
        (p.get("CHAINID"), _195_SC_TOKEN_TRANSFER_chainId),
        (p.get("ADDRESS"), _195_SC_TOKEN_TRANSFER_address),
        (p.get("TOADDRESS"), _195_SC_TOKEN_TRANSFER_toAddress),
        (p.get("CONTRACTADDRESS"), _195_SC_TOKEN_TRANSFER_contractAddress),
        (p.get("PASSWORD"), _195_SC_TOKEN_TRANSFER_password),
        (p.get("AMOUNT"), _195_SC_TOKEN_TRANSFER_amount),
        (p.get("REMARK"), _195_SC_TOKEN_TRANSFER_remark)
    ]],
    [
        SC_TOKEN_TRANSFER_LIST, [
        (p.get("CHAINID"), _196_SC_TOKEN_TRANSFER_LIST_chainId),
        (p.get("ADDRESS"), _196_SC_TOKEN_TRANSFER_LIST_address),
        (p.get("PAGENUMBER"), _196_SC_TOKEN_TRANSFER_LIST_pageNumber),
        (p.get("PAGESIZE"), _196_SC_TOKEN_TRANSFER_LIST_pageSize)
    ]],
    [
        SC_TRANSFER, [
        (p.get("CHAINID"), _197_SC_TRANSFER_chainId),
        (p.get("ADDRESS"), _197_SC_TRANSFER_address),
        (p.get("TOADDRESS"), _197_SC_TRANSFER_toAddress),
        (p.get("PASSWORD"), _197_SC_TRANSFER_password),
        (p.get("AMOUNT"), _197_SC_TRANSFER_amount),
        (p.get("REMARK"), _197_SC_TRANSFER_remark)
    ]],
    [
        SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT, [
        (p.get("CHAINID"), _198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_chainId),
        (p.get("STATEROOT"), _198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_stateRoot),
        (p.get("BLOCKHEIGHT"), _198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_blockHeight),
        (p.get("CONTRACTADDRESS"), _198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_contractAddress),
        (p.get("TX"), _198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_tx)
    ]],
    [
        SC_UPLOAD, [
        (p.get("CHAINID"), _199_SC_UPLOAD_chainId),
        (p.get("JARFILEDATA"), _199_SC_UPLOAD_jarFileData)
    ]],
    [
        SC_VALIDATE_CALL, [
        (p.get("CHAINID"), _200_SC_VALIDATE_CALL_chainId),
        (p.get("SENDER"), _200_SC_VALIDATE_CALL_sender),
        (p.get("VALUE"), _200_SC_VALIDATE_CALL_value),
        (p.get("GASLIMIT"), _200_SC_VALIDATE_CALL_gasLimit),
        (p.get("PRICE"), _200_SC_VALIDATE_CALL_price),
        (p.get("CONTRACTADDRESS"), _200_SC_VALIDATE_CALL_contractAddress),
        (p.get("METHODNAME"), _200_SC_VALIDATE_CALL_methodName),
        (p.get("METHODDESC"), _200_SC_VALIDATE_CALL_methodDesc),
        (p.get("ARGS"), _200_SC_VALIDATE_CALL_args)
    ]],
    [
        SC_VALIDATE_CREATE, [
        (p.get("CHAINID"), _201_SC_VALIDATE_CREATE_chainId),
        (p.get("SENDER"), _201_SC_VALIDATE_CREATE_sender),
        (p.get("GASLIMIT"), _201_SC_VALIDATE_CREATE_gasLimit),
        (p.get("PRICE"), _201_SC_VALIDATE_CREATE_price),
        (p.get("CONTRACTCODE"), _201_SC_VALIDATE_CREATE_contractCode),
        (p.get("ARGS"), _201_SC_VALIDATE_CREATE_args)
    ]],
    [
        SC_VALIDATE_DELETE, [
        (p.get("CHAINID"), _202_SC_VALIDATE_DELETE_chainId),
        (p.get("CONTRACTADDRESS"), _202_SC_VALIDATE_DELETE_contractAddress)
    ]],
    [
        STOP_AGENTVALID, [
        (p.get("CHAINID"), _203_STOP_AGENTVALID_chainId),
        (p.get("TX"), _203_STOP_AGENTVALID_tx)
    ]],
    [
        TX_COMMIT, [
        (p.get("CHAINID"), _204_TX_COMMIT_chainId),
        (p.get("TXLIST"), _204_TX_COMMIT_txList),
        (p.get("BLOCKHEADER"), _204_TX_COMMIT_blockHeader)
    ]],
    [
        TX_VALIDATOR, [
        (p.get("CHAINID"), _205_TX_VALIDATOR_chainId),
        (p.get("TXLIST"), _205_TX_VALIDATOR_txList),
        (p.get("BLOCKHEADER"), _205_TX_VALIDATOR_blockHeader)
    ]],
    [
        TX_BACK_PACKABLE_TXS, [
        (p.get("CHAINID"), _206_TX_BACK_PACKABLE_TXS_chainId),
        (p.get("TXLIST"), _206_TX_BACK_PACKABLE_TXS_txList)
    ]],
    [
        TX_BATCH_VERIFY, [
        (p.get("CHAINID"), _207_TX_BATCH_VERIFY_chainId),
        (p.get("TXLIST"), _207_TX_BATCH_VERIFY_txList),
        (p.get("BLOCKHEADER"), _207_TX_BATCH_VERIFY_blockHeader),
        (p.get("PRESTATEROOT"), _207_TX_BATCH_VERIFY_preStateRoot)
    ]],
    [
        TX_BL_STATE, [
        (p.get("CHAINID"), _208_TX_BL_STATE_chainId),
        (p.get("STATUS"), _208_TX_BL_STATE_status)
    ]],
    [
        TX_BLOCK_HEIGHT, [
        (p.get("CHAINID"), _209_TX_BLOCK_HEIGHT_chainId),
        (p.get("HEIGHT"), _209_TX_BLOCK_HEIGHT_height)
    ]],
    [
        TX_CS_STATE, [
        (p.get("CHAINID"), _210_TX_CS_STATE_chainId),
        (p.get("PACKAGING"), _210_TX_CS_STATE_packaging)
    ]],
    [
        TX_GET_BLOCKTXS, [
        (p.get("CHAINID"), _211_TX_GET_BLOCKTXS_chainId),
        (p.get("TXHASHLIST"), _211_TX_GET_BLOCKTXS_txHashList)
    ]],
    [
        TX_GET_BLOCKTXS_EXTEND, [
        (p.get("CHAINID"), _212_TX_GET_BLOCKTXS_EXTEND_chainId),
        (p.get("TXHASHLIST"), _212_TX_GET_BLOCKTXS_EXTEND_txHashList),
        (p.get("ALLHITS"), _212_TX_GET_BLOCKTXS_EXTEND_allHits)
    ]],
    [
        TX_GET_CONFIRMED_TX, [
        (p.get("CHAINID"), _213_TX_GET_CONFIRMED_TX_chainId),
        (p.get("TXHASH"), _213_TX_GET_CONFIRMED_TX_txHash)
    ]],
    [
        TX_GET_CONFIRMED_TX_CLIENT, [
        (p.get("CHAINID"), _214_TX_GET_CONFIRMED_TX_CLIENT_chainId),
        (p.get("TXHASH"), _214_TX_GET_CONFIRMED_TX_CLIENT_txHash)
    ]],
    [
        TX_GET_NONEXISTENT_UNCONFIRMED_HASHS, [
        (p.get("CHAINID"), _215_TX_GET_NONEXISTENT_UNCONFIRMED_HASHS_chainId),
        (p.get("TXHASHLIST"), _215_TX_GET_NONEXISTENT_UNCONFIRMED_HASHS_txHashList)
    ]],
    [
        TX_GET_SYSTEMTYPES, [
        (p.get("CHAINID"), _216_TX_GET_SYSTEMTYPES_chainId)
    ]],
    [
        TX_GET_TX, [
        (p.get("CHAINID"), _217_TX_GET_TX_chainId),
        (p.get("TXHASH"), _217_TX_GET_TX_txHash)
    ]],
    [
        TX_GET_TX_CLIENT, [
        (p.get("CHAINID"), _218_TX_GET_TX_CLIENT_chainId),
        (p.get("TXHASH"), _218_TX_GET_TX_CLIENT_txHash)
    ]],
    [
        TX_NEWTX, [
        (p.get("CHAINID"), _219_TX_NEWTX_chainId),
        (p.get("TX"), _219_TX_NEWTX_tx)
    ]],
    [
        TX_PACKABLE_TXS, [
        (p.get("CHAINID"), _220_TX_PACKABLE_TXS_chainId),
        (p.get("ENDTIMESTAMP"), _220_TX_PACKABLE_TXS_endTimestamp),
        (p.get("MAXTXDATASIZE"), _220_TX_PACKABLE_TXS_maxTxDataSize),
        (p.get("BLOCKTIME"), _220_TX_PACKABLE_TXS_blockTime),
        (p.get("PACKINGADDRESS"), _220_TX_PACKABLE_TXS_packingAddress),
        (p.get("PRESTATEROOT"), _220_TX_PACKABLE_TXS_preStateRoot)
    ]],
    [
        TX_REGISTER, [
        (p.get("CHAINID"), _221_TX_REGISTER_chainId),
        (p.get("MODULECODE"), _221_TX_REGISTER_moduleCode),
        (p.get("LIST"), _221_TX_REGISTER_list),
        (p.get("DELLIST"), _221_TX_REGISTER_delList)
    ]],
    [
        TX_ROLLBACK, [
        (p.get("CHAINID"), _222_TX_ROLLBACK_chainId),
        (p.get("TXHASHLIST"), _222_TX_ROLLBACK_txHashList),
        (p.get("BLOCKHEADER"), _222_TX_ROLLBACK_blockHeader)
    ]],
    [
        TX_SAVE, [
        (p.get("CHAINID"), _223_TX_SAVE_chainId),
        (p.get("TXLIST"), _223_TX_SAVE_txList),
        (p.get("CONTRACTLIST"), _223_TX_SAVE_contractList),
        (p.get("BLOCKHEADER"), _223_TX_SAVE_blockHeader)
    ]],
    [
        TX_VERIFY_TX, [
        (p.get("CHAINID"), _224_TX_VERIFY_TX_chainId),
        (p.get("TX"), _224_TX_VERIFY_TX_tx)
    ]],
    [
        UPDATE_CHAIN_ASSET, [
        (p.get("CHAINID"), _225_UPDATE_CHAIN_ASSET_chainId),
        (p.get("ASSETS"), _225_UPDATE_CHAIN_ASSET_assets)
    ]],
    [
        VERIFY_COINDATA, [
        (p.get("CHAINID"), _226_VERIFY_COINDATA_chainId),
        (p.get("TX"), _226_VERIFY_COINDATA_tx)
    ]],
    [
        VERIFY_COINDATA_BATCH_PACKAGED, [
        (p.get("CHAINID"), _227_VERIFY_COINDATA_BATCH_PACKAGED_chainId),
        (p.get("TXLIST"), _227_VERIFY_COINDATA_BATCH_PACKAGED_txList)
    ]],
    [
        WITHDRAW_VALID, [
        (p.get("CHAINID"), _228_WITHDRAW_VALID_chainId),
        (p.get("TX"), _228_WITHDRAW_VALID_tx)
    ]]
]
