#!/usr/bin/python3.7
"""
by Nancy Schorr for Nuls, Nulstar),
(December, None),
(2019

"""
# Do not edit this file to run queries - only for adding or changing methods

from Libraries.Constants.Dictionaires.nulsws_CONSTANTS_PARAM_LABELS import param_name_dict as p
from UserSettings.nulsws_USER_PARAMS import *
import Libraries.Constants.CLASSES.nulsws_c_labels as nulab

class nulsws_Cls_Prm(nulab.nulsws_Labels):

    def __init__(self):
        nn = nulab.nulsws_Labels()

    n = nulab.nulsws_Labels()
    # list of lists of tups
    ulab = nulab.nulsws_Labels.__init__(nulab.nulsws_Labels)

    USER_CALLS_DB = [
        [
            n.AC_CREATE_OFFLINE_ACCOUNT, [
            (p.get("CHAINID"), 5_AC_CREATE_OFFLINE_ACCOUNT_chainId),
            (p.get("COUNT"), 5_AC_CREATE_OFFLINE_ACCOUNT_count),
            (p.get("PASSWORD"), 5_AC_CREATE_OFFLINE_ACCOUNT_password)
        ]],
        [
            AC_EXPORT_ACCOUNT_KEYSTORE, [
            (p.get("CHAINID"), 6_AC_EXPORT_ACCOUNT_KEYSTORE_chainId),
            (p.get("ADDRESS"), 6_AC_EXPORT_ACCOUNT_KEYSTORE_address),
            (p.get("PASSWORD"), 6_AC_EXPORT_ACCOUNT_KEYSTORE_password),
            (p.get("FILEPATH"), 6_AC_EXPORT_ACCOUNT_KEYSTORE_filePath)
        ]],
        [
            AC_EXPORT_KEYSTORE_JSON, [
            (p.get("CHAINID"), 7_AC_EXPORT_KEYSTORE_JSON_chainId),
            (p.get("ADDRESS"), 7_AC_EXPORT_KEYSTORE_JSON_address),
            (p.get("PASSWORD"), 7_AC_EXPORT_KEYSTORE_JSON_password)
        ]],
        [
            AC_GET_ACCOUNT_BYADDRESS, [
            (p.get("CHAINID"), 8_AC_GET_ACCOUNT_BYADDRESS_chainId),
            (p.get("ADDRESS"), 8_AC_GET_ACCOUNT_BYADDRESS_address)
        ]],
        [
            AC_GET_ACCOUNT_LIST, [
            (p.get("CHAINID"), 9_AC_GET_ACCOUNT_LIST_chainId)
        ]],
        [
            AC_GET_ADDRESS_LIST, [
            (p.get("CHAINID"), 10_AC_GET_ADDRESS_LIST_chainId),
            (p.get("PAGENUMBER"), 10_AC_GET_ADDRESS_LIST_pageNumber),
            (p.get("PAGESIZE"), 10_AC_GET_ADDRESS_LIST_pageSize)
        ]],
        [
            AC_GET_ADDRESS_PREFIX_BY_CHAINID, [
            (p.get("CHAINID"), 11_AC_GET_ADDRESS_PREFIX_BY_CHAINID_chainId)
        ]],
        [
            AC_GET_ALIASBY_ADDRESS, [
            (p.get("CHAINID"), 12_AC_GET_ALIASBY_ADDRESS_chainId),
            (p.get("ADDRESS"), 12_AC_GET_ALIASBY_ADDRESS_address)
        ]],
        [
            AC_GET_ALL_PRIKEY, [
            (p.get("CHAINID"), 14_AC_GET_ALL_PRIKEY_chainId),
            (p.get("PASSWORD"), 14_AC_GET_ALL_PRIKEY_password)
        ]],
        [
            AC_GET_ENCRYPTED_ADDRESS_LIST, [
            (p.get("CHAINID"), 15_AC_GET_ENCRYPTED_ADDRESS_LIST_chainId)
        ]],
        [
            AC_GET_MULTI_SIGN_ACCOUNT, [
            (p.get("CHAINID"), 16_AC_GET_MULTI_SIGN_ACCOUNT_chainId),
            (p.get("ADDRESS"), 16_AC_GET_MULTI_SIGN_ACCOUNT_address)
        ]],
        [
            AC_GET_PUBKEY, [
            (p.get("CHAINID"), 17_AC_GET_PUBKEY_chainId),
            (p.get("ADDRESS"), 17_AC_GET_PUBKEY_address),
            (p.get("PASSWORD"), 17_AC_GET_PUBKEY_password)
        ]],
        [
            AC_IMPORT_ACCOUNT_BY_KEYSTORE, [
            (p.get("CHAINID"), 18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_chainId),
            (p.get("PASSWORD"), 18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_password),
            (p.get("KEYSTORE"), 18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_keyStore),
            (p.get("OVERWRITE"), 18_AC_IMPORT_ACCOUNT_BY_KEYSTORE_overwrite)
        ]],
        [
            AC_IMPORT_ACCOUNT_BY_PRIKEY, [
            (p.get("CHAINID"), 19_AC_IMPORT_ACCOUNT_BY_PRIKEY_chainId),
            (p.get("PASSWORD"), 19_AC_IMPORT_ACCOUNT_BY_PRIKEY_password),
            (p.get("PRIKEY"), 19_AC_IMPORT_ACCOUNT_BY_PRIKEY_priKey),
            (p.get("OVERWRITE"), 19_AC_IMPORT_ACCOUNT_BY_PRIKEY_overwrite)
        ]],
        [
            AC_IS_ALIAS_USABLE, [
            (p.get("CHAINID"), 20_AC_IS_ALIAS_USABLE_chainId),
            (p.get("ALIAS"), 20_AC_IS_ALIAS_USABLE_alias)
        ]],
        [
            AC_IS_MULTISIGN_ACCOUNT_BUILDER, [
            (p.get("CHAINID"), 21_AC_IS_MULTISIGN_ACCOUNT_BUILDER_chainId),
            (p.get("ADDRESS"), 21_AC_IS_MULTISIGN_ACCOUNT_BUILDER_address),
            (p.get("PUBKEY"), 21_AC_IS_MULTISIGN_ACCOUNT_BUILDER_pubKey)
        ]],
        [
            AC_REMOVE_ACCOUNT, [
            (p.get("CHAINID"), 22_AC_REMOVE_ACCOUNT_chainId),
            (p.get("ADDRESS"), 22_AC_REMOVE_ACCOUNT_address),
            (p.get("PASSWORD"), 22_AC_REMOVE_ACCOUNT_password)
        ]],
        [
            AC_REMOVE_MULTISIGN_ACCOUNT, [
            (p.get("CHAINID"), 23_AC_REMOVE_MULTISIGN_ACCOUNT_chainId),
            (p.get("ADDRESS"), 23_AC_REMOVE_MULTISIGN_ACCOUNT_address)
        ]],
        [
            AC_SET_ALIAS, [
            (p.get("CHAINID"), 24_AC_SET_ALIAS_chainId),
            (p.get("ADDRESS"), 24_AC_SET_ALIAS_address),
            (p.get("PASSWORD"), 24_AC_SET_ALIAS_password),
            (p.get("ALIAS"), 24_AC_SET_ALIAS_alias)
        ]],
        [
            AC_SET_MULTISIGN_ALIAS, [
            (p.get("CHAINID"), 25_AC_SET_MULTISIGN_ALIAS_chainId),
            (p.get("ADDRESS"), 25_AC_SET_MULTISIGN_ALIAS_address),
            (p.get("ALIAS"), 25_AC_SET_MULTISIGN_ALIAS_alias),
            (p.get("SIGNADDRESS"), 25_AC_SET_MULTISIGN_ALIAS_signAddress),
            (p.get("SIGNPASSWORD"), 25_AC_SET_MULTISIGN_ALIAS_signPassword)
        ]],
        [
            AC_SET_REMARK, [
            (p.get("CHAINID"), 26_AC_SET_REMARK_chainId),
            (p.get("ADDRESS"), 26_AC_SET_REMARK_address),
            (p.get("REMARK"), 26_AC_SET_REMARK_remark)
        ]],
        [
            AC_SIGN_BLOCKDIGEST, [
            (p.get("CHAINID"), 27_AC_SIGN_BLOCKDIGEST_chainId),
            (p.get("ADDRESS"), 27_AC_SIGN_BLOCKDIGEST_address),
            (p.get("PASSWORD"), 27_AC_SIGN_BLOCKDIGEST_password),
            (p.get("DATA"), 27_AC_SIGN_BLOCKDIGEST_data)
        ]],
        [
            AC_SIGN_DIGEST, [
            (p.get("CHAINID"), 28_AC_SIGN_DIGEST_chainId),
            (p.get("ADDRESS"), 28_AC_SIGN_DIGEST_address),
            (p.get("PASSWORD"), 28_AC_SIGN_DIGEST_password),
            (p.get("DATA"), 28_AC_SIGN_DIGEST_data)
        ]],
        [
            AC_SIGN_MULTISIGN_TRANSACTION, [
            (p.get("CHAINID"), 29_AC_SIGN_MULTISIGN_TRANSACTION_chainId),
            (p.get("TX"), 29_AC_SIGN_MULTISIGN_TRANSACTION_tx),
            (p.get("SIGNADDRESS"), 29_AC_SIGN_MULTISIGN_TRANSACTION_signAddress),
            (p.get("SIGNPASSWORD"), 29_AC_SIGN_MULTISIGN_TRANSACTION_signPassword)
        ]],
        [
            AC_TRANSFER, [
            (p.get("CHAINID"), 30_AC_TRANSFER_chainId),
            (p.get("INPUTS"), 30_AC_TRANSFER_inputs),
            (p.get("OUTPUTS"), 30_AC_TRANSFER_outputs),
            (p.get("REMARK"), 30_AC_TRANSFER_remark)
        ]],
        [
            AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD, [
            (p.get("CHAINID"), 31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_chainId),
            (p.get("ADDRESS"), 31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_address),
            (p.get("PASSWORD"), 31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_password),
            (p.get("NEWPASSWORD"), 31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_newPassword),
            (p.get("PRIKEY"), 31_AC_UPDATE_OFFLINE_ACCOUNT_PASSWORD_priKey)
        ]],
        [
            AC_UPDATE_PASSWORD, [
            (p.get("CHAINID"), 32_AC_UPDATE_PASSWORD_chainId),
            (p.get("ADDRESS"), 32_AC_UPDATE_PASSWORD_address),
            (p.get("PASSWORD"), 32_AC_UPDATE_PASSWORD_password),
            (p.get("NEWPASSWORD"), 32_AC_UPDATE_PASSWORD_newPassword)
        ]],
        [
            AC_VALIDATION_PASSWORD, [
            (p.get("CHAINID"), 33_AC_VALIDATION_PASSWORD_chainId),
            (p.get("ADDRESS"), 33_AC_VALIDATION_PASSWORD_address),
            (p.get("PASSWORD"), 33_AC_VALIDATION_PASSWORD_password)
        ]],
        [
            AC_VERIFY_SIGN_DATA, [
            (p.get("PUBKEY"), 34_AC_VERIFY_SIGN_DATA_pubKey),
            (p.get("SIG"), 34_AC_VERIFY_SIGN_DATA_sig),
            (p.get("DATA"), 34_AC_VERIFY_SIGN_DATA_data)
        ]],
        [
            BATCH_VALIDATE_BEGIN, [
            (p.get("CHAINID"), 35_BATCH_VALIDATE_BEGIN_chainId)
        ]],
        [
            BLOCK_VALIDATE, [
            (p.get("CHAINID"), 36_BLOCK_VALIDATE_chainId),
            (p.get("TXLIST"), 36_BLOCK_VALIDATE_txList)
        ]],
        [
            CANCEL_CROSSCHAIN, [
            (p.get("CHAINID"), 38_CANCEL_CROSSCHAIN_chainId),
            (p.get("ASSETID"), 38_CANCEL_CROSSCHAIN_assetId)
        ]],
        [
            CHECK_BLOCK_VERSION, [
            (p.get("CHAINID"), 39_CHECK_BLOCK_VERSION_chainId),
            (p.get("EXTENDSDATA"), 39_CHECK_BLOCK_VERSION_extendsData)
        ]],
        [
            CM_ASSET, [
            (p.get("CHAINID"), 40_CM_ASSET_chainId),
            (p.get("ASSETID"), 40_CM_ASSET_assetId)
        ]],
        [
            CM_ASSET_CIRCULATE_COMMIT, [
            (p.get("CHAINID"), 41_CM_ASSET_CIRCULATE_COMMIT_chainId),
            (p.get("TXLIST"), 41_CM_ASSET_CIRCULATE_COMMIT_txList),
            (p.get("BLOCKHEADER"), 41_CM_ASSET_CIRCULATE_COMMIT_blockHeader)
        ]],
        [
            CM_ASSET_CIRCULATE_ROLLBACK, [
            (p.get("CHAINID"), 42_CM_ASSET_CIRCULATE_ROLLBACK_chainId),
            (p.get("TXLIST"), 42_CM_ASSET_CIRCULATE_ROLLBACK_txList),
            (p.get("BLOCKHEADER"), 42_CM_ASSET_CIRCULATE_ROLLBACK_blockHeader)
        ]],
        [
            CM_ASSET_CIRCULATE_VALIDATOR, [
            (p.get("CHAINID"), 43_CM_ASSET_CIRCULATE_VALIDATOR_chainId),
            (p.get("TX"), 43_CM_ASSET_CIRCULATE_VALIDATOR_tx)
        ]],
        [
            CM_ASSET_DISABLE, [
            (p.get("CHAINID"), 44_CM_ASSET_DISABLE_chainId),
            (p.get("ASSETID"), 44_CM_ASSET_DISABLE_assetId),
            (p.get("ADDRESS"), 44_CM_ASSET_DISABLE_address),
            (p.get("PASSWORD"), 44_CM_ASSET_DISABLE_password)
        ]],
        [
            CM_ASSET_REG, [
            (p.get("CHAINID"), 45_CM_ASSET_REG_chainId),
            (p.get("ASSETID"), 45_CM_ASSET_REG_assetId),
            (p.get("SYMBOL"), 45_CM_ASSET_REG_symbol),
            (p.get("ASSETNAME"), 45_CM_ASSET_REG_assetName),
            (p.get("INITNUMBER"), 45_CM_ASSET_REG_initNumber),
            (p.get("DECIMALPLACES"), 45_CM_ASSET_REG_decimalPlaces),
            (p.get("ADDRESS"), 45_CM_ASSET_REG_address),
            (p.get("PASSWORD"), 45_CM_ASSET_REG_password)
        ]],
        [
            CM_CHAIN, [
            (p.get("CHAINID"), 46_CM_CHAIN_chainId)
        ]],
        [
            CM_CHAIN_ACTIVE, [
            (p.get("CHAINID"), 47_CM_CHAIN_ACTIVE_chainId),
            (p.get("CHAINNAME"), 47_CM_CHAIN_ACTIVE_chainName),
            (p.get("ADDRESSTYPE"), 47_CM_CHAIN_ACTIVE_addressType),
            (p.get("ADDRESSPREFIX"), 47_CM_CHAIN_ACTIVE_addressPrefix),
            (p.get("MAGICNUMBER"), 47_CM_CHAIN_ACTIVE_magicNumber),
            (p.get("MINAVAILABLENODENUM"), 47_CM_CHAIN_ACTIVE_minAvailableNodeNum),
            (p.get("ASSETID"), 47_CM_CHAIN_ACTIVE_assetId),
            (p.get("SYMBOL"), 47_CM_CHAIN_ACTIVE_symbol),
            (p.get("ASSETNAME"), 47_CM_CHAIN_ACTIVE_assetName),
            (p.get("INITNUMBER"), 47_CM_CHAIN_ACTIVE_initNumber),
            (p.get("DECIMALPLACES"), 47_CM_CHAIN_ACTIVE_decimalPlaces),
            (p.get("ADDRESS"), 47_CM_CHAIN_ACTIVE_address),
            (p.get("PASSWORD"), 47_CM_CHAIN_ACTIVE_password),
            (p.get("VERIFIERLIST"), 47_CM_CHAIN_ACTIVE_verifierList),
            (p.get("SIGNATUREBFTRATIO"), 47_CM_CHAIN_ACTIVE_signatureBFTRatio),
            (p.get("MAXSIGNATURECOUNT"), 47_CM_CHAIN_ACTIVE_maxSignatureCount)
        ]],
        [
            CM_CHAIN_REG, [
            (p.get("CHAINID"), 48_CM_CHAIN_REG_chainId),
            (p.get("CHAINNAME"), 48_CM_CHAIN_REG_chainName),
            (p.get("ADDRESSTYPE"), 48_CM_CHAIN_REG_addressType),
            (p.get("ADDRESSPREFIX"), 48_CM_CHAIN_REG_addressPrefix),
            (p.get("MAGICNUMBER"), 48_CM_CHAIN_REG_magicNumber),
            (p.get("MINAVAILABLENODENUM"), 48_CM_CHAIN_REG_minAvailableNodeNum),
            (p.get("ASSETID"), 48_CM_CHAIN_REG_assetId),
            (p.get("SYMBOL"), 48_CM_CHAIN_REG_symbol),
            (p.get("ASSETNAME"), 48_CM_CHAIN_REG_assetName),
            (p.get("INITNUMBER"), 48_CM_CHAIN_REG_initNumber),
            (p.get("DECIMALPLACES"), 48_CM_CHAIN_REG_decimalPlaces),
            (p.get("ADDRESS"), 48_CM_CHAIN_REG_address),
            (p.get("PASSWORD"), 48_CM_CHAIN_REG_password),
            (p.get("VERIFIERLIST"), 48_CM_CHAIN_REG_verifierList),
            (p.get("SIGNATUREBFTRATIO"), 48_CM_CHAIN_REG_signatureBFTRatio),
            (p.get("MAXSIGNATURECOUNT"), 48_CM_CHAIN_REG_maxSignatureCount)
        ]],
        [
            CM_GET_CHAIN_ASSET, [
            (p.get("CHAINID"), 49_CM_GET_CHAIN_ASSET_chainId),
            (p.get("ASSETCHAINID"), 49_CM_GET_CHAIN_ASSET_assetChainId),
            (p.get("ASSETID"), 49_CM_GET_CHAIN_ASSET_assetId)
        ]],
        [
            CM_GET_CIRCULATE_CHAIN_ASSET, [
            (p.get("CIRCULATECHAINID"), 50_CM_GET_CIRCULATE_CHAIN_ASSET_circulateChainId),
            (p.get("ASSETCHAINID"), 50_CM_GET_CIRCULATE_CHAIN_ASSET_assetChainId),
            (p.get("ASSETID"), 50_CM_GET_CIRCULATE_CHAIN_ASSET_assetId)
        ]],
        [
            COMMIT_BATCH_UNCONFIRMED_TXS, [
            (p.get("CHAINID"), 51_COMMIT_BATCH_UNCONFIRMED_TXS_chainId),
            (p.get("TXLIST"), 51_COMMIT_BATCH_UNCONFIRMED_TXS_txList)
        ]],
        [
            COMMIT_BLOCKTXS, [
            (p.get("CHAINID"), 52_COMMIT_BLOCKTXS_chainId),
            (p.get("TXLIST"), 52_COMMIT_BLOCKTXS_txList),
            (p.get("BLOCKHEIGHT"), 52_COMMIT_BLOCKTXS_blockHeight)
        ]],
        [
            COMMIT_UNCONFIRMEDTX, [
            (p.get("CHAINID"), 53_COMMIT_UNCONFIRMEDTX_chainId),
            (p.get("TX"), 53_COMMIT_UNCONFIRMEDTX_tx)
        ]],
        [
            CREATE_AGENT_VALID, [
            (p.get("CHAINID"), 55_CREATE_AGENT_VALID_chainId),
            (p.get("TX"), 55_CREATE_AGENT_VALID_tx)
        ]],
        [
            CREATE_CROSSTX, [
            (p.get("CHAINID"), 56_CREATE_CROSSTX_chainId),
            (p.get("LISTFROM"), 56_CREATE_CROSSTX_listFrom),
            (p.get("LISTTO"), 56_CREATE_CROSSTX_listTo),
            (p.get("REMARK"), 56_CREATE_CROSSTX_remark)
        ]],
        [
            CROSSCHAIN_REGISTER_CHANGE, [
            (p.get("CHAINID"), 57_CROSSCHAIN_REGISTER_CHANGE_chainId)
        ]],
        [
            CS_ADD_BLOCK, [
            (p.get("CHAINID"), 58_CS_ADD_BLOCK_chainId),
            (p.get("BLOCKHEADER"), 58_CS_ADD_BLOCK_blockHeader)
        ]],
        [
            CS_ADD_EVIDENCE_RECORD, [
            (p.get("CHAINID"), 59_CS_ADD_EVIDENCE_RECORD_chainId),
            (p.get("BLOCKHEADER"), 59_CS_ADD_EVIDENCE_RECORD_blockHeader),
            (p.get("EVIDENCEHEADER"), 59_CS_ADD_EVIDENCE_RECORD_evidenceHeader)
        ]],
        [
            CS_CHAIN_ROLLBACK, [
            (p.get("CHAINID"), 60_CS_CHAIN_ROLLBACK_chainId),
            (p.get("HEIGHT"), 60_CS_CHAIN_ROLLBACK_height)
        ]],
        [
            CS_CONTRACT_DEPOSIT, [
            (p.get("CHAINID"), 61_CS_CONTRACT_DEPOSIT_chainId),
            (p.get("AGENTHASH"), 61_CS_CONTRACT_DEPOSIT_agentHash),
            (p.get("DEPOSIT"), 61_CS_CONTRACT_DEPOSIT_deposit),
            (p.get("CONTRACTADDRESS"), 61_CS_CONTRACT_DEPOSIT_contractAddress),
            (p.get("CONTRACTSENDER"), 61_CS_CONTRACT_DEPOSIT_contractSender),
            (p.get("CONTRACTBALANCE"), 61_CS_CONTRACT_DEPOSIT_contractBalance),
            (p.get("CONTRACTNONCE"), 61_CS_CONTRACT_DEPOSIT_contractNonce),
            (p.get("BLOCKTIME"), 61_CS_CONTRACT_DEPOSIT_blockTime)
        ]],
        [
            CS_CONTRACT_WITHDRAW, [
            (p.get("CHAINID"), 62_CS_CONTRACT_WITHDRAW_chainId),
            (p.get("JOINAGENTHASH"), 62_CS_CONTRACT_WITHDRAW_joinAgentHash),
            (p.get("CONTRACTADDRESS"), 62_CS_CONTRACT_WITHDRAW_contractAddress),
            (p.get("CONTRACTSENDER"), 62_CS_CONTRACT_WITHDRAW_contractSender),
            (p.get("CONTRACTBALANCE"), 62_CS_CONTRACT_WITHDRAW_contractBalance),
            (p.get("CONTRACTNONCE"), 62_CS_CONTRACT_WITHDRAW_contractNonce),
            (p.get("BLOCKTIME"), 62_CS_CONTRACT_WITHDRAW_blockTime)
        ]],
        [
            CS_CREATE_AGENT, [
            (p.get("CHAINID"), 63_CS_CREATE_AGENT_chainId),
            (p.get("AGENTADDRESS"), 63_CS_CREATE_AGENT_agentAddress),
            (p.get("PACKINGADDRESS"), 63_CS_CREATE_AGENT_packingAddress),
            (p.get("REWARDADDRESS"), 63_CS_CREATE_AGENT_rewardAddress),
            (p.get("COMMISSIONRATE"), 63_CS_CREATE_AGENT_commissionRate),
            (p.get("DEPOSIT"), 63_CS_CREATE_AGENT_deposit),
            (p.get("PASSWORD"), 63_CS_CREATE_AGENT_password)
        ]],
        [
            CS_CREATE_CONTRACT_AGENT, [
            (p.get("CHAINID"), 64_CS_CREATE_CONTRACT_AGENT_chainId),
            (p.get("PACKINGADDRESS"), 64_CS_CREATE_CONTRACT_AGENT_packingAddress),
            (p.get("DEPOSIT"), 64_CS_CREATE_CONTRACT_AGENT_deposit),
            (p.get("COMMISSIONRATE"), 64_CS_CREATE_CONTRACT_AGENT_commissionRate),
            (p.get("CONTRACTADDRESS"), 64_CS_CREATE_CONTRACT_AGENT_contractAddress),
            (p.get("CONTRACTSENDER"), 64_CS_CREATE_CONTRACT_AGENT_contractSender),
            (p.get("CONTRACTBALANCE"), 64_CS_CREATE_CONTRACT_AGENT_contractBalance),
            (p.get("CONTRACTNONCE"), 64_CS_CREATE_CONTRACT_AGENT_contractNonce),
            (p.get("BLOCKTIME"), 64_CS_CREATE_CONTRACT_AGENT_blockTime)
        ]],
        [
            CS_CREATE_MULTI_AGENT, [
            (p.get("CHAINID"), 65_CS_CREATE_MULTI_AGENT_chainId),
            (p.get("AGENTADDRESS"), 65_CS_CREATE_MULTI_AGENT_agentAddress),
            (p.get("PACKINGADDRESS"), 65_CS_CREATE_MULTI_AGENT_packingAddress),
            (p.get("REWARDADDRESS"), 65_CS_CREATE_MULTI_AGENT_rewardAddress),
            (p.get("COMMISSIONRATE"), 65_CS_CREATE_MULTI_AGENT_commissionRate),
            (p.get("DEPOSIT"), 65_CS_CREATE_MULTI_AGENT_deposit),
            (p.get("PASSWORD"), 65_CS_CREATE_MULTI_AGENT_password),
            (p.get("SIGNADDRESS"), 65_CS_CREATE_MULTI_AGENT_signAddress)
        ]],
        [
            CS_DEPOSIT_TOAGENT, [
            (p.get("CHAINID"), 66_CS_DEPOSIT_TOAGENT_chainId),
            (p.get("ADDRESS"), 66_CS_DEPOSIT_TOAGENT_address),
            (p.get("AGENTHASH"), 66_CS_DEPOSIT_TOAGENT_agentHash),
            (p.get("DEPOSIT"), 66_CS_DEPOSIT_TOAGENT_deposit),
            (p.get("PASSWORD"), 66_CS_DEPOSIT_TOAGENT_password)
        ]],
        [
            CS_DOUBLE_SPEND_RECORD, [
            (p.get("CHAINID"), 67_CS_DOUBLE_SPEND_RECORD_chainId),
            (p.get("BLOCK"), 67_CS_DOUBLE_SPEND_RECORD_block),
            (p.get("TX"), 67_CS_DOUBLE_SPEND_RECORD_tx)
        ]],
        [
            CS_GET_AGENT_ADDRESS_LIST, [
            (p.get("CHAINID"), 68_CS_GET_AGENT_ADDRESS_LIST_chainId)
        ]],
        [
            CS_GET_AGENT_CHANGE_INFO, [
            (p.get("CHAINID"), 69_CS_GET_AGENT_CHANGE_INFO_chainId)
        ]],
        [
            CS_GET_AGENT_INFO, [
            (p.get("CHAINID"), 70_CS_GET_AGENT_INFO_chainId),
            (p.get("AGENTHASH"), 70_CS_GET_AGENT_INFO_agentHash)
        ]],
        [
            CS_GET_AGENT_LIST, [
            (p.get("CHAINID"), 71_CS_GET_AGENT_LIST_chainId),
            (p.get("PAGENUMBER"), 71_CS_GET_AGENT_LIST_pageNumber),
            (p.get("PAGESIZE"), 71_CS_GET_AGENT_LIST_pageSize),
            (p.get("KEYWORD"), 71_CS_GET_AGENT_LIST_keyWord)
        ]],
        [
            CS_GET_AGENT_STATUS, [
            (p.get("CHAINID"), 72_CS_GET_AGENT_STATUS_chainId),
            (p.get("AGENTHASH"), 72_CS_GET_AGENT_STATUS_agentHash)
        ]],
        [
            CS_GET_CONSENSUS_CONFIG, [
            (p.get("CHAINID"), 73_CS_GET_CONSENSUS_CONFIG_chainId)
        ]],
        [
            CS_GET_CONTRACT_AGENT_INFO, [
            (p.get("CHAINID"), 74_CS_GET_CONTRACT_AGENT_INFO_chainId),
            (p.get("AGENTHASH"), 74_CS_GET_CONTRACT_AGENT_INFO_agentHash),
            (p.get("CONTRACTADDRESS"), 74_CS_GET_CONTRACT_AGENT_INFO_contractAddress),
            (p.get("CONTRACTSENDER"), 74_CS_GET_CONTRACT_AGENT_INFO_contractSender)
        ]],
        [
            CS_GET_CONTRACT_DEPOSIT_INFO, [
            (p.get("CHAINID"), 75_CS_GET_CONTRACT_DEPOSIT_INFO_chainId),
            (p.get("JOINAGENTHASH"), 75_CS_GET_CONTRACT_DEPOSIT_INFO_joinAgentHash),
            (p.get("CONTRACTADDRESS"), 75_CS_GET_CONTRACT_DEPOSIT_INFO_contractAddress),
            (p.get("CONTRACTSENDER"), 75_CS_GET_CONTRACT_DEPOSIT_INFO_contractSender)
        ]],
        [
            CS_GET_DEPOSIT_LIST, [
            (p.get("CHAINID"), 76_CS_GET_DEPOSIT_LIST_chainId),
            (p.get("PAGENUMBER"), 76_CS_GET_DEPOSIT_LIST_pageNumber),
            (p.get("PAGESIZE"), 76_CS_GET_DEPOSIT_LIST_pageSize),
            (p.get("ADDRESS"), 76_CS_GET_DEPOSIT_LIST_address),
            (p.get("AGENTHASH"), 76_CS_GET_DEPOSIT_LIST_agentHash)
        ]],
        [
            CS_GET_INFO, [
            (p.get("CHAINID"), 77_CS_GET_INFO_chainId),
            (p.get("ADDRESS"), 77_CS_GET_INFO_address)
        ]],
        [
            CS_GET_PACKER_INFO, [
            (p.get("CHAINID"), 78_CS_GET_PACKER_INFO_chainId)
        ]],
        [
            CS_GET_PUBLISH_LIST, [
            (p.get("CHAINID"), 79_CS_GET_PUBLISH_LIST_chainId),
            (p.get("ADDRESS"), 79_CS_GET_PUBLISH_LIST_address),
            (p.get("TYPE"), 79_CS_GET_PUBLISH_LIST_type)
        ]],
        [
            CS_GET_ROUND_INFO, [
            (p.get("CHAINID"), 80_CS_GET_ROUND_INFO_chainId)
        ]],
        [
            CS_GET_ROUND_MEMBER_LIST, [
            (p.get("CHAINID"), 81_CS_GET_ROUND_MEMBER_LIST_chainId),
            (p.get("EXTEND"), 81_CS_GET_ROUND_MEMBER_LIST_extend)
        ]],
        [
            CS_GET_SEED_NODE_INFO, [
            (p.get("CHAINID"), 82_CS_GET_SEED_NODE_INFO_chainId)
        ]],
        [
            CS_GET_WHOLEINFO, [
            (p.get("CHAINID"), 83_CS_GET_WHOLEINFO_chainId)
        ]],
        [
            CS_MULTI_DEPOSIT, [
            (p.get("CHAINID"), 84_CS_MULTI_DEPOSIT_chainId),
            (p.get("ADDRESS"), 84_CS_MULTI_DEPOSIT_address),
            (p.get("AGENTHASH"), 84_CS_MULTI_DEPOSIT_agentHash),
            (p.get("DEPOSIT"), 84_CS_MULTI_DEPOSIT_deposit),
            (p.get("PASSWORD"), 84_CS_MULTI_DEPOSIT_password),
            (p.get("SIGNADDRESS"), 84_CS_MULTI_DEPOSIT_signAddress)
        ]],
        [
            CS_MULTI_WITHDRAW, [
            (p.get("CHAINID"), 85_CS_MULTI_WITHDRAW_chainId),
            (p.get("ADDRESS"), 85_CS_MULTI_WITHDRAW_address),
            (p.get("TXHASH"), 85_CS_MULTI_WITHDRAW_txHash),
            (p.get("PASSWORD"), 85_CS_MULTI_WITHDRAW_password),
            (p.get("SIGNADDRESS"), 85_CS_MULTI_WITHDRAW_signAddress)
        ]],
        [
            CS_RANDOM_RAW_SEEDS_COUNT, [
            (p.get("CHAINID"), 86_CS_RANDOM_RAW_SEEDS_COUNT_chainId),
            (p.get("HEIGHT"), 86_CS_RANDOM_RAW_SEEDS_COUNT_height),
            (p.get("COUNT"), 86_CS_RANDOM_RAW_SEEDS_COUNT_count)
        ]],
        [
            CS_RANDOM_RAW_SEEDS_HEIGHT, [
            (p.get("CHAINID"), 87_CS_RANDOM_RAW_SEEDS_HEIGHT_chainId),
            (p.get("STARTHEIGHT"), 87_CS_RANDOM_RAW_SEEDS_HEIGHT_startHeight),
            (p.get("ENDHEIGHT"), 87_CS_RANDOM_RAW_SEEDS_HEIGHT_endHeight)
        ]],
        [
            CS_RANDOM_SEED_COUNT, [
            (p.get("CHAINID"), 88_CS_RANDOM_SEED_COUNT_chainId),
            (p.get("HEIGHT"), 88_CS_RANDOM_SEED_COUNT_height),
            (p.get("COUNT"), 88_CS_RANDOM_SEED_COUNT_count),
            (p.get("ALGORITHM"), 88_CS_RANDOM_SEED_COUNT_algorithm)
        ]],
        [
            CS_RANDOM_SEED_HEIGHT, [
            (p.get("CHAINID"), 89_CS_RANDOM_SEED_HEIGHT_chainId),
            (p.get("STARTHEIGHT"), 89_CS_RANDOM_SEED_HEIGHT_startHeight),
            (p.get("ENDHEIGHT"), 89_CS_RANDOM_SEED_HEIGHT_endHeight),
            (p.get("ALGORITHM"), 89_CS_RANDOM_SEED_HEIGHT_algorithm)
        ]],
        [
            CS_RECEIVE_HEADERLIST, [
            (p.get("CHAINID"), 90_CS_RECEIVE_HEADERLIST_chainId),
            (p.get("HEADERLIST"), 90_CS_RECEIVE_HEADERLIST_headerList)
        ]],
        [
            CS_RUN_CHAIN, [
            (p.get("CHAINID"), 91_CS_RUN_CHAIN_chainId)
        ]],
        [
            CS_RUN_MAINCHAIN, [
            (p.get("CHAINID"), 92_CS_RUN_MAINCHAIN_chainId)
        ]],
        [
            CS_STOPAGENT, [
            (p.get("CHAINID"), 93_CS_STOPAGENT_chainId),
            (p.get("ADDRESS"), 93_CS_STOPAGENT_address),
            (p.get("PASSWORD"), 93_CS_STOPAGENT_password)
        ]],
        [
            CS_STOP_AGENT, [
            (p.get("CHAINID"), 94_CS_STOP_AGENT_chainId),
            (p.get("ADDRESS"), 94_CS_STOP_AGENT_address),
            (p.get("PASSWORD"), 94_CS_STOP_AGENT_password)
        ]],
        [
            CS_STOPCHAIN, [
            (p.get("CHAINID"), 95_CS_STOPCHAIN_chainId)
        ]],
        [
            CS_STOP_CHAIN, [
            (p.get("CHAINID"), 96_CS_STOP_CHAIN_chainId)
        ]],
        [
            CS_STOP_CONTRACT_AGENT, [
            (p.get("CHAINID"), 97_CS_STOP_CONTRACT_AGENT_chainId),
            (p.get("CONTRACTADDRESS"), 97_CS_STOP_CONTRACT_AGENT_contractAddress),
            (p.get("CONTRACTSENDER"), 97_CS_STOP_CONTRACT_AGENT_contractSender),
            (p.get("CONTRACTBALANCE"), 97_CS_STOP_CONTRACT_AGENT_contractBalance),
            (p.get("CONTRACTNONCE"), 97_CS_STOP_CONTRACT_AGENT_contractNonce),
            (p.get("BLOCKTIME"), 97_CS_STOP_CONTRACT_AGENT_blockTime)
        ]],
        [
            CS_STOP_MULTI_AGENT, [
            (p.get("CHAINID"), 98_CS_STOP_MULTI_AGENT_chainId),
            (p.get("ADDRESS"), 98_CS_STOP_MULTI_AGENT_address),
            (p.get("PASSWORD"), 98_CS_STOP_MULTI_AGENT_password),
            (p.get("SIGNADDRESS"), 98_CS_STOP_MULTI_AGENT_signAddress)
        ]],
        [
            CS_TRIGGER_COINBASE_CONTRACT, [
            (p.get("CHAINID"), 99_CS_TRIGGER_COINBASE_CONTRACT_chainId),
            (p.get("TX"), 99_CS_TRIGGER_COINBASE_CONTRACT_tx),
            (p.get("BLOCKHEADER"), 99_CS_TRIGGER_COINBASE_CONTRACT_blockHeader),
            (p.get("STATEROOT"), 99_CS_TRIGGER_COINBASE_CONTRACT_stateRoot)
        ]],
        [
            CS_UPDATE_AGENT_CONSENSUS_STATUS, [
            (p.get("CHAINID"), 100_CS_UPDATE_AGENT_CONSENSUS_STATUS_chainId)
        ]],
        [
            CS_UPDATE_AGENT_STATUS, [
            (p.get("CHAINID"), 101_CS_UPDATE_AGENT_STATUS_chainId),
            (p.get("STATUS"), 101_CS_UPDATE_AGENT_STATUS_status)
        ]],
        [
            CS_VALIDBLOCK, [
            (p.get("CHAINID"), 102_CS_VALIDBLOCK_chainId),
            (p.get("DOWNLOAD"), 102_CS_VALIDBLOCK_download),
            (p.get("BLOCK"), 102_CS_VALIDBLOCK_block)
        ]],
        [
            CS_WITHDRAW, [
            (p.get("CHAINID"), 103_CS_WITHDRAW_chainId),
            (p.get("ADDRESS"), 103_CS_WITHDRAW_address),
            (p.get("TXHASH"), 103_CS_WITHDRAW_txHash),
            (p.get("PASSWORD"), 103_CS_WITHDRAW_password)
        ]],
        [
            DEPOSIT_VALID, [
            (p.get("CHAINID"), 104_DEPOSIT_VALID_chainId),
            (p.get("TX"), 104_DEPOSIT_VALID_tx)
        ]],
        [
            GET_ASSETS_BY_ID, [
            (p.get("CHAINID"), 105_GET_ASSETS_BY_ID_chainId),
            (p.get("ASSETIDS"), 105_GET_ASSETS_BY_ID_assetIds)
        ]],
        [
            GET_BALANCE, [
            (p.get("CHAINID"), 106_GET_BALANCE_chainId),
            (p.get("ASSETCHAINID"), 106_GET_BALANCE_assetChainId),
            (p.get("ASSETID"), 106_GET_BALANCE_assetId),
            (p.get("ADDRESS"), 106_GET_BALANCE_address)
        ]],
        [
            GET_BALANCE_NONCE, [
            (p.get("CHAINID"), 107_GET_BALANCE_NONCE_chainId),
            (p.get("ASSETCHAINID"), 107_GET_BALANCE_NONCE_assetChainId),
            (p.get("ASSETID"), 107_GET_BALANCE_NONCE_assetId),
            (p.get("ADDRESS"), 107_GET_BALANCE_NONCE_address),
            (p.get("ISCONFIRMED"), 107_GET_BALANCE_NONCE_isConfirmed)
        ]],
        [
            GET_BLOCK_BY_HASH, [
            (p.get("CHAINID"), 108_GET_BLOCK_BY_HASH_chainId),
            (p.get("HASH"), 108_GET_BLOCK_BY_HASH_hash)
        ]],
        [
            GET_BLOCK_BY_HEIGHT, [
            (p.get("CHAINID"), 109_GET_BLOCK_BY_HEIGHT_chainId),
            (p.get("HEIGHT"), 109_GET_BLOCK_BY_HEIGHT_height)
        ]],
        [
            GET_BLOCKHEADER_BY_HASH, [
            (p.get("CHAINID"), 110_GET_BLOCKHEADER_BY_HASH_chainId),
            (p.get("HASH"), 110_GET_BLOCKHEADER_BY_HASH_hash)
        ]],
        [
            GET_BLOCKHEADER_BY_HEIGHT, [
            (p.get("CHAINID"), 111_GET_BLOCKHEADER_BY_HEIGHT_chainId),
            (p.get("HEIGHT"), 111_GET_BLOCKHEADER_BY_HEIGHT_height)
        ]],
        [
            GET_BLOCKHEADER_PO_BY_HASH, [
            (p.get("CHAINID"), 112_GET_BLOCKHEADER_PO_BY_HASH_chainId),
            (p.get("HASH"), 112_GET_BLOCKHEADER_PO_BY_HASH_hash)
        ]],
        [
            GET_BLOCKHEADER_POBY_HEIGHT, [
            (p.get("CHAINID"), 113_GET_BLOCKHEADER_POBY_HEIGHT_chainId),
            (p.get("HEIGHT"), 113_GET_BLOCKHEADER_POBY_HEIGHT_height)
        ]],
        [
            GET_BLOCKHEADERS_BY_HEIGHT_RANGE, [
            (p.get("CHAINID"), 114_GET_BLOCKHEADERS_BY_HEIGHT_RANGE_chainId),
            (p.get("BEGIN"), 114_GET_BLOCKHEADERS_BY_HEIGHT_RANGE_begin),
            (p.get("END"), 114_GET_BLOCKHEADERS_BY_HEIGHT_RANGE_end)
        ]],
        [
            GET_BLOCKHEADERS_FOR_PROTOCOL, [
            (p.get("CHAINID"), 115_GET_BLOCKHEADERS_FOR_PROTOCOL_chainId),
            (p.get("INTERVAL"), 115_GET_BLOCKHEADERS_FOR_PROTOCOL_interval)
        ]],
        [
            GET_BYZANTINE_COUNT, [
            (p.get("CHAINID"), 116_GET_BYZANTINE_COUNT_chainId)
        ]],
        [
            GET_CIRCULAT, [
            (p.get("CHAINID"), 117_GET_CIRCULAT_chainId),
            (p.get("NODEID"), 117_GET_CIRCULAT_nodeId),
            (p.get("MESSAGEBODY"), 117_GET_CIRCULAT_messageBody)
        ]],
        [
            GET_CROSSTX_STATE, [
            (p.get("CHAINID"), 119_GET_CROSSTX_STATE_chainId),
            (p.get("TXHASH"), 119_GET_CROSSTX_STATE_txHash)
        ]],
        [
            GET_CTX, [
            (p.get("CHAINID"), 120_GET_CTX_chainId),
            (p.get("NODEID"), 120_GET_CTX_nodeId),
            (p.get("MESSAGEBODY"), 120_GET_CTX_messageBody)
        ]],
        [
            GET_CTX_STATE, [
            (p.get("CHAINID"), 121_GET_CTX_STATE_chainId),
            (p.get("NODEID"), 121_GET_CTX_STATE_nodeId),
            (p.get("MESSAGEBODY"), 121_GET_CTX_STATE_messageBody)
        ]],
        [
            GET_FRIEND_CHAIN_CIRCULATE, [
            (p.get("CHAINID"), 122_GET_FRIEND_CHAIN_CIRCULATE_chainId),
            (p.get("ASSETIDS"), 122_GET_FRIEND_CHAIN_CIRCULATE_assetIds)
        ]],
        [
            GET_LATEST_BLOCKHEADERS, [
            (p.get("CHAINID"), 123_GET_LATEST_BLOCKHEADERS_chainId),
            (p.get("SIZE"), 123_GET_LATEST_BLOCKHEADERS_size)
        ]],
        [
            GET_LATEST_ROUND_BLOCKHEADERS, [
            (p.get("CHAINID"), 124_GET_LATEST_ROUND_BLOCKHEADERS_chainId),
            (p.get("ROUND"), 124_GET_LATEST_ROUND_BLOCKHEADERS_round)
        ]],
        [
            GET_NONCE, [
            (p.get("CHAINID"), 125_GET_NONCE_chainId),
            (p.get("ASSETCHAINID"), 125_GET_NONCE_assetChainId),
            (p.get("ASSETID"), 125_GET_NONCE_assetId),
            (p.get("ADDRESS"), 125_GET_NONCE_address),
            (p.get("ISCONFIRMED"), 125_GET_NONCE_isConfirmed)
        ]],
        [
            GET_OTHERCTX, [
            (p.get("CHAINID"), 126_GET_OTHERCTX_chainId),
            (p.get("NODEID"), 126_GET_OTHERCTX_nodeId),
            (p.get("MESSAGEBODY"), 126_GET_OTHERCTX_messageBody)
        ]],
        [
            GET_ROUND_BLOCKHEADERS, [
            (p.get("CHAINID"), 128_GET_ROUND_BLOCKHEADERS_chainId),
            (p.get("HEIGHT"), 128_GET_ROUND_BLOCKHEADERS_height),
            (p.get("ROUND"), 128_GET_ROUND_BLOCKHEADERS_round)
        ]],
        [
            GET_STATUS, [
            (p.get("CHAINID"), 129_GET_STATUS_chainId)
        ]],
        [
            GET_VERSION, [
            (p.get("CHAINID"), 130_GET_VERSION_chainId)
        ]],
        [
            INFO, [
            (p.get("CHAINID"), 131_INFO_chainId)
        ]],
        [
            LATEST_BLOCK, [
            (p.get("CHAINID"), 132_LATEST_BLOCK_chainId)
        ]],
        [
            LATEST_BLOCKHEADER, [
            (p.get("CHAINID"), 133_LATEST_BLOCKHEADER_chainId)
        ]],
        [
            LATEST_BLOCKHEADER_PO, [
            (p.get("CHAINID"), 134_LATEST_BLOCKHEADER_PO_chainId)
        ]],
        [
            LATEST_HEIGHT, [
            (p.get("CHAINID"), 135_LATEST_HEIGHT_chainId)
        ]],
        [
            MSG_PROCESS, [
            (p.get("CHAINID"), 137_MSG_PROCESS_chainId),
            (p.get("NODEID"), 137_MSG_PROCESS_nodeId),
            (p.get("CMD"), 137_MSG_PROCESS_cmd),
            (p.get("MESSAGEBODY"), 137_MSG_PROCESS_messageBody)
        ]],
        [
            NEW_BLOCK_HEIGHT, [
            (p.get("CHAINID"), 138_NEW_BLOCK_HEIGHT_chainId),
            (p.get("HEIGHT"), 138_NEW_BLOCK_HEIGHT_height)
        ]],
        [
            NW_ACTIVE_CROSS, [
            (p.get("CHAINID"), 139_NW_ACTIVE_CROSS_chainId),
            (p.get("MAXOUT"), 139_NW_ACTIVE_CROSS_maxOut),
            (p.get("MAXIN"), 139_NW_ACTIVE_CROSS_maxIn),
            (p.get("SEEDIPS"), 139_NW_ACTIVE_CROSS_seedIps)
        ]],
        [
            NW_ADD_NODES, [
            (p.get("CHAINID"), 140_NW_ADD_NODES_chainId),
            (p.get("ISCROSS"), 140_NW_ADD_NODES_isCross),
            (p.get("NODES"), 140_NW_ADD_NODES_nodes)
        ]],
        [
            NW_BROADCAST, [
            (p.get("CHAINID"), 141_NW_BROADCAST_chainId),
            (p.get("EXCLUDENODES"), 141_NW_BROADCAST_excludeNodes),
            (p.get("MESSAGEBODY"), 141_NW_BROADCAST_messageBody),
            (p.get("COMMAND"), 141_NW_BROADCAST_command),
            (p.get("ISCROSS"), 141_NW_BROADCAST_isCross),
            (p.get("PERCENT"), 141_NW_BROADCAST_percent)
        ]],
        [
            NW_CREATE_NODEGROUP, [
            (p.get("CHAINID"), 142_NW_CREATE_NODEGROUP_chainId),
            (p.get("MAGICNUMBER"), 142_NW_CREATE_NODEGROUP_magicNumber),
            (p.get("MAXOUT"), 142_NW_CREATE_NODEGROUP_maxOut),
            (p.get("MAXIN"), 142_NW_CREATE_NODEGROUP_maxIn),
            (p.get("MINAVAILABLECOUNT"), 142_NW_CREATE_NODEGROUP_minAvailableCount),
            (p.get("ISCROSSGROUP"), 142_NW_CREATE_NODEGROUP_isCrossGroup)
        ]],
        [
            NW_DEL_NODES, [
            (p.get("CHAINID"), 143_NW_DEL_NODES_chainId),
            (p.get("NODES"), 143_NW_DEL_NODES_nodes)
        ]],
        [
            NW_GET_CHAIN_CONNECT_AMOUNT, [
            (p.get("CHAINID"), 144_NW_GET_CHAIN_CONNECT_AMOUNT_chainId),
            (p.get("ISCROSS"), 144_NW_GET_CHAIN_CONNECT_AMOUNT_isCross)
        ]],
        [
            NW_GET_GROUP_BY_CHAINID, [
            (p.get("CHAINID"), 145_NW_GET_GROUP_BY_CHAINID_chainId)
        ]],
        [
            NW_GET_GROUPS, [
            (p.get("STARTPAGE"), 146_NW_GET_GROUPS_startPage),
            (p.get("PAGESIZE"), 146_NW_GET_GROUPS_pageSize)
        ]],
        [
            NW_GET_NODES, [
            (p.get("CHAINID"), 147_NW_GET_NODES_chainId),
            (p.get("STATE"), 147_NW_GET_NODES_state),
            (p.get("ISCROSS"), 147_NW_GET_NODES_isCross),
            (p.get("STARTPAGE"), 147_NW_GET_NODES_startPage),
            (p.get("PAGESIZE"), 147_NW_GET_NODES_pageSize)
        ]],
        [
            NW_INFO, [
            (p.get("CHAINID"), 149_NW_INFO_chainId)
        ]],
        [
            NW_NODES, [
            (p.get("CHAINID"), 150_NW_NODES_chainId)
        ]],
        [
            NW_PROTOCOL_REGISTER, [
            (p.get("ROLE"), 151_NW_PROTOCOL_REGISTER_role),
            (p.get("PROTOCOLCMDS"), 151_NW_PROTOCOL_REGISTER_protocolCmds)
        ]],
        [
            NW_RECONNECT, [
            (p.get("CHAINID"), 152_NW_RECONNECT_chainId)
        ]],
        [
            NW_SEND_PEERS_MSG, [
            (p.get("CHAINID"), 153_NW_SEND_PEERS_MSG_chainId),
            (p.get("NODES"), 153_NW_SEND_PEERS_MSG_nodes),
            (p.get("MESSAGEBODY"), 153_NW_SEND_PEERS_MSG_messageBody),
            (p.get("COMMAND"), 153_NW_SEND_PEERS_MSG_command)
        ]],
        [
            NW_UPDATE_NODE_INFO, [
            (p.get("CHAINID"), 154_NW_UPDATE_NODE_INFO_chainId),
            (p.get("NODEID"), 154_NW_UPDATE_NODE_INFO_nodeId),
            (p.get("BLOCKHEIGHT"), 154_NW_UPDATE_NODE_INFO_blockHeight),
            (p.get("BLOCKHASH"), 154_NW_UPDATE_NODE_INFO_blockHash)
        ]],
        [
            PARAM_TEST_CMD, [
            (p.get("INTCOUNT"), 155_PARAM_TEST_CMD_intCount),
            (p.get("BYTECOUNT"), 155_PARAM_TEST_CMD_byteCount),
            (p.get("SHORTCOUNT"), 155_PARAM_TEST_CMD_shortCount),
            (p.get("LONGCOUNT"), 155_PARAM_TEST_CMD_longCount)
        ]],
        [
            PROTOCOL_VERSION_CHANGE, [
            (p.get("CHAINID"), 156_PROTOCOL_VERSION_CHANGE_chainId),
            (p.get("PROTOCOLVERSION"), 156_PROTOCOL_VERSION_CHANGE_protocolVersion)
        ]],
        [
            RECEIVE_PACKING_BLOCK, [
            (p.get("CHAINID"), 157_RECEIVE_PACKING_BLOCK_chainId),
            (p.get("BLOCK"), 157_RECEIVE_PACKING_BLOCK_block)
        ]],
        [
            RECV_CIRCULAT, [
            (p.get("CHAINID"), 158_RECV_CIRCULAT_chainId),
            (p.get("NODEID"), 158_RECV_CIRCULAT_nodeId),
            (p.get("MESSAGEBODY"), 158_RECV_CIRCULAT_messageBody)
        ]],
        [
            RECV_CTX, [
            (p.get("CHAINID"), 159_RECV_CTX_chainId),
            (p.get("NODEID"), 159_RECV_CTX_nodeId),
            (p.get("MESSAGEBODY"), 159_RECV_CTX_messageBody)
        ]],
        [
            RECV_CTX_HASH, [
            (p.get("CHAINID"), 160_RECV_CTX_HASH_chainId),
            (p.get("NODEID"), 160_RECV_CTX_HASH_nodeId),
            (p.get("MESSAGEBODY"), 160_RECV_CTX_HASH_messageBody)
        ]],
        [
            RECV_CTX_SIGN, [
            (p.get("CHAINID"), 161_RECV_CTX_SIGN_chainId),
            (p.get("NODEID"), 161_RECV_CTX_SIGN_nodeId),
            (p.get("MESSAGEBODY"), 161_RECV_CTX_SIGN_messageBody)
        ]],
        [
            RECV_CTX_STATE, [
            (p.get("CHAINID"), 162_RECV_CTX_STATE_chainId),
            (p.get("NODEID"), 162_RECV_CTX_STATE_nodeId),
            (p.get("MESSAGEBODY"), 162_RECV_CTX_STATE_messageBody)
        ]],
        [
            RECV_OTHER_CTX, [
            (p.get("CHAINID"), 163_RECV_OTHER_CTX_chainId),
            (p.get("NODEID"), 163_RECV_OTHER_CTX_nodeId),
            (p.get("MESSAGEBODY"), 163_RECV_OTHER_CTX_messageBody)
        ]],
        [
            RECV_REGCHAIN, [
            (p.get("CHAINID"), 164_RECV_REGCHAIN_chainId),
            (p.get("NODEID"), 164_RECV_REGCHAIN_nodeId),
            (p.get("MESSAGEBODY"), 164_RECV_REGCHAIN_messageBody)
        ]],
        [
            REGISTER_PROTOCOL, [
            (p.get("CHAINID"), 166_REGISTER_PROTOCOL_chainId),
            (p.get("MODULECODE"), 166_REGISTER_PROTOCOL_moduleCode),
            (p.get("LIST"), 166_REGISTER_PROTOCOL_list)
        ]],
        [
            ROLLBACK_BLOCK_TXS, [
            (p.get("CHAINID"), 167_ROLLBACK_BLOCK_TXS_chainId),
            (p.get("TXLIST"), 167_ROLLBACK_BLOCK_TXS_txList),
            (p.get("BLOCKHEIGHT"), 167_ROLLBACK_BLOCK_TXS_blockHeight)
        ]],
        [
            ROLLBACK_UNCONFIRM_TX, [
            (p.get("CHAINID"), 168_ROLLBACK_UNCONFIRM_TX_chainId),
            (p.get("TX"), 168_ROLLBACK_UNCONFIRM_TX_tx)
        ]],
        [
            ROLLBACK_BLOCK, [
            (p.get("CHAINID"), 169_ROLLBACK_BLOCK_chainId),
            (p.get("BLOCKHEADER"), 169_ROLLBACK_BLOCK_blockHeader)
        ]],
        [
            ROLLBACK_TX_VALIDATE_STATUS, [
            (p.get("CHAINID"), 170_ROLLBACK_TX_VALIDATE_STATUS_chainId),
            (p.get("TX"), 170_ROLLBACK_TX_VALIDATE_STATUS_tx)
        ]],
        [
            SAVE_BLOCK, [
            (p.get("CHAINID"), 171_SAVE_BLOCK_chainId),
            (p.get("BLOCKHEADER"), 171_SAVE_BLOCK_blockHeader)
        ]],
        [
            SC_BATCH_BEFORE_END, [
            (p.get("CHAINID"), 172_SC_BATCH_BEFORE_END_chainId),
            (p.get("BLOCKTYPE"), 172_SC_BATCH_BEFORE_END_blockType),
            (p.get("BLOCKHEIGHT"), 172_SC_BATCH_BEFORE_END_blockHeight)
        ]],
        [
            SC_BATCH_BEGIN, [
            (p.get("CHAINID"), 173_SC_BATCH_BEGIN_chainId),
            (p.get("BLOCKTYPE"), 173_SC_BATCH_BEGIN_blockType),
            (p.get("BLOCKHEIGHT"), 173_SC_BATCH_BEGIN_blockHeight),
            (p.get("BLOCKTIME"), 173_SC_BATCH_BEGIN_blockTime),
            (p.get("PACKINGADDRESS"), 173_SC_BATCH_BEGIN_packingAddress),
            (p.get("PRESTATEROOT"), 173_SC_BATCH_BEGIN_preStateRoot)
        ]],
        [
            SC_BATCH_END, [
            (p.get("CHAINID"), 174_SC_BATCH_END_chainId),
            (p.get("BLOCKHEIGHT"), 174_SC_BATCH_END_blockHeight)
        ]],
        [
            SC_CALL, [
            (p.get("CHAINID"), 175_SC_CALL_chainId),
            (p.get("SENDER"), 175_SC_CALL_sender),
            (p.get("PASSWORD"), 175_SC_CALL_password),
            (p.get("VALUE"), 175_SC_CALL_value),
            (p.get("GASLIMIT"), 175_SC_CALL_gasLimit),
            (p.get("PRICE"), 175_SC_CALL_price),
            (p.get("CONTRACTADDRESS"), 175_SC_CALL_contractAddress),
            (p.get("METHODNAME"), 175_SC_CALL_methodName),
            (p.get("METHODDESC"), 175_SC_CALL_methodDesc),
            (p.get("ARGS"), 175_SC_CALL_args),
            (p.get("REMARK"), 175_SC_CALL_remark)
        ]],
        [
            SC_CALL_VALIDATOR, [
            (p.get("CHAINID"), 176_SC_CALL_VALIDATOR_chainId),
            (p.get("TX"), 176_SC_CALL_VALIDATOR_tx)
        ]],
        [
            SC_CONSTRUCTOR, [
            (p.get("CHAINID"), 177_SC_CONSTRUCTOR_chainId),
            (p.get("CONTRACTCODE"), 177_SC_CONSTRUCTOR_contractCode)
        ]],
        [
            SC_CONTRACT_INFO, [
            (p.get("CHAINID"), 178_SC_CONTRACT_INFO_chainId),
            (p.get("CONTRACTADDRESS"), 178_SC_CONTRACT_INFO_contractAddress)
        ]],
        [
            SC_CONTRACT_OFFLINE_TX_HASH_LIST, [
            (p.get("CHAINID"), 179_SC_CONTRACT_OFFLINE_TX_HASH_LIST_chainId),
            (p.get("BLOCKHASH"), 179_SC_CONTRACT_OFFLINE_TX_HASH_LIST_blockHash)
        ]],
        [
            SC_CONTRACT_RESULT, [
            (p.get("CHAINID"), 180_SC_CONTRACT_RESULT_chainId),
            (p.get("HASH"), 180_SC_CONTRACT_RESULT_hash)
        ]],
        [
            SC_CONTRACT_RESULT_LIST, [
            (p.get("CHAINID"), 181_SC_CONTRACT_RESULT_LIST_chainId),
            (p.get("HASHLIST"), 181_SC_CONTRACT_RESULT_LIST_hashList)
        ]],
        [
            SC_CONTRACT_TX, [
            (p.get("CHAINID"), 182_SC_CONTRACT_TX_chainId),
            (p.get("HASH"), 182_SC_CONTRACT_TX_hash)
        ]],
        [
            SC_CREATE, [
            (p.get("CHAINID"), 183_SC_CREATE_chainId),
            (p.get("SENDER"), 183_SC_CREATE_sender),
            (p.get("PASSWORD"), 183_SC_CREATE_password),
            (p.get("ALIAS"), 183_SC_CREATE_alias),
            (p.get("GASLIMIT"), 183_SC_CREATE_gasLimit),
            (p.get("PRICE"), 183_SC_CREATE_price),
            (p.get("CONTRACTCODE"), 183_SC_CREATE_contractCode),
            (p.get("ARGS"), 183_SC_CREATE_args),
            (p.get("REMARK"), 183_SC_CREATE_remark)
        ]],
        [
            SC_CREATE_VALIDATOR, [
            (p.get("CHAINID"), 184_SC_CREATE_VALIDATOR_chainId),
            (p.get("TX"), 184_SC_CREATE_VALIDATOR_tx)
        ]],
        [
            SC_DELETE, [
            (p.get("CHAINID"), 185_SC_DELETE_chainId),
            (p.get("SENDER"), 185_SC_DELETE_sender),
            (p.get("PASSWORD"), 185_SC_DELETE_password),
            (p.get("CONTRACTADDRESS"), 185_SC_DELETE_contractAddress),
            (p.get("REMARK"), 185_SC_DELETE_remark)
        ]],
        [
            SC_DELETE_VALIDATOR, [
            (p.get("CHAINID"), 186_SC_DELETE_VALIDATOR_chainId),
            (p.get("TX"), 186_SC_DELETE_VALIDATOR_tx)
        ]],
        [
            SC_IMPUTED_CALL_GAS, [
            (p.get("CHAINID"), 187_SC_IMPUTED_CALL_GAS_chainId),
            (p.get("SENDER"), 187_SC_IMPUTED_CALL_GAS_sender),
            (p.get("VALUE"), 187_SC_IMPUTED_CALL_GAS_value),
            (p.get("CONTRACTADDRESS"), 187_SC_IMPUTED_CALL_GAS_contractAddress),
            (p.get("METHODNAME"), 187_SC_IMPUTED_CALL_GAS_methodName),
            (p.get("METHODDESC"), 187_SC_IMPUTED_CALL_GAS_methodDesc),
            (p.get("ARGS"), 187_SC_IMPUTED_CALL_GAS_args)
        ]],
        [
            SC_IMPUTED_CREATE_GAS, [
            (p.get("CHAINID"), 188_SC_IMPUTED_CREATE_GAS_chainId),
            (p.get("SENDER"), 188_SC_IMPUTED_CREATE_GAS_sender),
            (p.get("CONTRACTCODE"), 188_SC_IMPUTED_CREATE_GAS_contractCode),
            (p.get("ARGS"), 188_SC_IMPUTED_CREATE_GAS_args)
        ]],
        [
            SC_INITIAL_ACCOUNT_TOKEN, [
            (p.get("CHAINID"), 189_SC_INITIAL_ACCOUNT_TOKEN_chainId),
            (p.get("ADDRESS"), 189_SC_INITIAL_ACCOUNT_TOKEN_address)
        ]],
        [
            SC_INVOKE_CONTRACT, [
            (p.get("CHAINID"), 190_SC_INVOKE_CONTRACT_chainId),
            (p.get("BLOCKTYPE"), 190_SC_INVOKE_CONTRACT_blockType),
            (p.get("TX"), 190_SC_INVOKE_CONTRACT_tx)
        ]],
        [
            SC_INVOKE_VIEW, [
            (p.get("CHAINID"), 191_SC_INVOKE_VIEW_chainId),
            (p.get("CONTRACTADDRESS"), 191_SC_INVOKE_VIEW_contractAddress),
            (p.get("METHODNAME"), 191_SC_INVOKE_VIEW_methodName),
            (p.get("METHODDESC"), 191_SC_INVOKE_VIEW_methodDesc),
            (p.get("ARGS"), 191_SC_INVOKE_VIEW_args)
        ]],
        [
            SC_PACKAGE_BATCH_END, [
            (p.get("CHAINID"), 192_SC_PACKAGE_BATCH_END_chainId),
            (p.get("BLOCKHEIGHT"), 192_SC_PACKAGE_BATCH_END_blockHeight)
        ]],
        [
            SC_TOKEN_ASSETS_LIST, [
            (p.get("CHAINID"), 193_SC_TOKEN_ASSETS_LIST_chainId),
            (p.get("ADDRESS"), 193_SC_TOKEN_ASSETS_LIST_address),
            (p.get("PAGENUMBER"), 193_SC_TOKEN_ASSETS_LIST_pageNumber),
            (p.get("PAGESIZE"), 193_SC_TOKEN_ASSETS_LIST_pageSize)
        ]],
        [
            SC_TOKEN_BALANCE, [
            (p.get("CHAINID"), 194_SC_TOKEN_BALANCE_chainId),
            (p.get("CONTRACTADDRESS"), 194_SC_TOKEN_BALANCE_contractAddress),
            (p.get("ADDRESS"), 194_SC_TOKEN_BALANCE_address)
        ]],
        [
            SC_TOKEN_TRANSFER, [
            (p.get("CHAINID"), 195_SC_TOKEN_TRANSFER_chainId),
            (p.get("ADDRESS"), 195_SC_TOKEN_TRANSFER_address),
            (p.get("TOADDRESS"), 195_SC_TOKEN_TRANSFER_toAddress),
            (p.get("CONTRACTADDRESS"), 195_SC_TOKEN_TRANSFER_contractAddress),
            (p.get("PASSWORD"), 195_SC_TOKEN_TRANSFER_password),
            (p.get("AMOUNT"), 195_SC_TOKEN_TRANSFER_amount),
            (p.get("REMARK"), 195_SC_TOKEN_TRANSFER_remark)
        ]],
        [
            SC_TOKEN_TRANSFER_LIST, [
            (p.get("CHAINID"), 196_SC_TOKEN_TRANSFER_LIST_chainId),
            (p.get("ADDRESS"), 196_SC_TOKEN_TRANSFER_LIST_address),
            (p.get("PAGENUMBER"), 196_SC_TOKEN_TRANSFER_LIST_pageNumber),
            (p.get("PAGESIZE"), 196_SC_TOKEN_TRANSFER_LIST_pageSize)
        ]],
        [
            SC_TRANSFER, [
            (p.get("CHAINID"), 197_SC_TRANSFER_chainId),
            (p.get("ADDRESS"), 197_SC_TRANSFER_address),
            (p.get("TOADDRESS"), 197_SC_TRANSFER_toAddress),
            (p.get("PASSWORD"), 197_SC_TRANSFER_password),
            (p.get("AMOUNT"), 197_SC_TRANSFER_amount),
            (p.get("REMARK"), 197_SC_TRANSFER_remark)
        ]],
        [
            SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT, [
            (p.get("CHAINID"), 198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_chainId),
            (p.get("STATEROOT"), 198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_stateRoot),
            (p.get("BLOCKHEIGHT"), 198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_blockHeight),
            (p.get("CONTRACTADDRESS"), 198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_contractAddress),
            (p.get("TX"), 198_SC_TRIGGER_PAYABLE_FOR_CONSENSUS_CONTRACT_tx)
        ]],
        [
            SC_UPLOAD, [
            (p.get("CHAINID"), 199_SC_UPLOAD_chainId),
            (p.get("JARFILEDATA"), 199_SC_UPLOAD_jarFileData)
        ]],
        [
            SC_VALIDATE_CALL, [
            (p.get("CHAINID"), 200_SC_VALIDATE_CALL_chainId),
            (p.get("SENDER"), 200_SC_VALIDATE_CALL_sender),
            (p.get("VALUE"), 200_SC_VALIDATE_CALL_value),
            (p.get("GASLIMIT"), 200_SC_VALIDATE_CALL_gasLimit),
            (p.get("PRICE"), 200_SC_VALIDATE_CALL_price),
            (p.get("CONTRACTADDRESS"), 200_SC_VALIDATE_CALL_contractAddress),
            (p.get("METHODNAME"), 200_SC_VALIDATE_CALL_methodName),
            (p.get("METHODDESC"), 200_SC_VALIDATE_CALL_methodDesc),
            (p.get("ARGS"), 200_SC_VALIDATE_CALL_args)
        ]],
        [
            SC_VALIDATE_CREATE, [
            (p.get("CHAINID"), 201_SC_VALIDATE_CREATE_chainId),
            (p.get("SENDER"), 201_SC_VALIDATE_CREATE_sender),
            (p.get("GASLIMIT"), 201_SC_VALIDATE_CREATE_gasLimit),
            (p.get("PRICE"), 201_SC_VALIDATE_CREATE_price),
            (p.get("CONTRACTCODE"), 201_SC_VALIDATE_CREATE_contractCode),
            (p.get("ARGS"), 201_SC_VALIDATE_CREATE_args)
        ]],
        [
            SC_VALIDATE_DELETE, [
            (p.get("CHAINID"), 202_SC_VALIDATE_DELETE_chainId),
            (p.get("CONTRACTADDRESS"), 202_SC_VALIDATE_DELETE_contractAddress)
        ]],
        [
            STOP_AGENTVALID, [
            (p.get("CHAINID"), 203_STOP_AGENTVALID_chainId),
            (p.get("TX"), 203_STOP_AGENTVALID_tx)
        ]],
        [
            TX_COMMIT, [
            (p.get("CHAINID"), 204_TX_COMMIT_chainId),
            (p.get("TXLIST"), 204_TX_COMMIT_txList),
            (p.get("BLOCKHEADER"), 204_TX_COMMIT_blockHeader)
        ]],
        [
            TX_VALIDATOR, [
            (p.get("CHAINID"), 205_TX_VALIDATOR_chainId),
            (p.get("TXLIST"), 205_TX_VALIDATOR_txList),
            (p.get("BLOCKHEADER"), 205_TX_VALIDATOR_blockHeader)
        ]],
        [
            TX_BACK_PACKABLE_TXS, [
            (p.get("CHAINID"), 206_TX_BACK_PACKABLE_TXS_chainId),
            (p.get("TXLIST"), 206_TX_BACK_PACKABLE_TXS_txList)
        ]],
        [
            TX_BATCH_VERIFY, [
            (p.get("CHAINID"), 207_TX_BATCH_VERIFY_chainId),
            (p.get("TXLIST"), 207_TX_BATCH_VERIFY_txList),
            (p.get("BLOCKHEADER"), 207_TX_BATCH_VERIFY_blockHeader),
            (p.get("PRESTATEROOT"), 207_TX_BATCH_VERIFY_preStateRoot)
        ]],
        [
            TX_BL_STATE, [
            (p.get("CHAINID"), 208_TX_BL_STATE_chainId),
            (p.get("STATUS"), 208_TX_BL_STATE_status)
        ]],
        [
            TX_BLOCK_HEIGHT, [
            (p.get("CHAINID"), 209_TX_BLOCK_HEIGHT_chainId),
            (p.get("HEIGHT"), 209_TX_BLOCK_HEIGHT_height)
        ]],
        [
            TX_CS_STATE, [
            (p.get("CHAINID"), 210_TX_CS_STATE_chainId),
            (p.get("PACKAGING"), 210_TX_CS_STATE_packaging)
        ]],
        [
            TX_GET_BLOCKTXS, [
            (p.get("CHAINID"), 211_TX_GET_BLOCKTXS_chainId),
            (p.get("TXHASHLIST"), 211_TX_GET_BLOCKTXS_txHashList)
        ]],
        [
            TX_GET_BLOCKTXS_EXTEND, [
            (p.get("CHAINID"), 212_TX_GET_BLOCKTXS_EXTEND_chainId),
            (p.get("TXHASHLIST"), 212_TX_GET_BLOCKTXS_EXTEND_txHashList),
            (p.get("ALLHITS"), 212_TX_GET_BLOCKTXS_EXTEND_allHits)
        ]],
        [
            TX_GET_CONFIRMED_TX, [
            (p.get("CHAINID"), 213_TX_GET_CONFIRMED_TX_chainId),
            (p.get("TXHASH"), 213_TX_GET_CONFIRMED_TX_txHash)
        ]],
        [
            TX_GET_CONFIRMED_TX_CLIENT, [
            (p.get("CHAINID"), 214_TX_GET_CONFIRMED_TX_CLIENT_chainId),
            (p.get("TXHASH"), 214_TX_GET_CONFIRMED_TX_CLIENT_txHash)
        ]],
        [
            TX_GET_NONEXISTENT_UNCONFIRMED_HASHS, [
            (p.get("CHAINID"), 215_TX_GET_NONEXISTENT_UNCONFIRMED_HASHS_chainId),
            (p.get("TXHASHLIST"), 215_TX_GET_NONEXISTENT_UNCONFIRMED_HASHS_txHashList)
        ]],
        [
            TX_GET_SYSTEMTYPES, [
            (p.get("CHAINID"), 216_TX_GET_SYSTEMTYPES_chainId)
        ]],
        [
            TX_GET_TX, [
            (p.get("CHAINID"), 217_TX_GET_TX_chainId),
            (p.get("TXHASH"), 217_TX_GET_TX_txHash)
        ]],
        [
            TX_GET_TX_CLIENT, [
            (p.get("CHAINID"), 218_TX_GET_TX_CLIENT_chainId),
            (p.get("TXHASH"), 218_TX_GET_TX_CLIENT_txHash)
        ]],
        [
            TX_NEWTX, [
            (p.get("CHAINID"), 219_TX_NEWTX_chainId),
            (p.get("TX"), 219_TX_NEWTX_tx)
        ]],
        [
            TX_PACKABLE_TXS, [
            (p.get("CHAINID"), 220_TX_PACKABLE_TXS_chainId),
            (p.get("ENDTIMESTAMP"), 220_TX_PACKABLE_TXS_endTimestamp),
            (p.get("MAXTXDATASIZE"), 220_TX_PACKABLE_TXS_maxTxDataSize),
            (p.get("BLOCKTIME"), 220_TX_PACKABLE_TXS_blockTime),
            (p.get("PACKINGADDRESS"), 220_TX_PACKABLE_TXS_packingAddress),
            (p.get("PRESTATEROOT"), 220_TX_PACKABLE_TXS_preStateRoot)
        ]],
        [
            TX_REGISTER, [
            (p.get("CHAINID"), 221_TX_REGISTER_chainId),
            (p.get("MODULECODE"), 221_TX_REGISTER_moduleCode),
            (p.get("LIST"), 221_TX_REGISTER_list),
            (p.get("DELLIST"), 221_TX_REGISTER_delList)
        ]],
        [
            TX_ROLLBACK, [
            (p.get("CHAINID"), 222_TX_ROLLBACK_chainId),
            (p.get("TXHASHLIST"), 222_TX_ROLLBACK_txHashList),
            (p.get("BLOCKHEADER"), 222_TX_ROLLBACK_blockHeader)
        ]],
        [
            TX_SAVE, [
            (p.get("CHAINID"), 223_TX_SAVE_chainId),
            (p.get("TXLIST"), 223_TX_SAVE_txList),
            (p.get("CONTRACTLIST"), 223_TX_SAVE_contractList),
            (p.get("BLOCKHEADER"), 223_TX_SAVE_blockHeader)
        ]],
        [
            TX_VERIFY_TX, [
            (p.get("CHAINID"), 224_TX_VERIFY_TX_chainId),
            (p.get("TX"), 224_TX_VERIFY_TX_tx)
        ]],
        [
            UPDATE_CHAIN_ASSET, [
            (p.get("CHAINID"), 225_UPDATE_CHAIN_ASSET_chainId),
            (p.get("ASSETS"), 225_UPDATE_CHAIN_ASSET_assets)
        ]],
        [
            VERIFY_COINDATA, [
            (p.get("CHAINID"), 226_VERIFY_COINDATA_chainId),
            (p.get("TX"), 226_VERIFY_COINDATA_tx)
        ]],
        [
            VERIFY_COINDATA_BATCH_PACKAGED, [
            (p.get("CHAINID"), 227_VERIFY_COINDATA_BATCH_PACKAGED_chainId),
            (p.get("TXLIST"), 227_VERIFY_COINDATA_BATCH_PACKAGED_txList)
        ]],
        [
            WITHDRAW_VALID, [
            (p.get("CHAINID"), 228_WITHDRAW_VALID_chainId),
            (p.get("TX"), 228_WITHDRAW_VALID_tx)
        ]]
    ]
